// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type UserStatus int64

const (
	UserStatus_BANNED UserStatus = 0
	UserStatus_ACTIVE UserStatus = 1
	UserStatus_POWER  UserStatus = 2
)

func (p UserStatus) String() string {
	switch p {
	case UserStatus_BANNED:
		return "BANNED"
	case UserStatus_ACTIVE:
		return "ACTIVE"
	case UserStatus_POWER:
		return "POWER"
	}
	return "<UNSET>"
}

func UserStatusFromString(s string) (UserStatus, error) {
	switch s {
	case "BANNED":
		return UserStatus_BANNED, nil
	case "ACTIVE":
		return UserStatus_ACTIVE, nil
	case "POWER":
		return UserStatus_POWER, nil
	}
	return UserStatus(0), fmt.Errorf("not a valid UserStatus string")
}

func UserStatusPtr(v UserStatus) *UserStatus { return &v }
func (p *UserStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = UserStatus(result.Int64)
	return
}

func (p *UserStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type User struct {
	Id        int64      `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name      string     `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Email     string     `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Password  string     `thrift:"password,4" frugal:"4,default,string" json:"password"`
	Phone     string     `thrift:"phone,5" frugal:"5,default,string" json:"phone"`
	Avatar    *string    `thrift:"avatar,6,optional" frugal:"6,optional,string" json:"avatar,omitempty"`
	Bio       *string    `thrift:"bio,7,optional" frugal:"7,optional,string" json:"bio,omitempty"`
	Gender    *int32     `thrift:"gender,8,optional" frugal:"8,optional,i32" json:"gender,omitempty"`
	CreatedAt int64      `thrift:"createdAt,9" frugal:"9,default,i64" json:"createdAt"`
	UpdatedAt int64      `thrift:"updatedAt,10" frugal:"10,default,i64" json:"updatedAt"`
	Status    UserStatus `thrift:"status,11" frugal:"11,default,UserStatus" json:"status"`
	LastLogin *int64     `thrift:"lastLogin,12,optional" frugal:"12,optional,i64" json:"lastLogin,omitempty"`
}

func NewUser() *User {
	return &User{
		Status: UserStatus_ACTIVE,
	}
}

func (p *User) InitDefault() {
	p.Status = UserStatus_ACTIVE
}

func (p *User) GetId() (v int64) {
	return p.Id
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetEmail() (v string) {
	return p.Email
}

func (p *User) GetPassword() (v string) {
	return p.Password
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

var User_Avatar_DEFAULT string

func (p *User) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return User_Avatar_DEFAULT
	}
	return *p.Avatar
}

var User_Bio_DEFAULT string

func (p *User) GetBio() (v string) {
	if !p.IsSetBio() {
		return User_Bio_DEFAULT
	}
	return *p.Bio
}

var User_Gender_DEFAULT int32

func (p *User) GetGender() (v int32) {
	if !p.IsSetGender() {
		return User_Gender_DEFAULT
	}
	return *p.Gender
}

func (p *User) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *User) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *User) GetStatus() (v UserStatus) {
	return p.Status
}

var User_LastLogin_DEFAULT int64

func (p *User) GetLastLogin() (v int64) {
	if !p.IsSetLastLogin() {
		return User_LastLogin_DEFAULT
	}
	return *p.LastLogin
}
func (p *User) SetId(val int64) {
	p.Id = val
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetEmail(val string) {
	p.Email = val
}
func (p *User) SetPassword(val string) {
	p.Password = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *User) SetBio(val *string) {
	p.Bio = val
}
func (p *User) SetGender(val *int32) {
	p.Gender = val
}
func (p *User) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *User) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *User) SetStatus(val UserStatus) {
	p.Status = val
}
func (p *User) SetLastLogin(val *int64) {
	p.LastLogin = val
}

func (p *User) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *User) IsSetBio() bool {
	return p.Bio != nil
}

func (p *User) IsSetGender() bool {
	return p.Gender != nil
}

func (p *User) IsSetLastLogin() bool {
	return p.LastLogin != nil
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "email",
	4:  "password",
	5:  "phone",
	6:  "avatar",
	7:  "bio",
	8:  "gender",
	9:  "createdAt",
	10: "updatedAt",
	11: "status",
	12: "lastLogin",
}

type SafeUser struct {
	Id        int64      `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name      string     `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Email     string     `thrift:"email,3" frugal:"3,default,string" json:"email"`
	Phone     string     `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	Avatar    *string    `thrift:"avatar,5,optional" frugal:"5,optional,string" json:"avatar,omitempty"`
	Bio       *string    `thrift:"bio,6,optional" frugal:"6,optional,string" json:"bio,omitempty"`
	Gender    *int32     `thrift:"gender,7,optional" frugal:"7,optional,i32" json:"gender,omitempty"`
	CreatedAt int64      `thrift:"createdAt,8" frugal:"8,default,i64" json:"createdAt"`
	UpdatedAt int64      `thrift:"updatedAt,9" frugal:"9,default,i64" json:"updatedAt"`
	Status    UserStatus `thrift:"status,10" frugal:"10,default,UserStatus" json:"status"`
	LastLogin *int64     `thrift:"lastLogin,11,optional" frugal:"11,optional,i64" json:"lastLogin,omitempty"`
}

func NewSafeUser() *SafeUser {
	return &SafeUser{}
}

func (p *SafeUser) InitDefault() {
}

func (p *SafeUser) GetId() (v int64) {
	return p.Id
}

func (p *SafeUser) GetName() (v string) {
	return p.Name
}

func (p *SafeUser) GetEmail() (v string) {
	return p.Email
}

func (p *SafeUser) GetPhone() (v string) {
	return p.Phone
}

var SafeUser_Avatar_DEFAULT string

func (p *SafeUser) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return SafeUser_Avatar_DEFAULT
	}
	return *p.Avatar
}

var SafeUser_Bio_DEFAULT string

func (p *SafeUser) GetBio() (v string) {
	if !p.IsSetBio() {
		return SafeUser_Bio_DEFAULT
	}
	return *p.Bio
}

var SafeUser_Gender_DEFAULT int32

func (p *SafeUser) GetGender() (v int32) {
	if !p.IsSetGender() {
		return SafeUser_Gender_DEFAULT
	}
	return *p.Gender
}

func (p *SafeUser) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *SafeUser) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

func (p *SafeUser) GetStatus() (v UserStatus) {
	return p.Status
}

var SafeUser_LastLogin_DEFAULT int64

func (p *SafeUser) GetLastLogin() (v int64) {
	if !p.IsSetLastLogin() {
		return SafeUser_LastLogin_DEFAULT
	}
	return *p.LastLogin
}
func (p *SafeUser) SetId(val int64) {
	p.Id = val
}
func (p *SafeUser) SetName(val string) {
	p.Name = val
}
func (p *SafeUser) SetEmail(val string) {
	p.Email = val
}
func (p *SafeUser) SetPhone(val string) {
	p.Phone = val
}
func (p *SafeUser) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *SafeUser) SetBio(val *string) {
	p.Bio = val
}
func (p *SafeUser) SetGender(val *int32) {
	p.Gender = val
}
func (p *SafeUser) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *SafeUser) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *SafeUser) SetStatus(val UserStatus) {
	p.Status = val
}
func (p *SafeUser) SetLastLogin(val *int64) {
	p.LastLogin = val
}

func (p *SafeUser) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *SafeUser) IsSetBio() bool {
	return p.Bio != nil
}

func (p *SafeUser) IsSetGender() bool {
	return p.Gender != nil
}

func (p *SafeUser) IsSetLastLogin() bool {
	return p.LastLogin != nil
}

func (p *SafeUser) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SafeUser(%+v)", *p)
}

var fieldIDToName_SafeUser = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "email",
	4:  "phone",
	5:  "avatar",
	6:  "bio",
	7:  "gender",
	8:  "createdAt",
	9:  "updatedAt",
	10: "status",
	11: "lastLogin",
}

type RegisterReq struct {
	Name     string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Email    string `thrift:"email,2" frugal:"2,default,string" json:"email"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
	Phone    string `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
}

func NewRegisterReq() *RegisterReq {
	return &RegisterReq{}
}

func (p *RegisterReq) InitDefault() {
}

func (p *RegisterReq) GetName() (v string) {
	return p.Name
}

func (p *RegisterReq) GetEmail() (v string) {
	return p.Email
}

func (p *RegisterReq) GetPassword() (v string) {
	return p.Password
}

func (p *RegisterReq) GetPhone() (v string) {
	return p.Phone
}
func (p *RegisterReq) SetName(val string) {
	p.Name = val
}
func (p *RegisterReq) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterReq) SetPassword(val string) {
	p.Password = val
}
func (p *RegisterReq) SetPhone(val string) {
	p.Phone = val
}

func (p *RegisterReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterReq(%+v)", *p)
}

var fieldIDToName_RegisterReq = map[int16]string{
	1: "name",
	2: "email",
	3: "password",
	4: "phone",
}

type LoginReq struct {
	Phone    string  `thrift:"phone,1" frugal:"1,default,string" json:"phone"`
	Password string  `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Email    *string `thrift:"email,3,optional" frugal:"3,optional,string" json:"email,omitempty"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

func (p *LoginReq) GetPhone() (v string) {
	return p.Phone
}

func (p *LoginReq) GetPassword() (v string) {
	return p.Password
}

var LoginReq_Email_DEFAULT string

func (p *LoginReq) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return LoginReq_Email_DEFAULT
	}
	return *p.Email
}
func (p *LoginReq) SetPhone(val string) {
	p.Phone = val
}
func (p *LoginReq) SetPassword(val string) {
	p.Password = val
}
func (p *LoginReq) SetEmail(val *string) {
	p.Email = val
}

func (p *LoginReq) IsSetEmail() bool {
	return p.Email != nil
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "phone",
	2: "password",
	3: "email",
}

type UpdateUserReq struct {
	Name   *string `thrift:"name,1,optional" frugal:"1,optional,string" json:"name,omitempty"`
	Avatar *string `thrift:"avatar,2,optional" frugal:"2,optional,string" json:"avatar,omitempty"`
	Bio    *string `thrift:"bio,3,optional" frugal:"3,optional,string" json:"bio,omitempty"`
	Gender *int32  `thrift:"gender,4,optional" frugal:"4,optional,i32" json:"gender,omitempty"`
}

func NewUpdateUserReq() *UpdateUserReq {
	return &UpdateUserReq{}
}

func (p *UpdateUserReq) InitDefault() {
}

var UpdateUserReq_Name_DEFAULT string

func (p *UpdateUserReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateUserReq_Name_DEFAULT
	}
	return *p.Name
}

var UpdateUserReq_Avatar_DEFAULT string

func (p *UpdateUserReq) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return UpdateUserReq_Avatar_DEFAULT
	}
	return *p.Avatar
}

var UpdateUserReq_Bio_DEFAULT string

func (p *UpdateUserReq) GetBio() (v string) {
	if !p.IsSetBio() {
		return UpdateUserReq_Bio_DEFAULT
	}
	return *p.Bio
}

var UpdateUserReq_Gender_DEFAULT int32

func (p *UpdateUserReq) GetGender() (v int32) {
	if !p.IsSetGender() {
		return UpdateUserReq_Gender_DEFAULT
	}
	return *p.Gender
}
func (p *UpdateUserReq) SetName(val *string) {
	p.Name = val
}
func (p *UpdateUserReq) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *UpdateUserReq) SetBio(val *string) {
	p.Bio = val
}
func (p *UpdateUserReq) SetGender(val *int32) {
	p.Gender = val
}

func (p *UpdateUserReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateUserReq) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *UpdateUserReq) IsSetBio() bool {
	return p.Bio != nil
}

func (p *UpdateUserReq) IsSetGender() bool {
	return p.Gender != nil
}

func (p *UpdateUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserReq(%+v)", *p)
}

var fieldIDToName_UpdateUserReq = map[int16]string{
	1: "name",
	2: "avatar",
	3: "bio",
	4: "gender",
}

type ChangePasswordReq struct {
	OldPassword  string `thrift:"oldPassword,1" frugal:"1,default,string" json:"oldPassword"`
	NewPassword_ string `thrift:"newPassword,2" frugal:"2,default,string" json:"newPassword"`
}

func NewChangePasswordReq() *ChangePasswordReq {
	return &ChangePasswordReq{}
}

func (p *ChangePasswordReq) InitDefault() {
}

func (p *ChangePasswordReq) GetOldPassword() (v string) {
	return p.OldPassword
}

func (p *ChangePasswordReq) GetNewPassword_() (v string) {
	return p.NewPassword_
}
func (p *ChangePasswordReq) SetOldPassword(val string) {
	p.OldPassword = val
}
func (p *ChangePasswordReq) SetNewPassword_(val string) {
	p.NewPassword_ = val
}

func (p *ChangePasswordReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangePasswordReq(%+v)", *p)
}

var fieldIDToName_ChangePasswordReq = map[int16]string{
	1: "oldPassword",
	2: "newPassword",
}

type ChangeEmailReq struct {
	NewEmail_ string `thrift:"newEmail,1" frugal:"1,default,string" json:"newEmail"`
	Password  string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Code      string `thrift:"code,3" frugal:"3,default,string" json:"code"`
}

func NewChangeEmailReq() *ChangeEmailReq {
	return &ChangeEmailReq{}
}

func (p *ChangeEmailReq) InitDefault() {
}

func (p *ChangeEmailReq) GetNewEmail_() (v string) {
	return p.NewEmail_
}

func (p *ChangeEmailReq) GetPassword() (v string) {
	return p.Password
}

func (p *ChangeEmailReq) GetCode() (v string) {
	return p.Code
}
func (p *ChangeEmailReq) SetNewEmail_(val string) {
	p.NewEmail_ = val
}
func (p *ChangeEmailReq) SetPassword(val string) {
	p.Password = val
}
func (p *ChangeEmailReq) SetCode(val string) {
	p.Code = val
}

func (p *ChangeEmailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangeEmailReq(%+v)", *p)
}

var fieldIDToName_ChangeEmailReq = map[int16]string{
	1: "newEmail",
	2: "password",
	3: "code",
}

type ChangePhoneReq struct {
	NewPhone_ string `thrift:"newPhone,1" frugal:"1,default,string" json:"newPhone"`
	Password  string `thrift:"password,2" frugal:"2,default,string" json:"password"`
	Code      string `thrift:"code,3" frugal:"3,default,string" json:"code"`
}

func NewChangePhoneReq() *ChangePhoneReq {
	return &ChangePhoneReq{}
}

func (p *ChangePhoneReq) InitDefault() {
}

func (p *ChangePhoneReq) GetNewPhone_() (v string) {
	return p.NewPhone_
}

func (p *ChangePhoneReq) GetPassword() (v string) {
	return p.Password
}

func (p *ChangePhoneReq) GetCode() (v string) {
	return p.Code
}
func (p *ChangePhoneReq) SetNewPhone_(val string) {
	p.NewPhone_ = val
}
func (p *ChangePhoneReq) SetPassword(val string) {
	p.Password = val
}
func (p *ChangePhoneReq) SetCode(val string) {
	p.Code = val
}

func (p *ChangePhoneReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChangePhoneReq(%+v)", *p)
}

var fieldIDToName_ChangePhoneReq = map[int16]string{
	1: "newPhone",
	2: "password",
	3: "code",
}

type RegisterResp struct {
	Id      int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Token   string  `thrift:"token,2" frugal:"2,default,string" json:"token"`
	Success bool    `thrift:"success,3" frugal:"3,default,bool" json:"success"`
	Message *string `thrift:"message,4,optional" frugal:"4,optional,string" json:"message,omitempty"`
	Code    int32   `thrift:"code,5" frugal:"5,default,i32" json:"code"`
}

func NewRegisterResp() *RegisterResp {
	return &RegisterResp{
		Code: 0,
	}
}

func (p *RegisterResp) InitDefault() {
	p.Code = 0
}

func (p *RegisterResp) GetId() (v int64) {
	return p.Id
}

func (p *RegisterResp) GetToken() (v string) {
	return p.Token
}

func (p *RegisterResp) GetSuccess() (v bool) {
	return p.Success
}

var RegisterResp_Message_DEFAULT string

func (p *RegisterResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return RegisterResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *RegisterResp) GetCode() (v int32) {
	return p.Code
}
func (p *RegisterResp) SetId(val int64) {
	p.Id = val
}
func (p *RegisterResp) SetToken(val string) {
	p.Token = val
}
func (p *RegisterResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *RegisterResp) SetMessage(val *string) {
	p.Message = val
}
func (p *RegisterResp) SetCode(val int32) {
	p.Code = val
}

func (p *RegisterResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *RegisterResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResp(%+v)", *p)
}

var fieldIDToName_RegisterResp = map[int16]string{
	1: "id",
	2: "token",
	3: "success",
	4: "message",
	5: "code",
}

type LoginResp struct {
	Id      int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Token   string  `thrift:"token,2" frugal:"2,default,string" json:"token"`
	Success bool    `thrift:"success,3" frugal:"3,default,bool" json:"success"`
	Message *string `thrift:"message,4,optional" frugal:"4,optional,string" json:"message,omitempty"`
	Code    int32   `thrift:"code,5" frugal:"5,default,i32" json:"code"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{
		Code: 0,
	}
}

func (p *LoginResp) InitDefault() {
	p.Code = 0
}

func (p *LoginResp) GetId() (v int64) {
	return p.Id
}

func (p *LoginResp) GetToken() (v string) {
	return p.Token
}

func (p *LoginResp) GetSuccess() (v bool) {
	return p.Success
}

var LoginResp_Message_DEFAULT string

func (p *LoginResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return LoginResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *LoginResp) GetCode() (v int32) {
	return p.Code
}
func (p *LoginResp) SetId(val int64) {
	p.Id = val
}
func (p *LoginResp) SetToken(val string) {
	p.Token = val
}
func (p *LoginResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *LoginResp) SetMessage(val *string) {
	p.Message = val
}
func (p *LoginResp) SetCode(val int32) {
	p.Code = val
}

func (p *LoginResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "id",
	2: "token",
	3: "success",
	4: "message",
	5: "code",
}

type UpdateUserResp struct {
	Message *string `thrift:"message,1,optional" frugal:"1,optional,string" json:"message,omitempty"`
	Success bool    `thrift:"success,2" frugal:"2,default,bool" json:"success"`
	Code    int32   `thrift:"code,3" frugal:"3,default,i32" json:"code"`
}

func NewUpdateUserResp() *UpdateUserResp {
	return &UpdateUserResp{
		Code: 0,
	}
}

func (p *UpdateUserResp) InitDefault() {
	p.Code = 0
}

var UpdateUserResp_Message_DEFAULT string

func (p *UpdateUserResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return UpdateUserResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *UpdateUserResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateUserResp) GetCode() (v int32) {
	return p.Code
}
func (p *UpdateUserResp) SetMessage(val *string) {
	p.Message = val
}
func (p *UpdateUserResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateUserResp) SetCode(val int32) {
	p.Code = val
}

func (p *UpdateUserResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *UpdateUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateUserResp(%+v)", *p)
}

var fieldIDToName_UpdateUserResp = map[int16]string{
	1: "message",
	2: "success",
	3: "code",
}

type GetUserProfileReq struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewGetUserProfileReq() *GetUserProfileReq {
	return &GetUserProfileReq{}
}

func (p *GetUserProfileReq) InitDefault() {
}

func (p *GetUserProfileReq) GetId() (v int64) {
	return p.Id
}
func (p *GetUserProfileReq) SetId(val int64) {
	p.Id = val
}

func (p *GetUserProfileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserProfileReq(%+v)", *p)
}

var fieldIDToName_GetUserProfileReq = map[int16]string{
	1: "id",
}

type GetUserProfileResp struct {
	Success bool      `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32     `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string   `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	User    *SafeUser `thrift:"user,4,optional" frugal:"4,optional,SafeUser" json:"user,omitempty"`
}

func NewGetUserProfileResp() *GetUserProfileResp {
	return &GetUserProfileResp{
		Code: 0,
	}
}

func (p *GetUserProfileResp) InitDefault() {
	p.Code = 0
}

func (p *GetUserProfileResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetUserProfileResp) GetCode() (v int32) {
	return p.Code
}

var GetUserProfileResp_Message_DEFAULT string

func (p *GetUserProfileResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return GetUserProfileResp_Message_DEFAULT
	}
	return *p.Message
}

var GetUserProfileResp_User_DEFAULT *SafeUser

func (p *GetUserProfileResp) GetUser() (v *SafeUser) {
	if !p.IsSetUser() {
		return GetUserProfileResp_User_DEFAULT
	}
	return p.User
}
func (p *GetUserProfileResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetUserProfileResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetUserProfileResp) SetMessage(val *string) {
	p.Message = val
}
func (p *GetUserProfileResp) SetUser(val *SafeUser) {
	p.User = val
}

func (p *GetUserProfileResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *GetUserProfileResp) IsSetUser() bool {
	return p.User != nil
}

func (p *GetUserProfileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserProfileResp(%+v)", *p)
}

var fieldIDToName_GetUserProfileResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "user",
}

type LogoutReq struct {
}

func NewLogoutReq() *LogoutReq {
	return &LogoutReq{}
}

func (p *LogoutReq) InitDefault() {
}

func (p *LogoutReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutReq(%+v)", *p)
}

var fieldIDToName_LogoutReq = map[int16]string{}

type LogoutResp struct {
	Success bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32   `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
}

func NewLogoutResp() *LogoutResp {
	return &LogoutResp{
		Code: 0,
	}
}

func (p *LogoutResp) InitDefault() {
	p.Code = 0
}

func (p *LogoutResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *LogoutResp) GetCode() (v int32) {
	return p.Code
}

var LogoutResp_Message_DEFAULT string

func (p *LogoutResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return LogoutResp_Message_DEFAULT
	}
	return *p.Message
}
func (p *LogoutResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *LogoutResp) SetCode(val int32) {
	p.Code = val
}
func (p *LogoutResp) SetMessage(val *string) {
	p.Message = val
}

func (p *LogoutResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *LogoutResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutResp(%+v)", *p)
}

var fieldIDToName_LogoutResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterReq) (r *RegisterResp, err error)

	Login(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	UpdateUser(ctx context.Context, req *UpdateUserReq) (r *UpdateUserResp, err error)

	ChangePassword(ctx context.Context, req *ChangePasswordReq) (r *UpdateUserResp, err error)

	ChangeEmail(ctx context.Context, req *ChangeEmailReq) (r *UpdateUserResp, err error)

	ChangePhone(ctx context.Context, req *ChangePhoneReq) (r *UpdateUserResp, err error)

	GetUserProfile(ctx context.Context, req *GetUserProfileReq) (r *GetUserProfileResp, err error)

	Logout(ctx context.Context, req *LogoutReq) (r *LogoutResp, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterReq `thrift:"req,1" frugal:"1,default,RegisterReq" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterReq

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterReq) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterReq) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResp `thrift:"success,0,optional" frugal:"0,optional,RegisterResp" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResp

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResp) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResp)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginReq

func (p *UserServiceLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResp

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateUserArgs struct {
	Req *UpdateUserReq `thrift:"req,1" frugal:"1,default,UpdateUserReq" json:"req"`
}

func NewUserServiceUpdateUserArgs() *UserServiceUpdateUserArgs {
	return &UserServiceUpdateUserArgs{}
}

func (p *UserServiceUpdateUserArgs) InitDefault() {
}

var UserServiceUpdateUserArgs_Req_DEFAULT *UpdateUserReq

func (p *UserServiceUpdateUserArgs) GetReq() (v *UpdateUserReq) {
	if !p.IsSetReq() {
		return UserServiceUpdateUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateUserArgs) SetReq(val *UpdateUserReq) {
	p.Req = val
}

func (p *UserServiceUpdateUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateUserResult struct {
	Success *UpdateUserResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResp" json:"success,omitempty"`
}

func NewUserServiceUpdateUserResult() *UserServiceUpdateUserResult {
	return &UserServiceUpdateUserResult{}
}

func (p *UserServiceUpdateUserResult) InitDefault() {
}

var UserServiceUpdateUserResult_Success_DEFAULT *UpdateUserResp

func (p *UserServiceUpdateUserResult) GetSuccess() (v *UpdateUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResp)
}

func (p *UserServiceUpdateUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateUserResult = map[int16]string{
	0: "success",
}

type UserServiceChangePasswordArgs struct {
	Req *ChangePasswordReq `thrift:"req,1" frugal:"1,default,ChangePasswordReq" json:"req"`
}

func NewUserServiceChangePasswordArgs() *UserServiceChangePasswordArgs {
	return &UserServiceChangePasswordArgs{}
}

func (p *UserServiceChangePasswordArgs) InitDefault() {
}

var UserServiceChangePasswordArgs_Req_DEFAULT *ChangePasswordReq

func (p *UserServiceChangePasswordArgs) GetReq() (v *ChangePasswordReq) {
	if !p.IsSetReq() {
		return UserServiceChangePasswordArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceChangePasswordArgs) SetReq(val *ChangePasswordReq) {
	p.Req = val
}

func (p *UserServiceChangePasswordArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceChangePasswordArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangePasswordArgs(%+v)", *p)
}

var fieldIDToName_UserServiceChangePasswordArgs = map[int16]string{
	1: "req",
}

type UserServiceChangePasswordResult struct {
	Success *UpdateUserResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResp" json:"success,omitempty"`
}

func NewUserServiceChangePasswordResult() *UserServiceChangePasswordResult {
	return &UserServiceChangePasswordResult{}
}

func (p *UserServiceChangePasswordResult) InitDefault() {
}

var UserServiceChangePasswordResult_Success_DEFAULT *UpdateUserResp

func (p *UserServiceChangePasswordResult) GetSuccess() (v *UpdateUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceChangePasswordResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceChangePasswordResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResp)
}

func (p *UserServiceChangePasswordResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceChangePasswordResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangePasswordResult(%+v)", *p)
}

var fieldIDToName_UserServiceChangePasswordResult = map[int16]string{
	0: "success",
}

type UserServiceChangeEmailArgs struct {
	Req *ChangeEmailReq `thrift:"req,1" frugal:"1,default,ChangeEmailReq" json:"req"`
}

func NewUserServiceChangeEmailArgs() *UserServiceChangeEmailArgs {
	return &UserServiceChangeEmailArgs{}
}

func (p *UserServiceChangeEmailArgs) InitDefault() {
}

var UserServiceChangeEmailArgs_Req_DEFAULT *ChangeEmailReq

func (p *UserServiceChangeEmailArgs) GetReq() (v *ChangeEmailReq) {
	if !p.IsSetReq() {
		return UserServiceChangeEmailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceChangeEmailArgs) SetReq(val *ChangeEmailReq) {
	p.Req = val
}

func (p *UserServiceChangeEmailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceChangeEmailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangeEmailArgs(%+v)", *p)
}

var fieldIDToName_UserServiceChangeEmailArgs = map[int16]string{
	1: "req",
}

type UserServiceChangeEmailResult struct {
	Success *UpdateUserResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResp" json:"success,omitempty"`
}

func NewUserServiceChangeEmailResult() *UserServiceChangeEmailResult {
	return &UserServiceChangeEmailResult{}
}

func (p *UserServiceChangeEmailResult) InitDefault() {
}

var UserServiceChangeEmailResult_Success_DEFAULT *UpdateUserResp

func (p *UserServiceChangeEmailResult) GetSuccess() (v *UpdateUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceChangeEmailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceChangeEmailResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResp)
}

func (p *UserServiceChangeEmailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceChangeEmailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangeEmailResult(%+v)", *p)
}

var fieldIDToName_UserServiceChangeEmailResult = map[int16]string{
	0: "success",
}

type UserServiceChangePhoneArgs struct {
	Req *ChangePhoneReq `thrift:"req,1" frugal:"1,default,ChangePhoneReq" json:"req"`
}

func NewUserServiceChangePhoneArgs() *UserServiceChangePhoneArgs {
	return &UserServiceChangePhoneArgs{}
}

func (p *UserServiceChangePhoneArgs) InitDefault() {
}

var UserServiceChangePhoneArgs_Req_DEFAULT *ChangePhoneReq

func (p *UserServiceChangePhoneArgs) GetReq() (v *ChangePhoneReq) {
	if !p.IsSetReq() {
		return UserServiceChangePhoneArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceChangePhoneArgs) SetReq(val *ChangePhoneReq) {
	p.Req = val
}

func (p *UserServiceChangePhoneArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceChangePhoneArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangePhoneArgs(%+v)", *p)
}

var fieldIDToName_UserServiceChangePhoneArgs = map[int16]string{
	1: "req",
}

type UserServiceChangePhoneResult struct {
	Success *UpdateUserResp `thrift:"success,0,optional" frugal:"0,optional,UpdateUserResp" json:"success,omitempty"`
}

func NewUserServiceChangePhoneResult() *UserServiceChangePhoneResult {
	return &UserServiceChangePhoneResult{}
}

func (p *UserServiceChangePhoneResult) InitDefault() {
}

var UserServiceChangePhoneResult_Success_DEFAULT *UpdateUserResp

func (p *UserServiceChangePhoneResult) GetSuccess() (v *UpdateUserResp) {
	if !p.IsSetSuccess() {
		return UserServiceChangePhoneResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceChangePhoneResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateUserResp)
}

func (p *UserServiceChangePhoneResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceChangePhoneResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceChangePhoneResult(%+v)", *p)
}

var fieldIDToName_UserServiceChangePhoneResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserProfileArgs struct {
	Req *GetUserProfileReq `thrift:"req,1" frugal:"1,default,GetUserProfileReq" json:"req"`
}

func NewUserServiceGetUserProfileArgs() *UserServiceGetUserProfileArgs {
	return &UserServiceGetUserProfileArgs{}
}

func (p *UserServiceGetUserProfileArgs) InitDefault() {
}

var UserServiceGetUserProfileArgs_Req_DEFAULT *GetUserProfileReq

func (p *UserServiceGetUserProfileArgs) GetReq() (v *GetUserProfileReq) {
	if !p.IsSetReq() {
		return UserServiceGetUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserProfileArgs) SetReq(val *GetUserProfileReq) {
	p.Req = val
}

func (p *UserServiceGetUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserProfileArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserProfileArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserProfileResult struct {
	Success *GetUserProfileResp `thrift:"success,0,optional" frugal:"0,optional,GetUserProfileResp" json:"success,omitempty"`
}

func NewUserServiceGetUserProfileResult() *UserServiceGetUserProfileResult {
	return &UserServiceGetUserProfileResult{}
}

func (p *UserServiceGetUserProfileResult) InitDefault() {
}

var UserServiceGetUserProfileResult_Success_DEFAULT *GetUserProfileResp

func (p *UserServiceGetUserProfileResult) GetSuccess() (v *GetUserProfileResp) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserProfileResp)
}

func (p *UserServiceGetUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserProfileResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserProfileResult = map[int16]string{
	0: "success",
}

type UserServiceLogoutArgs struct {
	Req *LogoutReq `thrift:"req,1" frugal:"1,default,LogoutReq" json:"req"`
}

func NewUserServiceLogoutArgs() *UserServiceLogoutArgs {
	return &UserServiceLogoutArgs{}
}

func (p *UserServiceLogoutArgs) InitDefault() {
}

var UserServiceLogoutArgs_Req_DEFAULT *LogoutReq

func (p *UserServiceLogoutArgs) GetReq() (v *LogoutReq) {
	if !p.IsSetReq() {
		return UserServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLogoutArgs) SetReq(val *LogoutReq) {
	p.Req = val
}

func (p *UserServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutArgs = map[int16]string{
	1: "req",
}

type UserServiceLogoutResult struct {
	Success *LogoutResp `thrift:"success,0,optional" frugal:"0,optional,LogoutResp" json:"success,omitempty"`
}

func NewUserServiceLogoutResult() *UserServiceLogoutResult {
	return &UserServiceLogoutResult{}
}

func (p *UserServiceLogoutResult) InitDefault() {
}

var UserServiceLogoutResult_Success_DEFAULT *LogoutResp

func (p *UserServiceLogoutResult) GetSuccess() (v *LogoutResp) {
	if !p.IsSetSuccess() {
		return UserServiceLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*LogoutResp)
}

func (p *UserServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_UserServiceLogoutResult = map[int16]string{
	0: "success",
}
