// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	api "ecommerce/user-service/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *api.RegisterReq, callOptions ...callopt.Option) (r *api.RegisterResp, err error)
	Login(ctx context.Context, req *api.LoginReq, callOptions ...callopt.Option) (r *api.LoginResp, err error)
	UpdateUser(ctx context.Context, req *api.UpdateUserReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	ChangePassword(ctx context.Context, req *api.ChangePasswordReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	ChangeEmail(ctx context.Context, req *api.ChangeEmailReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	ChangePhone(ctx context.Context, req *api.ChangePhoneReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	GetUserProfile(ctx context.Context, req *api.GetUserProfileReq, callOptions ...callopt.Option) (r *api.GetUserProfileResp, err error)
	Logout(ctx context.Context, req *api.LogoutReq, callOptions ...callopt.Option) (r *api.LogoutResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *api.RegisterReq, callOptions ...callopt.Option) (r *api.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *api.LoginReq, callOptions ...callopt.Option) (r *api.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) UpdateUser(ctx context.Context, req *api.UpdateUserReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, req)
}

func (p *kUserServiceClient) ChangePassword(ctx context.Context, req *api.ChangePasswordReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, req)
}

func (p *kUserServiceClient) ChangeEmail(ctx context.Context, req *api.ChangeEmailReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeEmail(ctx, req)
}

func (p *kUserServiceClient) ChangePhone(ctx context.Context, req *api.ChangePhoneReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePhone(ctx, req)
}

func (p *kUserServiceClient) GetUserProfile(ctx context.Context, req *api.GetUserProfileReq, callOptions ...callopt.Option) (r *api.GetUserProfileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserProfile(ctx, req)
}

func (p *kUserServiceClient) Logout(ctx context.Context, req *api.LogoutReq, callOptions ...callopt.Option) (r *api.LogoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}
