// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	api "ecommerce/user-service/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *api.RegisterReq, callOptions ...callopt.Option) (r *api.RegisterResp, err error)
	Login(ctx context.Context, req *api.LoginReq, callOptions ...callopt.Option) (r *api.LoginResp, err error)
	UpdateUser(ctx context.Context, req *api.UpdateUserReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	ChangePassword(ctx context.Context, req *api.ChangePasswordReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	ChangeEmail(ctx context.Context, req *api.ChangeEmailReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	ChangePhone(ctx context.Context, req *api.ChangePhoneReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error)
	GetUserProfile(ctx context.Context, req *api.GetUserProfileReq, callOptions ...callopt.Option) (r *api.GetUserProfileResp, err error)
	Logout(ctx context.Context, req *api.LogoutReq, callOptions ...callopt.Option) (r *api.LogoutResp, err error)
	GetUserStatus(ctx context.Context, req *api.GetUserStatusReq, callOptions ...callopt.Option) (r *api.GetUserStatusResp, err error)
	BanUser(ctx context.Context, req *api.BanUserReq, callOptions ...callopt.Option) (r *api.BanUserResp, err error)
	UnbanUser(ctx context.Context, req *api.UnbanUserReq, callOptions ...callopt.Option) (r *api.UnbanUserResp, err error)
	DeleteUser(ctx context.Context, req *api.DeleteUserReq, callOptions ...callopt.Option) (r *api.DeleteUserResp, err error)
	RestoreUser(ctx context.Context, req *api.RestoreUserReq, callOptions ...callopt.Option) (r *api.RestoreUserResp, err error)
	UpdateUserStatus(ctx context.Context, req *api.UpdateUserStatusReq, callOptions ...callopt.Option) (r *api.UpdateUserStatusResp, err error)
	ListUsers(ctx context.Context, req *api.ListUsersReq, callOptions ...callopt.Option) (r *api.ListUsersResp, err error)
	SearchUsers(ctx context.Context, req *api.SearchUsersReq, callOptions ...callopt.Option) (r *api.SearchUsersResp, err error)
	CountUsers(ctx context.Context, req *api.CountUsersReq, callOptions ...callopt.Option) (r *api.CountUsersResp, err error)
	CountByStatus(ctx context.Context, req *api.CountByStatusReq, callOptions ...callopt.Option) (r *api.CountByStatusResp, err error)
	AdminUpdatePassword(ctx context.Context, req *api.UpdatePasswordReq, callOptions ...callopt.Option) (r *api.UpdatePasswordResp, err error)
	AdminUpdateEmail(ctx context.Context, req *api.UpdateEmailReq, callOptions ...callopt.Option) (r *api.UpdateEmailResp, err error)
	AdminUpdatePhone(ctx context.Context, req *api.UpdatePhoneReq, callOptions ...callopt.Option) (r *api.UpdatePhoneResp, err error)
	AdminUpdateUserProfile(ctx context.Context, req *api.UpdateUserProfileReq, callOptions ...callopt.Option) (r *api.UpdateUserProfileResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *api.RegisterReq, callOptions ...callopt.Option) (r *api.RegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *api.LoginReq, callOptions ...callopt.Option) (r *api.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) UpdateUser(ctx context.Context, req *api.UpdateUserReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, req)
}

func (p *kUserServiceClient) ChangePassword(ctx context.Context, req *api.ChangePasswordReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePassword(ctx, req)
}

func (p *kUserServiceClient) ChangeEmail(ctx context.Context, req *api.ChangeEmailReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangeEmail(ctx, req)
}

func (p *kUserServiceClient) ChangePhone(ctx context.Context, req *api.ChangePhoneReq, callOptions ...callopt.Option) (r *api.UpdateUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChangePhone(ctx, req)
}

func (p *kUserServiceClient) GetUserProfile(ctx context.Context, req *api.GetUserProfileReq, callOptions ...callopt.Option) (r *api.GetUserProfileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserProfile(ctx, req)
}

func (p *kUserServiceClient) Logout(ctx context.Context, req *api.LogoutReq, callOptions ...callopt.Option) (r *api.LogoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}

func (p *kUserServiceClient) GetUserStatus(ctx context.Context, req *api.GetUserStatusReq, callOptions ...callopt.Option) (r *api.GetUserStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserStatus(ctx, req)
}

func (p *kUserServiceClient) BanUser(ctx context.Context, req *api.BanUserReq, callOptions ...callopt.Option) (r *api.BanUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BanUser(ctx, req)
}

func (p *kUserServiceClient) UnbanUser(ctx context.Context, req *api.UnbanUserReq, callOptions ...callopt.Option) (r *api.UnbanUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnbanUser(ctx, req)
}

func (p *kUserServiceClient) DeleteUser(ctx context.Context, req *api.DeleteUserReq, callOptions ...callopt.Option) (r *api.DeleteUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteUser(ctx, req)
}

func (p *kUserServiceClient) RestoreUser(ctx context.Context, req *api.RestoreUserReq, callOptions ...callopt.Option) (r *api.RestoreUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RestoreUser(ctx, req)
}

func (p *kUserServiceClient) UpdateUserStatus(ctx context.Context, req *api.UpdateUserStatusReq, callOptions ...callopt.Option) (r *api.UpdateUserStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUserStatus(ctx, req)
}

func (p *kUserServiceClient) ListUsers(ctx context.Context, req *api.ListUsersReq, callOptions ...callopt.Option) (r *api.ListUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListUsers(ctx, req)
}

func (p *kUserServiceClient) SearchUsers(ctx context.Context, req *api.SearchUsersReq, callOptions ...callopt.Option) (r *api.SearchUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchUsers(ctx, req)
}

func (p *kUserServiceClient) CountUsers(ctx context.Context, req *api.CountUsersReq, callOptions ...callopt.Option) (r *api.CountUsersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountUsers(ctx, req)
}

func (p *kUserServiceClient) CountByStatus(ctx context.Context, req *api.CountByStatusReq, callOptions ...callopt.Option) (r *api.CountByStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CountByStatus(ctx, req)
}

func (p *kUserServiceClient) AdminUpdatePassword(ctx context.Context, req *api.UpdatePasswordReq, callOptions ...callopt.Option) (r *api.UpdatePasswordResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminUpdatePassword(ctx, req)
}

func (p *kUserServiceClient) AdminUpdateEmail(ctx context.Context, req *api.UpdateEmailReq, callOptions ...callopt.Option) (r *api.UpdateEmailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminUpdateEmail(ctx, req)
}

func (p *kUserServiceClient) AdminUpdatePhone(ctx context.Context, req *api.UpdatePhoneReq, callOptions ...callopt.Option) (r *api.UpdatePhoneResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminUpdatePhone(ctx, req)
}

func (p *kUserServiceClient) AdminUpdateUserProfile(ctx context.Context, req *api.UpdateUserProfileReq, callOptions ...callopt.Option) (r *api.UpdateUserProfileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminUpdateUserProfile(ctx, req)
}
