// Code generated by Kitex v0.15.2. DO NOT EDIT.

package userservice

import (
	"context"
	api "ecommerce/user-service/kitex_gen/api"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateUser": kitex.NewMethodInfo(
		updateUserHandler,
		newUserServiceUpdateUserArgs,
		newUserServiceUpdateUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangePassword": kitex.NewMethodInfo(
		changePasswordHandler,
		newUserServiceChangePasswordArgs,
		newUserServiceChangePasswordResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangeEmail": kitex.NewMethodInfo(
		changeEmailHandler,
		newUserServiceChangeEmailArgs,
		newUserServiceChangeEmailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChangePhone": kitex.NewMethodInfo(
		changePhoneHandler,
		newUserServiceChangePhoneArgs,
		newUserServiceChangePhoneResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserProfile": kitex.NewMethodInfo(
		getUserProfileHandler,
		newUserServiceGetUserProfileArgs,
		newUserServiceGetUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newUserServiceLogoutArgs,
		newUserServiceLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*api.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceRegisterArgs)
	realResult := result.(*api.UserServiceRegisterResult)
	success, err := handler.(api.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return api.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return api.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceLoginArgs)
	realResult := result.(*api.UserServiceLoginResult)
	success, err := handler.(api.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return api.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return api.NewUserServiceLoginResult()
}

func updateUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceUpdateUserArgs)
	realResult := result.(*api.UserServiceUpdateUserResult)
	success, err := handler.(api.UserService).UpdateUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateUserArgs() interface{} {
	return api.NewUserServiceUpdateUserArgs()
}

func newUserServiceUpdateUserResult() interface{} {
	return api.NewUserServiceUpdateUserResult()
}

func changePasswordHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceChangePasswordArgs)
	realResult := result.(*api.UserServiceChangePasswordResult)
	success, err := handler.(api.UserService).ChangePassword(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceChangePasswordArgs() interface{} {
	return api.NewUserServiceChangePasswordArgs()
}

func newUserServiceChangePasswordResult() interface{} {
	return api.NewUserServiceChangePasswordResult()
}

func changeEmailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceChangeEmailArgs)
	realResult := result.(*api.UserServiceChangeEmailResult)
	success, err := handler.(api.UserService).ChangeEmail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceChangeEmailArgs() interface{} {
	return api.NewUserServiceChangeEmailArgs()
}

func newUserServiceChangeEmailResult() interface{} {
	return api.NewUserServiceChangeEmailResult()
}

func changePhoneHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceChangePhoneArgs)
	realResult := result.(*api.UserServiceChangePhoneResult)
	success, err := handler.(api.UserService).ChangePhone(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceChangePhoneArgs() interface{} {
	return api.NewUserServiceChangePhoneArgs()
}

func newUserServiceChangePhoneResult() interface{} {
	return api.NewUserServiceChangePhoneResult()
}

func getUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceGetUserProfileArgs)
	realResult := result.(*api.UserServiceGetUserProfileResult)
	success, err := handler.(api.UserService).GetUserProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetUserProfileArgs() interface{} {
	return api.NewUserServiceGetUserProfileArgs()
}

func newUserServiceGetUserProfileResult() interface{} {
	return api.NewUserServiceGetUserProfileResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.UserServiceLogoutArgs)
	realResult := result.(*api.UserServiceLogoutResult)
	success, err := handler.(api.UserService).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLogoutArgs() interface{} {
	return api.NewUserServiceLogoutArgs()
}

func newUserServiceLogoutResult() interface{} {
	return api.NewUserServiceLogoutResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *api.RegisterReq) (r *api.RegisterResp, err error) {
	var _args api.UserServiceRegisterArgs
	_args.Req = req
	var _result api.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *api.LoginReq) (r *api.LoginResp, err error) {
	var _args api.UserServiceLoginArgs
	_args.Req = req
	var _result api.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateUser(ctx context.Context, req *api.UpdateUserReq) (r *api.UpdateUserResp, err error) {
	var _args api.UserServiceUpdateUserArgs
	_args.Req = req
	var _result api.UserServiceUpdateUserResult
	if err = p.c.Call(ctx, "UpdateUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePassword(ctx context.Context, req *api.ChangePasswordReq) (r *api.UpdateUserResp, err error) {
	var _args api.UserServiceChangePasswordArgs
	_args.Req = req
	var _result api.UserServiceChangePasswordResult
	if err = p.c.Call(ctx, "ChangePassword", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangeEmail(ctx context.Context, req *api.ChangeEmailReq) (r *api.UpdateUserResp, err error) {
	var _args api.UserServiceChangeEmailArgs
	_args.Req = req
	var _result api.UserServiceChangeEmailResult
	if err = p.c.Call(ctx, "ChangeEmail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChangePhone(ctx context.Context, req *api.ChangePhoneReq) (r *api.UpdateUserResp, err error) {
	var _args api.UserServiceChangePhoneArgs
	_args.Req = req
	var _result api.UserServiceChangePhoneResult
	if err = p.c.Call(ctx, "ChangePhone", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserProfile(ctx context.Context, req *api.GetUserProfileReq) (r *api.GetUserProfileResp, err error) {
	var _args api.UserServiceGetUserProfileArgs
	_args.Req = req
	var _result api.UserServiceGetUserProfileResult
	if err = p.c.Call(ctx, "GetUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *api.LogoutReq) (r *api.LogoutResp, err error) {
	var _args api.UserServiceLogoutArgs
	_args.Req = req
	var _result api.UserServiceLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
