// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type OrderStatus int64

const (
	OrderStatus_PENDING   OrderStatus = 0
	OrderStatus_PAID      OrderStatus = 1
	OrderStatus_SHIPPED   OrderStatus = 2
	OrderStatus_COMPLETED OrderStatus = 3
	OrderStatus_CANCELLED OrderStatus = 4
	OrderStatus_REFUNDED  OrderStatus = 5
)

func (p OrderStatus) String() string {
	switch p {
	case OrderStatus_PENDING:
		return "PENDING"
	case OrderStatus_PAID:
		return "PAID"
	case OrderStatus_SHIPPED:
		return "SHIPPED"
	case OrderStatus_COMPLETED:
		return "COMPLETED"
	case OrderStatus_CANCELLED:
		return "CANCELLED"
	case OrderStatus_REFUNDED:
		return "REFUNDED"
	}
	return "<UNSET>"
}

func OrderStatusFromString(s string) (OrderStatus, error) {
	switch s {
	case "PENDING":
		return OrderStatus_PENDING, nil
	case "PAID":
		return OrderStatus_PAID, nil
	case "SHIPPED":
		return OrderStatus_SHIPPED, nil
	case "COMPLETED":
		return OrderStatus_COMPLETED, nil
	case "CANCELLED":
		return OrderStatus_CANCELLED, nil
	case "REFUNDED":
		return OrderStatus_REFUNDED, nil
	}
	return OrderStatus(0), fmt.Errorf("not a valid OrderStatus string")
}

func OrderStatusPtr(v OrderStatus) *OrderStatus { return &v }
func (p *OrderStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OrderStatus(result.Int64)
	return
}

func (p *OrderStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type RefundStatus int64

const (
	RefundStatus_PENDING    RefundStatus = 0
	RefundStatus_APPROVED   RefundStatus = 1
	RefundStatus_REJECTED   RefundStatus = 2
	RefundStatus_PROCESSING RefundStatus = 3
	RefundStatus_COMPLETED  RefundStatus = 4
)

func (p RefundStatus) String() string {
	switch p {
	case RefundStatus_PENDING:
		return "PENDING"
	case RefundStatus_APPROVED:
		return "APPROVED"
	case RefundStatus_REJECTED:
		return "REJECTED"
	case RefundStatus_PROCESSING:
		return "PROCESSING"
	case RefundStatus_COMPLETED:
		return "COMPLETED"
	}
	return "<UNSET>"
}

func RefundStatusFromString(s string) (RefundStatus, error) {
	switch s {
	case "PENDING":
		return RefundStatus_PENDING, nil
	case "APPROVED":
		return RefundStatus_APPROVED, nil
	case "REJECTED":
		return RefundStatus_REJECTED, nil
	case "PROCESSING":
		return RefundStatus_PROCESSING, nil
	case "COMPLETED":
		return RefundStatus_COMPLETED, nil
	}
	return RefundStatus(0), fmt.Errorf("not a valid RefundStatus string")
}

func RefundStatusPtr(v RefundStatus) *RefundStatus { return &v }
func (p *RefundStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = RefundStatus(result.Int64)
	return
}

func (p *RefundStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TimeoutType int64

const (
	TimeoutType_ORDER_UNPAID      TimeoutType = 0
	TimeoutType_STOCK_RESERVATION TimeoutType = 1
)

func (p TimeoutType) String() string {
	switch p {
	case TimeoutType_ORDER_UNPAID:
		return "ORDER_UNPAID"
	case TimeoutType_STOCK_RESERVATION:
		return "STOCK_RESERVATION"
	}
	return "<UNSET>"
}

func TimeoutTypeFromString(s string) (TimeoutType, error) {
	switch s {
	case "ORDER_UNPAID":
		return TimeoutType_ORDER_UNPAID, nil
	case "STOCK_RESERVATION":
		return TimeoutType_STOCK_RESERVATION, nil
	}
	return TimeoutType(0), fmt.Errorf("not a valid TimeoutType string")
}

func TimeoutTypePtr(v TimeoutType) *TimeoutType { return &v }
func (p *TimeoutType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = TimeoutType(result.Int64)
	return
}

func (p *TimeoutType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OrderItem struct {
	ProductId    int64   `thrift:"productId,1" frugal:"1,default,i64" json:"productId"`
	ProductName  string  `thrift:"productName,2" frugal:"2,default,string" json:"productName"`
	Quantity     int32   `thrift:"quantity,3" frugal:"3,default,i32" json:"quantity"`
	Price        float64 `thrift:"price,4" frugal:"4,default,double" json:"price"`
	ProductImage *string `thrift:"productImage,5,optional" frugal:"5,optional,string" json:"productImage,omitempty"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItem) GetProductName() (v string) {
	return p.ProductName
}

func (p *OrderItem) GetQuantity() (v int32) {
	return p.Quantity
}

func (p *OrderItem) GetPrice() (v float64) {
	return p.Price
}

var OrderItem_ProductImage_DEFAULT string

func (p *OrderItem) GetProductImage() (v string) {
	if !p.IsSetProductImage() {
		return OrderItem_ProductImage_DEFAULT
	}
	return *p.ProductImage
}
func (p *OrderItem) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItem) SetProductName(val string) {
	p.ProductName = val
}
func (p *OrderItem) SetQuantity(val int32) {
	p.Quantity = val
}
func (p *OrderItem) SetPrice(val float64) {
	p.Price = val
}
func (p *OrderItem) SetProductImage(val *string) {
	p.ProductImage = val
}

func (p *OrderItem) IsSetProductImage() bool {
	return p.ProductImage != nil
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1: "productId",
	2: "productName",
	3: "quantity",
	4: "price",
	5: "productImage",
}

type Order struct {
	Id          int64        `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	OrderNo     string       `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	UserId      int64        `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	TotalAmount float64      `thrift:"totalAmount,4" frugal:"4,default,double" json:"totalAmount"`
	Status      OrderStatus  `thrift:"status,5" frugal:"5,default,OrderStatus" json:"status"`
	Items       []*OrderItem `thrift:"items,6" frugal:"6,default,list<OrderItem>" json:"items"`
	Address     string       `thrift:"address,7" frugal:"7,default,string" json:"address"`
	Phone       string       `thrift:"phone,8" frugal:"8,default,string" json:"phone"`
	CreatedAt   int64        `thrift:"createdAt,9" frugal:"9,default,i64" json:"createdAt"`
	UpdatedAt   int64        `thrift:"updatedAt,10" frugal:"10,default,i64" json:"updatedAt"`
	Receiver    *string      `thrift:"receiver,11,optional" frugal:"11,optional,string" json:"receiver,omitempty"`
	PaymentNo   *string      `thrift:"paymentNo,12,optional" frugal:"12,optional,string" json:"paymentNo,omitempty"`
	ShippingNo  *string      `thrift:"shippingNo,13,optional" frugal:"13,optional,string" json:"shippingNo,omitempty"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetId() (v int64) {
	return p.Id
}

func (p *Order) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *Order) GetUserId() (v int64) {
	return p.UserId
}

func (p *Order) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

func (p *Order) GetStatus() (v OrderStatus) {
	return p.Status
}

func (p *Order) GetItems() (v []*OrderItem) {
	return p.Items
}

func (p *Order) GetAddress() (v string) {
	return p.Address
}

func (p *Order) GetPhone() (v string) {
	return p.Phone
}

func (p *Order) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *Order) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

var Order_Receiver_DEFAULT string

func (p *Order) GetReceiver() (v string) {
	if !p.IsSetReceiver() {
		return Order_Receiver_DEFAULT
	}
	return *p.Receiver
}

var Order_PaymentNo_DEFAULT string

func (p *Order) GetPaymentNo() (v string) {
	if !p.IsSetPaymentNo() {
		return Order_PaymentNo_DEFAULT
	}
	return *p.PaymentNo
}

var Order_ShippingNo_DEFAULT string

func (p *Order) GetShippingNo() (v string) {
	if !p.IsSetShippingNo() {
		return Order_ShippingNo_DEFAULT
	}
	return *p.ShippingNo
}
func (p *Order) SetId(val int64) {
	p.Id = val
}
func (p *Order) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *Order) SetUserId(val int64) {
	p.UserId = val
}
func (p *Order) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *Order) SetStatus(val OrderStatus) {
	p.Status = val
}
func (p *Order) SetItems(val []*OrderItem) {
	p.Items = val
}
func (p *Order) SetAddress(val string) {
	p.Address = val
}
func (p *Order) SetPhone(val string) {
	p.Phone = val
}
func (p *Order) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *Order) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *Order) SetReceiver(val *string) {
	p.Receiver = val
}
func (p *Order) SetPaymentNo(val *string) {
	p.PaymentNo = val
}
func (p *Order) SetShippingNo(val *string) {
	p.ShippingNo = val
}

func (p *Order) IsSetReceiver() bool {
	return p.Receiver != nil
}

func (p *Order) IsSetPaymentNo() bool {
	return p.PaymentNo != nil
}

func (p *Order) IsSetShippingNo() bool {
	return p.ShippingNo != nil
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1:  "id",
	2:  "orderNo",
	3:  "userId",
	4:  "totalAmount",
	5:  "status",
	6:  "items",
	7:  "address",
	8:  "phone",
	9:  "createdAt",
	10: "updatedAt",
	11: "receiver",
	12: "paymentNo",
	13: "shippingNo",
}

type StockReservation struct {
	ReserveId  string `thrift:"reserveId,1" frugal:"1,default,string" json:"reserveId"`
	OrderNo    string `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	ProductId  int64  `thrift:"productId,3" frugal:"3,default,i64" json:"productId"`
	Quantity   int32  `thrift:"quantity,4" frugal:"4,default,i32" json:"quantity"`
	Status     string `thrift:"status,5" frugal:"5,default,string" json:"status"`
	ExpireTime int64  `thrift:"expireTime,6" frugal:"6,default,i64" json:"expireTime"`
	CreatedAt  int64  `thrift:"createdAt,7" frugal:"7,default,i64" json:"createdAt"`
	UpdatedAt  int64  `thrift:"updatedAt,8" frugal:"8,default,i64" json:"updatedAt"`
}

func NewStockReservation() *StockReservation {
	return &StockReservation{}
}

func (p *StockReservation) InitDefault() {
}

func (p *StockReservation) GetReserveId() (v string) {
	return p.ReserveId
}

func (p *StockReservation) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *StockReservation) GetProductId() (v int64) {
	return p.ProductId
}

func (p *StockReservation) GetQuantity() (v int32) {
	return p.Quantity
}

func (p *StockReservation) GetStatus() (v string) {
	return p.Status
}

func (p *StockReservation) GetExpireTime() (v int64) {
	return p.ExpireTime
}

func (p *StockReservation) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *StockReservation) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *StockReservation) SetReserveId(val string) {
	p.ReserveId = val
}
func (p *StockReservation) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *StockReservation) SetProductId(val int64) {
	p.ProductId = val
}
func (p *StockReservation) SetQuantity(val int32) {
	p.Quantity = val
}
func (p *StockReservation) SetStatus(val string) {
	p.Status = val
}
func (p *StockReservation) SetExpireTime(val int64) {
	p.ExpireTime = val
}
func (p *StockReservation) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *StockReservation) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *StockReservation) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StockReservation(%+v)", *p)
}

var fieldIDToName_StockReservation = map[int16]string{
	1: "reserveId",
	2: "orderNo",
	3: "productId",
	4: "quantity",
	5: "status",
	6: "expireTime",
	7: "createdAt",
	8: "updatedAt",
}

type RefundOrder struct {
	RefundNo    string       `thrift:"refundNo,1" frugal:"1,default,string" json:"refundNo"`
	OrderNo     string       `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	UserId      int64        `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	Amount      float64      `thrift:"amount,4" frugal:"4,default,double" json:"amount"`
	Status      RefundStatus `thrift:"status,5" frugal:"5,default,RefundStatus" json:"status"`
	Reason      string       `thrift:"reason,6" frugal:"6,default,string" json:"reason"`
	CreatedAt   int64        `thrift:"createdAt,7" frugal:"7,default,i64" json:"createdAt"`
	UpdatedAt   int64        `thrift:"updatedAt,8" frugal:"8,default,i64" json:"updatedAt"`
	Processor   *string      `thrift:"processor,9,optional" frugal:"9,optional,string" json:"processor,omitempty"`
	ProcessedAt *int64       `thrift:"processedAt,10,optional" frugal:"10,optional,i64" json:"processedAt,omitempty"`
}

func NewRefundOrder() *RefundOrder {
	return &RefundOrder{}
}

func (p *RefundOrder) InitDefault() {
}

func (p *RefundOrder) GetRefundNo() (v string) {
	return p.RefundNo
}

func (p *RefundOrder) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *RefundOrder) GetUserId() (v int64) {
	return p.UserId
}

func (p *RefundOrder) GetAmount() (v float64) {
	return p.Amount
}

func (p *RefundOrder) GetStatus() (v RefundStatus) {
	return p.Status
}

func (p *RefundOrder) GetReason() (v string) {
	return p.Reason
}

func (p *RefundOrder) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *RefundOrder) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

var RefundOrder_Processor_DEFAULT string

func (p *RefundOrder) GetProcessor() (v string) {
	if !p.IsSetProcessor() {
		return RefundOrder_Processor_DEFAULT
	}
	return *p.Processor
}

var RefundOrder_ProcessedAt_DEFAULT int64

func (p *RefundOrder) GetProcessedAt() (v int64) {
	if !p.IsSetProcessedAt() {
		return RefundOrder_ProcessedAt_DEFAULT
	}
	return *p.ProcessedAt
}
func (p *RefundOrder) SetRefundNo(val string) {
	p.RefundNo = val
}
func (p *RefundOrder) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *RefundOrder) SetUserId(val int64) {
	p.UserId = val
}
func (p *RefundOrder) SetAmount(val float64) {
	p.Amount = val
}
func (p *RefundOrder) SetStatus(val RefundStatus) {
	p.Status = val
}
func (p *RefundOrder) SetReason(val string) {
	p.Reason = val
}
func (p *RefundOrder) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *RefundOrder) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *RefundOrder) SetProcessor(val *string) {
	p.Processor = val
}
func (p *RefundOrder) SetProcessedAt(val *int64) {
	p.ProcessedAt = val
}

func (p *RefundOrder) IsSetProcessor() bool {
	return p.Processor != nil
}

func (p *RefundOrder) IsSetProcessedAt() bool {
	return p.ProcessedAt != nil
}

func (p *RefundOrder) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefundOrder(%+v)", *p)
}

var fieldIDToName_RefundOrder = map[int16]string{
	1:  "refundNo",
	2:  "orderNo",
	3:  "userId",
	4:  "amount",
	5:  "status",
	6:  "reason",
	7:  "createdAt",
	8:  "updatedAt",
	9:  "processor",
	10: "processedAt",
}

type TimeoutTask struct {
	TaskId     string      `thrift:"taskId,1" frugal:"1,default,string" json:"taskId"`
	OrderNo    string      `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	Type       TimeoutType `thrift:"type,3" frugal:"3,default,TimeoutType" json:"type"`
	Status     string      `thrift:"status,4" frugal:"4,default,string" json:"status"`
	ExpireTime int64       `thrift:"expireTime,5" frugal:"5,default,i64" json:"expireTime"`
	RetryCount int32       `thrift:"retryCount,6" frugal:"6,default,i32" json:"retryCount"`
	CreatedAt  int64       `thrift:"createdAt,7" frugal:"7,default,i64" json:"createdAt"`
	UpdatedAt  int64       `thrift:"updatedAt,8" frugal:"8,default,i64" json:"updatedAt"`
}

func NewTimeoutTask() *TimeoutTask {
	return &TimeoutTask{}
}

func (p *TimeoutTask) InitDefault() {
}

func (p *TimeoutTask) GetTaskId() (v string) {
	return p.TaskId
}

func (p *TimeoutTask) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *TimeoutTask) GetType() (v TimeoutType) {
	return p.Type
}

func (p *TimeoutTask) GetStatus() (v string) {
	return p.Status
}

func (p *TimeoutTask) GetExpireTime() (v int64) {
	return p.ExpireTime
}

func (p *TimeoutTask) GetRetryCount() (v int32) {
	return p.RetryCount
}

func (p *TimeoutTask) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *TimeoutTask) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}
func (p *TimeoutTask) SetTaskId(val string) {
	p.TaskId = val
}
func (p *TimeoutTask) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *TimeoutTask) SetType(val TimeoutType) {
	p.Type = val
}
func (p *TimeoutTask) SetStatus(val string) {
	p.Status = val
}
func (p *TimeoutTask) SetExpireTime(val int64) {
	p.ExpireTime = val
}
func (p *TimeoutTask) SetRetryCount(val int32) {
	p.RetryCount = val
}
func (p *TimeoutTask) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *TimeoutTask) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}

func (p *TimeoutTask) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TimeoutTask(%+v)", *p)
}

var fieldIDToName_TimeoutTask = map[int16]string{
	1: "taskId",
	2: "orderNo",
	3: "type",
	4: "status",
	5: "expireTime",
	6: "retryCount",
	7: "createdAt",
	8: "updatedAt",
}

type CreateOrderReq struct {
	UserId        int64        `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Items         []*OrderItem `thrift:"items,2" frugal:"2,default,list<OrderItem>" json:"items"`
	Address       string       `thrift:"address,3" frugal:"3,default,string" json:"address"`
	Phone         string       `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	Receiver      *string      `thrift:"receiver,5,optional" frugal:"5,optional,string" json:"receiver,omitempty"`
	PaymentMethod *string      `thrift:"paymentMethod,6,optional" frugal:"6,optional,string" json:"paymentMethod,omitempty"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateOrderReq) GetItems() (v []*OrderItem) {
	return p.Items
}

func (p *CreateOrderReq) GetAddress() (v string) {
	return p.Address
}

func (p *CreateOrderReq) GetPhone() (v string) {
	return p.Phone
}

var CreateOrderReq_Receiver_DEFAULT string

func (p *CreateOrderReq) GetReceiver() (v string) {
	if !p.IsSetReceiver() {
		return CreateOrderReq_Receiver_DEFAULT
	}
	return *p.Receiver
}

var CreateOrderReq_PaymentMethod_DEFAULT string

func (p *CreateOrderReq) GetPaymentMethod() (v string) {
	if !p.IsSetPaymentMethod() {
		return CreateOrderReq_PaymentMethod_DEFAULT
	}
	return *p.PaymentMethod
}
func (p *CreateOrderReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateOrderReq) SetItems(val []*OrderItem) {
	p.Items = val
}
func (p *CreateOrderReq) SetAddress(val string) {
	p.Address = val
}
func (p *CreateOrderReq) SetPhone(val string) {
	p.Phone = val
}
func (p *CreateOrderReq) SetReceiver(val *string) {
	p.Receiver = val
}
func (p *CreateOrderReq) SetPaymentMethod(val *string) {
	p.PaymentMethod = val
}

func (p *CreateOrderReq) IsSetReceiver() bool {
	return p.Receiver != nil
}

func (p *CreateOrderReq) IsSetPaymentMethod() bool {
	return p.PaymentMethod != nil
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "userId",
	2: "items",
	3: "address",
	4: "phone",
	5: "receiver",
	6: "paymentMethod",
}

type CreateOrderResp struct {
	Success     bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code        int32   `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message     string  `thrift:"message,3" frugal:"3,default,string" json:"message"`
	OrderNo     string  `thrift:"orderNo,4" frugal:"4,default,string" json:"orderNo"`
	TotalAmount float64 `thrift:"totalAmount,5" frugal:"5,default,double" json:"totalAmount"`
	PaymentUrl  *string `thrift:"paymentUrl,6,optional" frugal:"6,optional,string" json:"paymentUrl,omitempty"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{
		Code: 0,
	}
}

func (p *CreateOrderResp) InitDefault() {
	p.Code = 0
}

func (p *CreateOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreateOrderResp) GetCode() (v int32) {
	return p.Code
}

func (p *CreateOrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *CreateOrderResp) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *CreateOrderResp) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

var CreateOrderResp_PaymentUrl_DEFAULT string

func (p *CreateOrderResp) GetPaymentUrl() (v string) {
	if !p.IsSetPaymentUrl() {
		return CreateOrderResp_PaymentUrl_DEFAULT
	}
	return *p.PaymentUrl
}
func (p *CreateOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreateOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *CreateOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *CreateOrderResp) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *CreateOrderResp) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *CreateOrderResp) SetPaymentUrl(val *string) {
	p.PaymentUrl = val
}

func (p *CreateOrderResp) IsSetPaymentUrl() bool {
	return p.PaymentUrl != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "orderNo",
	5: "totalAmount",
	6: "paymentUrl",
}

type GetOrderReq struct {
	OrderNo string `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId  *int64 `thrift:"userId,2,optional" frugal:"2,optional,i64" json:"userId,omitempty"`
}

func NewGetOrderReq() *GetOrderReq {
	return &GetOrderReq{}
}

func (p *GetOrderReq) InitDefault() {
}

func (p *GetOrderReq) GetOrderNo() (v string) {
	return p.OrderNo
}

var GetOrderReq_UserId_DEFAULT int64

func (p *GetOrderReq) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return GetOrderReq_UserId_DEFAULT
	}
	return *p.UserId
}
func (p *GetOrderReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *GetOrderReq) SetUserId(val *int64) {
	p.UserId = val
}

func (p *GetOrderReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *GetOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderReq(%+v)", *p)
}

var fieldIDToName_GetOrderReq = map[int16]string{
	1: "orderNo",
	2: "userId",
}

type GetOrderResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
	Order   *Order `thrift:"order,4" frugal:"4,default,Order" json:"order"`
}

func NewGetOrderResp() *GetOrderResp {
	return &GetOrderResp{
		Code: 0,
	}
}

func (p *GetOrderResp) InitDefault() {
	p.Code = 0
}

func (p *GetOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetOrderResp) GetCode() (v int32) {
	return p.Code
}

func (p *GetOrderResp) GetMessage() (v string) {
	return p.Message
}

var GetOrderResp_Order_DEFAULT *Order

func (p *GetOrderResp) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return GetOrderResp_Order_DEFAULT
	}
	return p.Order
}
func (p *GetOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *GetOrderResp) SetOrder(val *Order) {
	p.Order = val
}

func (p *GetOrderResp) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderResp(%+v)", *p)
}

var fieldIDToName_GetOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "order",
}

type ListOrdersReq struct {
	UserId    int64        `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Status    *OrderStatus `thrift:"status,2,optional" frugal:"2,optional,OrderStatus" json:"status,omitempty"`
	Page      int32        `thrift:"page,3" frugal:"3,default,i32" json:"page"`
	PageSize  int32        `thrift:"pageSize,4" frugal:"4,default,i32" json:"pageSize"`
	StartTime *int64       `thrift:"startTime,5,optional" frugal:"5,optional,i64" json:"startTime,omitempty"`
	EndTime   *int64       `thrift:"endTime,6,optional" frugal:"6,optional,i64" json:"endTime,omitempty"`
}

func NewListOrdersReq() *ListOrdersReq {
	return &ListOrdersReq{
		Page:     1,
		PageSize: 10,
	}
}

func (p *ListOrdersReq) InitDefault() {
	p.Page = 1
	p.PageSize = 10
}

func (p *ListOrdersReq) GetUserId() (v int64) {
	return p.UserId
}

var ListOrdersReq_Status_DEFAULT OrderStatus

func (p *ListOrdersReq) GetStatus() (v OrderStatus) {
	if !p.IsSetStatus() {
		return ListOrdersReq_Status_DEFAULT
	}
	return *p.Status
}

func (p *ListOrdersReq) GetPage() (v int32) {
	return p.Page
}

func (p *ListOrdersReq) GetPageSize() (v int32) {
	return p.PageSize
}

var ListOrdersReq_StartTime_DEFAULT int64

func (p *ListOrdersReq) GetStartTime() (v int64) {
	if !p.IsSetStartTime() {
		return ListOrdersReq_StartTime_DEFAULT
	}
	return *p.StartTime
}

var ListOrdersReq_EndTime_DEFAULT int64

func (p *ListOrdersReq) GetEndTime() (v int64) {
	if !p.IsSetEndTime() {
		return ListOrdersReq_EndTime_DEFAULT
	}
	return *p.EndTime
}
func (p *ListOrdersReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListOrdersReq) SetStatus(val *OrderStatus) {
	p.Status = val
}
func (p *ListOrdersReq) SetPage(val int32) {
	p.Page = val
}
func (p *ListOrdersReq) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListOrdersReq) SetStartTime(val *int64) {
	p.StartTime = val
}
func (p *ListOrdersReq) SetEndTime(val *int64) {
	p.EndTime = val
}

func (p *ListOrdersReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *ListOrdersReq) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *ListOrdersReq) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *ListOrdersReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersReq(%+v)", *p)
}

var fieldIDToName_ListOrdersReq = map[int16]string{
	1: "userId",
	2: "status",
	3: "page",
	4: "pageSize",
	5: "startTime",
	6: "endTime",
}

type ListOrdersResp struct {
	Success  bool     `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code     int32    `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message  string   `thrift:"message,3" frugal:"3,default,string" json:"message"`
	Total    int32    `thrift:"total,4" frugal:"4,default,i32" json:"total"`
	Page     int32    `thrift:"page,5" frugal:"5,default,i32" json:"page"`
	PageSize int32    `thrift:"pageSize,6" frugal:"6,default,i32" json:"pageSize"`
	Orders   []*Order `thrift:"orders,7" frugal:"7,default,list<Order>" json:"orders"`
}

func NewListOrdersResp() *ListOrdersResp {
	return &ListOrdersResp{
		Code: 0,
	}
}

func (p *ListOrdersResp) InitDefault() {
	p.Code = 0
}

func (p *ListOrdersResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ListOrdersResp) GetCode() (v int32) {
	return p.Code
}

func (p *ListOrdersResp) GetMessage() (v string) {
	return p.Message
}

func (p *ListOrdersResp) GetTotal() (v int32) {
	return p.Total
}

func (p *ListOrdersResp) GetPage() (v int32) {
	return p.Page
}

func (p *ListOrdersResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *ListOrdersResp) GetOrders() (v []*Order) {
	return p.Orders
}
func (p *ListOrdersResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ListOrdersResp) SetCode(val int32) {
	p.Code = val
}
func (p *ListOrdersResp) SetMessage(val string) {
	p.Message = val
}
func (p *ListOrdersResp) SetTotal(val int32) {
	p.Total = val
}
func (p *ListOrdersResp) SetPage(val int32) {
	p.Page = val
}
func (p *ListOrdersResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *ListOrdersResp) SetOrders(val []*Order) {
	p.Orders = val
}

func (p *ListOrdersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListOrdersResp(%+v)", *p)
}

var fieldIDToName_ListOrdersResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "total",
	5: "page",
	6: "pageSize",
	7: "orders",
}

type PayOrderReq struct {
	OrderNo   string  `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId    int64   `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	PaymentNo *string `thrift:"paymentNo,3,optional" frugal:"3,optional,string" json:"paymentNo,omitempty"`
}

func NewPayOrderReq() *PayOrderReq {
	return &PayOrderReq{}
}

func (p *PayOrderReq) InitDefault() {
}

func (p *PayOrderReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *PayOrderReq) GetUserId() (v int64) {
	return p.UserId
}

var PayOrderReq_PaymentNo_DEFAULT string

func (p *PayOrderReq) GetPaymentNo() (v string) {
	if !p.IsSetPaymentNo() {
		return PayOrderReq_PaymentNo_DEFAULT
	}
	return *p.PaymentNo
}
func (p *PayOrderReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *PayOrderReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *PayOrderReq) SetPaymentNo(val *string) {
	p.PaymentNo = val
}

func (p *PayOrderReq) IsSetPaymentNo() bool {
	return p.PaymentNo != nil
}

func (p *PayOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *p)
}

var fieldIDToName_PayOrderReq = map[int16]string{
	1: "orderNo",
	2: "userId",
	3: "paymentNo",
}

type PayOrderResp struct {
	Success    bool        `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32       `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    string      `thrift:"message,3" frugal:"3,default,string" json:"message"`
	NewStatus_ OrderStatus `thrift:"newStatus,4" frugal:"4,default,OrderStatus" json:"newStatus"`
	PaidAt     *int64      `thrift:"paidAt,5,optional" frugal:"5,optional,i64" json:"paidAt,omitempty"`
}

func NewPayOrderResp() *PayOrderResp {
	return &PayOrderResp{
		Code: 0,
	}
}

func (p *PayOrderResp) InitDefault() {
	p.Code = 0
}

func (p *PayOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *PayOrderResp) GetCode() (v int32) {
	return p.Code
}

func (p *PayOrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *PayOrderResp) GetNewStatus_() (v OrderStatus) {
	return p.NewStatus_
}

var PayOrderResp_PaidAt_DEFAULT int64

func (p *PayOrderResp) GetPaidAt() (v int64) {
	if !p.IsSetPaidAt() {
		return PayOrderResp_PaidAt_DEFAULT
	}
	return *p.PaidAt
}
func (p *PayOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *PayOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *PayOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *PayOrderResp) SetNewStatus_(val OrderStatus) {
	p.NewStatus_ = val
}
func (p *PayOrderResp) SetPaidAt(val *int64) {
	p.PaidAt = val
}

func (p *PayOrderResp) IsSetPaidAt() bool {
	return p.PaidAt != nil
}

func (p *PayOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderResp(%+v)", *p)
}

var fieldIDToName_PayOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "newStatus",
	5: "paidAt",
}

type CancelOrderReq struct {
	OrderNo string `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId  int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Reason  string `thrift:"reason,3" frugal:"3,default,string" json:"reason"`
}

func NewCancelOrderReq() *CancelOrderReq {
	return &CancelOrderReq{}
}

func (p *CancelOrderReq) InitDefault() {
}

func (p *CancelOrderReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *CancelOrderReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CancelOrderReq) GetReason() (v string) {
	return p.Reason
}
func (p *CancelOrderReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *CancelOrderReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CancelOrderReq) SetReason(val string) {
	p.Reason = val
}

func (p *CancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderReq(%+v)", *p)
}

var fieldIDToName_CancelOrderReq = map[int16]string{
	1: "orderNo",
	2: "userId",
	3: "reason",
}

type CancelOrderResp struct {
	Success     bool        `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code        int32       `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message     string      `thrift:"message,3" frugal:"3,default,string" json:"message"`
	NewStatus_  OrderStatus `thrift:"newStatus,4" frugal:"4,default,OrderStatus" json:"newStatus"`
	CancelledAt *int64      `thrift:"cancelledAt,5,optional" frugal:"5,optional,i64" json:"cancelledAt,omitempty"`
}

func NewCancelOrderResp() *CancelOrderResp {
	return &CancelOrderResp{
		Code: 0,
	}
}

func (p *CancelOrderResp) InitDefault() {
	p.Code = 0
}

func (p *CancelOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CancelOrderResp) GetCode() (v int32) {
	return p.Code
}

func (p *CancelOrderResp) GetMessage() (v string) {
	return p.Message
}

func (p *CancelOrderResp) GetNewStatus_() (v OrderStatus) {
	return p.NewStatus_
}

var CancelOrderResp_CancelledAt_DEFAULT int64

func (p *CancelOrderResp) GetCancelledAt() (v int64) {
	if !p.IsSetCancelledAt() {
		return CancelOrderResp_CancelledAt_DEFAULT
	}
	return *p.CancelledAt
}
func (p *CancelOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CancelOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *CancelOrderResp) SetMessage(val string) {
	p.Message = val
}
func (p *CancelOrderResp) SetNewStatus_(val OrderStatus) {
	p.NewStatus_ = val
}
func (p *CancelOrderResp) SetCancelledAt(val *int64) {
	p.CancelledAt = val
}

func (p *CancelOrderResp) IsSetCancelledAt() bool {
	return p.CancelledAt != nil
}

func (p *CancelOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderResp(%+v)", *p)
}

var fieldIDToName_CancelOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "newStatus",
	5: "cancelledAt",
}

type ApplyRefundReq struct {
	OrderNo string   `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId  int64    `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Reason  string   `thrift:"reason,3" frugal:"3,default,string" json:"reason"`
	Amount  *float64 `thrift:"amount,4,optional" frugal:"4,optional,double" json:"amount,omitempty"`
}

func NewApplyRefundReq() *ApplyRefundReq {
	return &ApplyRefundReq{}
}

func (p *ApplyRefundReq) InitDefault() {
}

func (p *ApplyRefundReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *ApplyRefundReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *ApplyRefundReq) GetReason() (v string) {
	return p.Reason
}

var ApplyRefundReq_Amount_DEFAULT float64

func (p *ApplyRefundReq) GetAmount() (v float64) {
	if !p.IsSetAmount() {
		return ApplyRefundReq_Amount_DEFAULT
	}
	return *p.Amount
}
func (p *ApplyRefundReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *ApplyRefundReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *ApplyRefundReq) SetReason(val string) {
	p.Reason = val
}
func (p *ApplyRefundReq) SetAmount(val *float64) {
	p.Amount = val
}

func (p *ApplyRefundReq) IsSetAmount() bool {
	return p.Amount != nil
}

func (p *ApplyRefundReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApplyRefundReq(%+v)", *p)
}

var fieldIDToName_ApplyRefundReq = map[int16]string{
	1: "orderNo",
	2: "userId",
	3: "reason",
	4: "amount",
}

type ApplyRefundResp struct {
	Success  bool         `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code     int32        `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message  string       `thrift:"message,3" frugal:"3,default,string" json:"message"`
	RefundNo string       `thrift:"refundNo,4" frugal:"4,default,string" json:"refundNo"`
	Status   RefundStatus `thrift:"status,5" frugal:"5,default,RefundStatus" json:"status"`
}

func NewApplyRefundResp() *ApplyRefundResp {
	return &ApplyRefundResp{
		Code: 0,
	}
}

func (p *ApplyRefundResp) InitDefault() {
	p.Code = 0
}

func (p *ApplyRefundResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ApplyRefundResp) GetCode() (v int32) {
	return p.Code
}

func (p *ApplyRefundResp) GetMessage() (v string) {
	return p.Message
}

func (p *ApplyRefundResp) GetRefundNo() (v string) {
	return p.RefundNo
}

func (p *ApplyRefundResp) GetStatus() (v RefundStatus) {
	return p.Status
}
func (p *ApplyRefundResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ApplyRefundResp) SetCode(val int32) {
	p.Code = val
}
func (p *ApplyRefundResp) SetMessage(val string) {
	p.Message = val
}
func (p *ApplyRefundResp) SetRefundNo(val string) {
	p.RefundNo = val
}
func (p *ApplyRefundResp) SetStatus(val RefundStatus) {
	p.Status = val
}

func (p *ApplyRefundResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ApplyRefundResp(%+v)", *p)
}

var fieldIDToName_ApplyRefundResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "refundNo",
	5: "status",
}

type ProcessRefundReq struct {
	RefundNo    string       `thrift:"refundNo,1" frugal:"1,default,string" json:"refundNo"`
	ProcessorId int64        `thrift:"processorId,2" frugal:"2,default,i64" json:"processorId"`
	Action      RefundStatus `thrift:"action,3" frugal:"3,default,RefundStatus" json:"action"`
	Remark      *string      `thrift:"remark,4,optional" frugal:"4,optional,string" json:"remark,omitempty"`
}

func NewProcessRefundReq() *ProcessRefundReq {
	return &ProcessRefundReq{}
}

func (p *ProcessRefundReq) InitDefault() {
}

func (p *ProcessRefundReq) GetRefundNo() (v string) {
	return p.RefundNo
}

func (p *ProcessRefundReq) GetProcessorId() (v int64) {
	return p.ProcessorId
}

func (p *ProcessRefundReq) GetAction() (v RefundStatus) {
	return p.Action
}

var ProcessRefundReq_Remark_DEFAULT string

func (p *ProcessRefundReq) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return ProcessRefundReq_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *ProcessRefundReq) SetRefundNo(val string) {
	p.RefundNo = val
}
func (p *ProcessRefundReq) SetProcessorId(val int64) {
	p.ProcessorId = val
}
func (p *ProcessRefundReq) SetAction(val RefundStatus) {
	p.Action = val
}
func (p *ProcessRefundReq) SetRemark(val *string) {
	p.Remark = val
}

func (p *ProcessRefundReq) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *ProcessRefundReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProcessRefundReq(%+v)", *p)
}

var fieldIDToName_ProcessRefundReq = map[int16]string{
	1: "refundNo",
	2: "processorId",
	3: "action",
	4: "remark",
}

type ProcessRefundResp struct {
	Success    bool         `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32        `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    string       `thrift:"message,3" frugal:"3,default,string" json:"message"`
	NewStatus_ RefundStatus `thrift:"newStatus,4" frugal:"4,default,RefundStatus" json:"newStatus"`
}

func NewProcessRefundResp() *ProcessRefundResp {
	return &ProcessRefundResp{
		Code: 0,
	}
}

func (p *ProcessRefundResp) InitDefault() {
	p.Code = 0
}

func (p *ProcessRefundResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ProcessRefundResp) GetCode() (v int32) {
	return p.Code
}

func (p *ProcessRefundResp) GetMessage() (v string) {
	return p.Message
}

func (p *ProcessRefundResp) GetNewStatus_() (v RefundStatus) {
	return p.NewStatus_
}
func (p *ProcessRefundResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ProcessRefundResp) SetCode(val int32) {
	p.Code = val
}
func (p *ProcessRefundResp) SetMessage(val string) {
	p.Message = val
}
func (p *ProcessRefundResp) SetNewStatus_(val RefundStatus) {
	p.NewStatus_ = val
}

func (p *ProcessRefundResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProcessRefundResp(%+v)", *p)
}

var fieldIDToName_ProcessRefundResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "newStatus",
}

type ReserveStockReq struct {
	OrderNo       string `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	ProductId     int64  `thrift:"productId,2" frugal:"2,default,i64" json:"productId"`
	Quantity      int32  `thrift:"quantity,3" frugal:"3,default,i32" json:"quantity"`
	ExpireSeconds int64  `thrift:"expireSeconds,4" frugal:"4,default,i64" json:"expireSeconds"`
}

func NewReserveStockReq() *ReserveStockReq {
	return &ReserveStockReq{
		ExpireSeconds: 900,
	}
}

func (p *ReserveStockReq) InitDefault() {
	p.ExpireSeconds = 900
}

func (p *ReserveStockReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *ReserveStockReq) GetProductId() (v int64) {
	return p.ProductId
}

func (p *ReserveStockReq) GetQuantity() (v int32) {
	return p.Quantity
}

func (p *ReserveStockReq) GetExpireSeconds() (v int64) {
	return p.ExpireSeconds
}
func (p *ReserveStockReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *ReserveStockReq) SetProductId(val int64) {
	p.ProductId = val
}
func (p *ReserveStockReq) SetQuantity(val int32) {
	p.Quantity = val
}
func (p *ReserveStockReq) SetExpireSeconds(val int64) {
	p.ExpireSeconds = val
}

func (p *ReserveStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReserveStockReq(%+v)", *p)
}

var fieldIDToName_ReserveStockReq = map[int16]string{
	1: "orderNo",
	2: "productId",
	3: "quantity",
	4: "expireSeconds",
}

type ReserveStockResp struct {
	Success   bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code      int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message   string `thrift:"message,3" frugal:"3,default,string" json:"message"`
	ReserveId string `thrift:"reserveId,4" frugal:"4,default,string" json:"reserveId"`
}

func NewReserveStockResp() *ReserveStockResp {
	return &ReserveStockResp{
		Code: 0,
	}
}

func (p *ReserveStockResp) InitDefault() {
	p.Code = 0
}

func (p *ReserveStockResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ReserveStockResp) GetCode() (v int32) {
	return p.Code
}

func (p *ReserveStockResp) GetMessage() (v string) {
	return p.Message
}

func (p *ReserveStockResp) GetReserveId() (v string) {
	return p.ReserveId
}
func (p *ReserveStockResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ReserveStockResp) SetCode(val int32) {
	p.Code = val
}
func (p *ReserveStockResp) SetMessage(val string) {
	p.Message = val
}
func (p *ReserveStockResp) SetReserveId(val string) {
	p.ReserveId = val
}

func (p *ReserveStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReserveStockResp(%+v)", *p)
}

var fieldIDToName_ReserveStockResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "reserveId",
}

type ReleaseStockReq struct {
	ReserveId string `thrift:"reserveId,1" frugal:"1,default,string" json:"reserveId"`
	Reason    string `thrift:"reason,2" frugal:"2,default,string" json:"reason"`
}

func NewReleaseStockReq() *ReleaseStockReq {
	return &ReleaseStockReq{}
}

func (p *ReleaseStockReq) InitDefault() {
}

func (p *ReleaseStockReq) GetReserveId() (v string) {
	return p.ReserveId
}

func (p *ReleaseStockReq) GetReason() (v string) {
	return p.Reason
}
func (p *ReleaseStockReq) SetReserveId(val string) {
	p.ReserveId = val
}
func (p *ReleaseStockReq) SetReason(val string) {
	p.Reason = val
}

func (p *ReleaseStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseStockReq(%+v)", *p)
}

var fieldIDToName_ReleaseStockReq = map[int16]string{
	1: "reserveId",
	2: "reason",
}

type ReleaseStockResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewReleaseStockResp() *ReleaseStockResp {
	return &ReleaseStockResp{
		Code: 0,
	}
}

func (p *ReleaseStockResp) InitDefault() {
	p.Code = 0
}

func (p *ReleaseStockResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ReleaseStockResp) GetCode() (v int32) {
	return p.Code
}

func (p *ReleaseStockResp) GetMessage() (v string) {
	return p.Message
}
func (p *ReleaseStockResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ReleaseStockResp) SetCode(val int32) {
	p.Code = val
}
func (p *ReleaseStockResp) SetMessage(val string) {
	p.Message = val
}

func (p *ReleaseStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ReleaseStockResp(%+v)", *p)
}

var fieldIDToName_ReleaseStockResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
}

type ConfirmStockReq struct {
	ReserveId string `thrift:"reserveId,1" frugal:"1,default,string" json:"reserveId"`
	OrderNo   string `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
}

func NewConfirmStockReq() *ConfirmStockReq {
	return &ConfirmStockReq{}
}

func (p *ConfirmStockReq) InitDefault() {
}

func (p *ConfirmStockReq) GetReserveId() (v string) {
	return p.ReserveId
}

func (p *ConfirmStockReq) GetOrderNo() (v string) {
	return p.OrderNo
}
func (p *ConfirmStockReq) SetReserveId(val string) {
	p.ReserveId = val
}
func (p *ConfirmStockReq) SetOrderNo(val string) {
	p.OrderNo = val
}

func (p *ConfirmStockReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmStockReq(%+v)", *p)
}

var fieldIDToName_ConfirmStockReq = map[int16]string{
	1: "reserveId",
	2: "orderNo",
}

type ConfirmStockResp struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32  `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string `thrift:"message,3" frugal:"3,default,string" json:"message"`
}

func NewConfirmStockResp() *ConfirmStockResp {
	return &ConfirmStockResp{
		Code: 0,
	}
}

func (p *ConfirmStockResp) InitDefault() {
	p.Code = 0
}

func (p *ConfirmStockResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ConfirmStockResp) GetCode() (v int32) {
	return p.Code
}

func (p *ConfirmStockResp) GetMessage() (v string) {
	return p.Message
}
func (p *ConfirmStockResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ConfirmStockResp) SetCode(val int32) {
	p.Code = val
}
func (p *ConfirmStockResp) SetMessage(val string) {
	p.Message = val
}

func (p *ConfirmStockResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConfirmStockResp(%+v)", *p)
}

var fieldIDToName_ConfirmStockResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
}

type ProcessTimeoutReq struct {
	TaskId string      `thrift:"taskId,1" frugal:"1,default,string" json:"taskId"`
	Type   TimeoutType `thrift:"type,2" frugal:"2,default,TimeoutType" json:"type"`
}

func NewProcessTimeoutReq() *ProcessTimeoutReq {
	return &ProcessTimeoutReq{}
}

func (p *ProcessTimeoutReq) InitDefault() {
}

func (p *ProcessTimeoutReq) GetTaskId() (v string) {
	return p.TaskId
}

func (p *ProcessTimeoutReq) GetType() (v TimeoutType) {
	return p.Type
}
func (p *ProcessTimeoutReq) SetTaskId(val string) {
	p.TaskId = val
}
func (p *ProcessTimeoutReq) SetType(val TimeoutType) {
	p.Type = val
}

func (p *ProcessTimeoutReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProcessTimeoutReq(%+v)", *p)
}

var fieldIDToName_ProcessTimeoutReq = map[int16]string{
	1: "taskId",
	2: "type",
}

type ProcessTimeoutResp struct {
	Success bool              `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32             `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message string            `thrift:"message,3" frugal:"3,default,string" json:"message"`
	Results map[string]string `thrift:"results,4" frugal:"4,default,map<string:string>" json:"results"`
}

func NewProcessTimeoutResp() *ProcessTimeoutResp {
	return &ProcessTimeoutResp{
		Code: 0,
	}
}

func (p *ProcessTimeoutResp) InitDefault() {
	p.Code = 0
}

func (p *ProcessTimeoutResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *ProcessTimeoutResp) GetCode() (v int32) {
	return p.Code
}

func (p *ProcessTimeoutResp) GetMessage() (v string) {
	return p.Message
}

func (p *ProcessTimeoutResp) GetResults() (v map[string]string) {
	return p.Results
}
func (p *ProcessTimeoutResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *ProcessTimeoutResp) SetCode(val int32) {
	p.Code = val
}
func (p *ProcessTimeoutResp) SetMessage(val string) {
	p.Message = val
}
func (p *ProcessTimeoutResp) SetResults(val map[string]string) {
	p.Results = val
}

func (p *ProcessTimeoutResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProcessTimeoutResp(%+v)", *p)
}

var fieldIDToName_ProcessTimeoutResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "results",
}

type OrderStatsReq struct {
	UserId    int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	StartTime *int64 `thrift:"startTime,2,optional" frugal:"2,optional,i64" json:"startTime,omitempty"`
	EndTime   *int64 `thrift:"endTime,3,optional" frugal:"3,optional,i64" json:"endTime,omitempty"`
}

func NewOrderStatsReq() *OrderStatsReq {
	return &OrderStatsReq{}
}

func (p *OrderStatsReq) InitDefault() {
}

func (p *OrderStatsReq) GetUserId() (v int64) {
	return p.UserId
}

var OrderStatsReq_StartTime_DEFAULT int64

func (p *OrderStatsReq) GetStartTime() (v int64) {
	if !p.IsSetStartTime() {
		return OrderStatsReq_StartTime_DEFAULT
	}
	return *p.StartTime
}

var OrderStatsReq_EndTime_DEFAULT int64

func (p *OrderStatsReq) GetEndTime() (v int64) {
	if !p.IsSetEndTime() {
		return OrderStatsReq_EndTime_DEFAULT
	}
	return *p.EndTime
}
func (p *OrderStatsReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *OrderStatsReq) SetStartTime(val *int64) {
	p.StartTime = val
}
func (p *OrderStatsReq) SetEndTime(val *int64) {
	p.EndTime = val
}

func (p *OrderStatsReq) IsSetStartTime() bool {
	return p.StartTime != nil
}

func (p *OrderStatsReq) IsSetEndTime() bool {
	return p.EndTime != nil
}

func (p *OrderStatsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderStatsReq(%+v)", *p)
}

var fieldIDToName_OrderStatsReq = map[int16]string{
	1: "userId",
	2: "startTime",
	3: "endTime",
}

type OrderStatsResp struct {
	Success      bool             `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code         int32            `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message      string           `thrift:"message,3" frugal:"3,default,string" json:"message"`
	TotalOrders  int32            `thrift:"totalOrders,4" frugal:"4,default,i32" json:"totalOrders"`
	TotalAmount  float64          `thrift:"totalAmount,5" frugal:"5,default,double" json:"totalAmount"`
	StatusCounts map[string]int32 `thrift:"statusCounts,6" frugal:"6,default,map<string:i32>" json:"statusCounts"`
}

func NewOrderStatsResp() *OrderStatsResp {
	return &OrderStatsResp{
		Code: 0,
	}
}

func (p *OrderStatsResp) InitDefault() {
	p.Code = 0
}

func (p *OrderStatsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OrderStatsResp) GetCode() (v int32) {
	return p.Code
}

func (p *OrderStatsResp) GetMessage() (v string) {
	return p.Message
}

func (p *OrderStatsResp) GetTotalOrders() (v int32) {
	return p.TotalOrders
}

func (p *OrderStatsResp) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

func (p *OrderStatsResp) GetStatusCounts() (v map[string]int32) {
	return p.StatusCounts
}
func (p *OrderStatsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OrderStatsResp) SetCode(val int32) {
	p.Code = val
}
func (p *OrderStatsResp) SetMessage(val string) {
	p.Message = val
}
func (p *OrderStatsResp) SetTotalOrders(val int32) {
	p.TotalOrders = val
}
func (p *OrderStatsResp) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *OrderStatsResp) SetStatusCounts(val map[string]int32) {
	p.StatusCounts = val
}

func (p *OrderStatsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderStatsResp(%+v)", *p)
}

var fieldIDToName_OrderStatsResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "totalOrders",
	5: "totalAmount",
	6: "statusCounts",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	PayOrder(ctx context.Context, req *PayOrderReq) (r *PayOrderResp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (r *CancelOrderResp, err error)

	GetOrder(ctx context.Context, req *GetOrderReq) (r *GetOrderResp, err error)

	ListOrders(ctx context.Context, req *ListOrdersReq) (r *ListOrdersResp, err error)

	ApplyRefund(ctx context.Context, req *ApplyRefundReq) (r *ApplyRefundResp, err error)

	ProcessRefund(ctx context.Context, req *ProcessRefundReq) (r *ProcessRefundResp, err error)

	ReserveStock(ctx context.Context, req *ReserveStockReq) (r *ReserveStockResp, err error)

	ReleaseStock(ctx context.Context, req *ReleaseStockReq) (r *ReleaseStockResp, err error)

	ConfirmStock(ctx context.Context, req *ConfirmStockReq) (r *ConfirmStockResp, err error)

	ProcessTimeout(ctx context.Context, req *ProcessTimeoutReq) (r *ProcessTimeoutResp, err error)

	GetOrderStats(ctx context.Context, req *OrderStatsReq) (r *OrderStatsResp, err error)

	UpdateOrderStatus(ctx context.Context, req *CancelOrderReq) (r *CancelOrderResp, err error)

	ShipOrder(ctx context.Context, req *PayOrderReq) (r *PayOrderResp, err error)

	ConfirmReceipt(ctx context.Context, req *PayOrderReq) (r *PayOrderResp, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServicePayOrderArgs struct {
	Req *PayOrderReq `thrift:"req,1" frugal:"1,default,PayOrderReq" json:"req"`
}

func NewOrderServicePayOrderArgs() *OrderServicePayOrderArgs {
	return &OrderServicePayOrderArgs{}
}

func (p *OrderServicePayOrderArgs) InitDefault() {
}

var OrderServicePayOrderArgs_Req_DEFAULT *PayOrderReq

func (p *OrderServicePayOrderArgs) GetReq() (v *PayOrderReq) {
	if !p.IsSetReq() {
		return OrderServicePayOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServicePayOrderArgs) SetReq(val *PayOrderReq) {
	p.Req = val
}

func (p *OrderServicePayOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServicePayOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePayOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServicePayOrderArgs = map[int16]string{
	1: "req",
}

type OrderServicePayOrderResult struct {
	Success *PayOrderResp `thrift:"success,0,optional" frugal:"0,optional,PayOrderResp" json:"success,omitempty"`
}

func NewOrderServicePayOrderResult() *OrderServicePayOrderResult {
	return &OrderServicePayOrderResult{}
}

func (p *OrderServicePayOrderResult) InitDefault() {
}

var OrderServicePayOrderResult_Success_DEFAULT *PayOrderResp

func (p *OrderServicePayOrderResult) GetSuccess() (v *PayOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServicePayOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServicePayOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*PayOrderResp)
}

func (p *OrderServicePayOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServicePayOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePayOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServicePayOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceCancelOrderArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewOrderServiceCancelOrderArgs() *OrderServiceCancelOrderArgs {
	return &OrderServiceCancelOrderArgs{}
}

func (p *OrderServiceCancelOrderArgs) InitDefault() {
}

var OrderServiceCancelOrderArgs_Req_DEFAULT *CancelOrderReq

func (p *OrderServiceCancelOrderArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCancelOrderArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *OrderServiceCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCancelOrderResult struct {
	Success *CancelOrderResp `thrift:"success,0,optional" frugal:"0,optional,CancelOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCancelOrderResult() *OrderServiceCancelOrderResult {
	return &OrderServiceCancelOrderResult{}
}

func (p *OrderServiceCancelOrderResult) InitDefault() {
}

var OrderServiceCancelOrderResult_Success_DEFAULT *CancelOrderResp

func (p *OrderServiceCancelOrderResult) GetSuccess() (v *CancelOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelOrderResp)
}

func (p *OrderServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceGetOrderArgs struct {
	Req *GetOrderReq `thrift:"req,1" frugal:"1,default,GetOrderReq" json:"req"`
}

func NewOrderServiceGetOrderArgs() *OrderServiceGetOrderArgs {
	return &OrderServiceGetOrderArgs{}
}

func (p *OrderServiceGetOrderArgs) InitDefault() {
}

var OrderServiceGetOrderArgs_Req_DEFAULT *GetOrderReq

func (p *OrderServiceGetOrderArgs) GetReq() (v *GetOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceGetOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetOrderArgs) SetReq(val *GetOrderReq) {
	p.Req = val
}

func (p *OrderServiceGetOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetOrderResult struct {
	Success *GetOrderResp `thrift:"success,0,optional" frugal:"0,optional,GetOrderResp" json:"success,omitempty"`
}

func NewOrderServiceGetOrderResult() *OrderServiceGetOrderResult {
	return &OrderServiceGetOrderResult{}
}

func (p *OrderServiceGetOrderResult) InitDefault() {
}

var OrderServiceGetOrderResult_Success_DEFAULT *GetOrderResp

func (p *OrderServiceGetOrderResult) GetSuccess() (v *GetOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderResp)
}

func (p *OrderServiceGetOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceListOrdersArgs struct {
	Req *ListOrdersReq `thrift:"req,1" frugal:"1,default,ListOrdersReq" json:"req"`
}

func NewOrderServiceListOrdersArgs() *OrderServiceListOrdersArgs {
	return &OrderServiceListOrdersArgs{}
}

func (p *OrderServiceListOrdersArgs) InitDefault() {
}

var OrderServiceListOrdersArgs_Req_DEFAULT *ListOrdersReq

func (p *OrderServiceListOrdersArgs) GetReq() (v *ListOrdersReq) {
	if !p.IsSetReq() {
		return OrderServiceListOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceListOrdersArgs) SetReq(val *ListOrdersReq) {
	p.Req = val
}

func (p *OrderServiceListOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceListOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersArgs = map[int16]string{
	1: "req",
}

type OrderServiceListOrdersResult struct {
	Success *ListOrdersResp `thrift:"success,0,optional" frugal:"0,optional,ListOrdersResp" json:"success,omitempty"`
}

func NewOrderServiceListOrdersResult() *OrderServiceListOrdersResult {
	return &OrderServiceListOrdersResult{}
}

func (p *OrderServiceListOrdersResult) InitDefault() {
}

var OrderServiceListOrdersResult_Success_DEFAULT *ListOrdersResp

func (p *OrderServiceListOrdersResult) GetSuccess() (v *ListOrdersResp) {
	if !p.IsSetSuccess() {
		return OrderServiceListOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceListOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListOrdersResp)
}

func (p *OrderServiceListOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceListOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceListOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceListOrdersResult = map[int16]string{
	0: "success",
}

type OrderServiceApplyRefundArgs struct {
	Req *ApplyRefundReq `thrift:"req,1" frugal:"1,default,ApplyRefundReq" json:"req"`
}

func NewOrderServiceApplyRefundArgs() *OrderServiceApplyRefundArgs {
	return &OrderServiceApplyRefundArgs{}
}

func (p *OrderServiceApplyRefundArgs) InitDefault() {
}

var OrderServiceApplyRefundArgs_Req_DEFAULT *ApplyRefundReq

func (p *OrderServiceApplyRefundArgs) GetReq() (v *ApplyRefundReq) {
	if !p.IsSetReq() {
		return OrderServiceApplyRefundArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceApplyRefundArgs) SetReq(val *ApplyRefundReq) {
	p.Req = val
}

func (p *OrderServiceApplyRefundArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceApplyRefundArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceApplyRefundArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceApplyRefundArgs = map[int16]string{
	1: "req",
}

type OrderServiceApplyRefundResult struct {
	Success *ApplyRefundResp `thrift:"success,0,optional" frugal:"0,optional,ApplyRefundResp" json:"success,omitempty"`
}

func NewOrderServiceApplyRefundResult() *OrderServiceApplyRefundResult {
	return &OrderServiceApplyRefundResult{}
}

func (p *OrderServiceApplyRefundResult) InitDefault() {
}

var OrderServiceApplyRefundResult_Success_DEFAULT *ApplyRefundResp

func (p *OrderServiceApplyRefundResult) GetSuccess() (v *ApplyRefundResp) {
	if !p.IsSetSuccess() {
		return OrderServiceApplyRefundResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceApplyRefundResult) SetSuccess(x interface{}) {
	p.Success = x.(*ApplyRefundResp)
}

func (p *OrderServiceApplyRefundResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceApplyRefundResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceApplyRefundResult(%+v)", *p)
}

var fieldIDToName_OrderServiceApplyRefundResult = map[int16]string{
	0: "success",
}

type OrderServiceProcessRefundArgs struct {
	Req *ProcessRefundReq `thrift:"req,1" frugal:"1,default,ProcessRefundReq" json:"req"`
}

func NewOrderServiceProcessRefundArgs() *OrderServiceProcessRefundArgs {
	return &OrderServiceProcessRefundArgs{}
}

func (p *OrderServiceProcessRefundArgs) InitDefault() {
}

var OrderServiceProcessRefundArgs_Req_DEFAULT *ProcessRefundReq

func (p *OrderServiceProcessRefundArgs) GetReq() (v *ProcessRefundReq) {
	if !p.IsSetReq() {
		return OrderServiceProcessRefundArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceProcessRefundArgs) SetReq(val *ProcessRefundReq) {
	p.Req = val
}

func (p *OrderServiceProcessRefundArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceProcessRefundArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceProcessRefundArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceProcessRefundArgs = map[int16]string{
	1: "req",
}

type OrderServiceProcessRefundResult struct {
	Success *ProcessRefundResp `thrift:"success,0,optional" frugal:"0,optional,ProcessRefundResp" json:"success,omitempty"`
}

func NewOrderServiceProcessRefundResult() *OrderServiceProcessRefundResult {
	return &OrderServiceProcessRefundResult{}
}

func (p *OrderServiceProcessRefundResult) InitDefault() {
}

var OrderServiceProcessRefundResult_Success_DEFAULT *ProcessRefundResp

func (p *OrderServiceProcessRefundResult) GetSuccess() (v *ProcessRefundResp) {
	if !p.IsSetSuccess() {
		return OrderServiceProcessRefundResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceProcessRefundResult) SetSuccess(x interface{}) {
	p.Success = x.(*ProcessRefundResp)
}

func (p *OrderServiceProcessRefundResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceProcessRefundResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceProcessRefundResult(%+v)", *p)
}

var fieldIDToName_OrderServiceProcessRefundResult = map[int16]string{
	0: "success",
}

type OrderServiceReserveStockArgs struct {
	Req *ReserveStockReq `thrift:"req,1" frugal:"1,default,ReserveStockReq" json:"req"`
}

func NewOrderServiceReserveStockArgs() *OrderServiceReserveStockArgs {
	return &OrderServiceReserveStockArgs{}
}

func (p *OrderServiceReserveStockArgs) InitDefault() {
}

var OrderServiceReserveStockArgs_Req_DEFAULT *ReserveStockReq

func (p *OrderServiceReserveStockArgs) GetReq() (v *ReserveStockReq) {
	if !p.IsSetReq() {
		return OrderServiceReserveStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceReserveStockArgs) SetReq(val *ReserveStockReq) {
	p.Req = val
}

func (p *OrderServiceReserveStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceReserveStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceReserveStockArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceReserveStockArgs = map[int16]string{
	1: "req",
}

type OrderServiceReserveStockResult struct {
	Success *ReserveStockResp `thrift:"success,0,optional" frugal:"0,optional,ReserveStockResp" json:"success,omitempty"`
}

func NewOrderServiceReserveStockResult() *OrderServiceReserveStockResult {
	return &OrderServiceReserveStockResult{}
}

func (p *OrderServiceReserveStockResult) InitDefault() {
}

var OrderServiceReserveStockResult_Success_DEFAULT *ReserveStockResp

func (p *OrderServiceReserveStockResult) GetSuccess() (v *ReserveStockResp) {
	if !p.IsSetSuccess() {
		return OrderServiceReserveStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceReserveStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReserveStockResp)
}

func (p *OrderServiceReserveStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceReserveStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceReserveStockResult(%+v)", *p)
}

var fieldIDToName_OrderServiceReserveStockResult = map[int16]string{
	0: "success",
}

type OrderServiceReleaseStockArgs struct {
	Req *ReleaseStockReq `thrift:"req,1" frugal:"1,default,ReleaseStockReq" json:"req"`
}

func NewOrderServiceReleaseStockArgs() *OrderServiceReleaseStockArgs {
	return &OrderServiceReleaseStockArgs{}
}

func (p *OrderServiceReleaseStockArgs) InitDefault() {
}

var OrderServiceReleaseStockArgs_Req_DEFAULT *ReleaseStockReq

func (p *OrderServiceReleaseStockArgs) GetReq() (v *ReleaseStockReq) {
	if !p.IsSetReq() {
		return OrderServiceReleaseStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceReleaseStockArgs) SetReq(val *ReleaseStockReq) {
	p.Req = val
}

func (p *OrderServiceReleaseStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceReleaseStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceReleaseStockArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceReleaseStockArgs = map[int16]string{
	1: "req",
}

type OrderServiceReleaseStockResult struct {
	Success *ReleaseStockResp `thrift:"success,0,optional" frugal:"0,optional,ReleaseStockResp" json:"success,omitempty"`
}

func NewOrderServiceReleaseStockResult() *OrderServiceReleaseStockResult {
	return &OrderServiceReleaseStockResult{}
}

func (p *OrderServiceReleaseStockResult) InitDefault() {
}

var OrderServiceReleaseStockResult_Success_DEFAULT *ReleaseStockResp

func (p *OrderServiceReleaseStockResult) GetSuccess() (v *ReleaseStockResp) {
	if !p.IsSetSuccess() {
		return OrderServiceReleaseStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceReleaseStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*ReleaseStockResp)
}

func (p *OrderServiceReleaseStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceReleaseStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceReleaseStockResult(%+v)", *p)
}

var fieldIDToName_OrderServiceReleaseStockResult = map[int16]string{
	0: "success",
}

type OrderServiceConfirmStockArgs struct {
	Req *ConfirmStockReq `thrift:"req,1" frugal:"1,default,ConfirmStockReq" json:"req"`
}

func NewOrderServiceConfirmStockArgs() *OrderServiceConfirmStockArgs {
	return &OrderServiceConfirmStockArgs{}
}

func (p *OrderServiceConfirmStockArgs) InitDefault() {
}

var OrderServiceConfirmStockArgs_Req_DEFAULT *ConfirmStockReq

func (p *OrderServiceConfirmStockArgs) GetReq() (v *ConfirmStockReq) {
	if !p.IsSetReq() {
		return OrderServiceConfirmStockArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceConfirmStockArgs) SetReq(val *ConfirmStockReq) {
	p.Req = val
}

func (p *OrderServiceConfirmStockArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceConfirmStockArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmStockArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmStockArgs = map[int16]string{
	1: "req",
}

type OrderServiceConfirmStockResult struct {
	Success *ConfirmStockResp `thrift:"success,0,optional" frugal:"0,optional,ConfirmStockResp" json:"success,omitempty"`
}

func NewOrderServiceConfirmStockResult() *OrderServiceConfirmStockResult {
	return &OrderServiceConfirmStockResult{}
}

func (p *OrderServiceConfirmStockResult) InitDefault() {
}

var OrderServiceConfirmStockResult_Success_DEFAULT *ConfirmStockResp

func (p *OrderServiceConfirmStockResult) GetSuccess() (v *ConfirmStockResp) {
	if !p.IsSetSuccess() {
		return OrderServiceConfirmStockResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceConfirmStockResult) SetSuccess(x interface{}) {
	p.Success = x.(*ConfirmStockResp)
}

func (p *OrderServiceConfirmStockResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceConfirmStockResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmStockResult(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmStockResult = map[int16]string{
	0: "success",
}

type OrderServiceProcessTimeoutArgs struct {
	Req *ProcessTimeoutReq `thrift:"req,1" frugal:"1,default,ProcessTimeoutReq" json:"req"`
}

func NewOrderServiceProcessTimeoutArgs() *OrderServiceProcessTimeoutArgs {
	return &OrderServiceProcessTimeoutArgs{}
}

func (p *OrderServiceProcessTimeoutArgs) InitDefault() {
}

var OrderServiceProcessTimeoutArgs_Req_DEFAULT *ProcessTimeoutReq

func (p *OrderServiceProcessTimeoutArgs) GetReq() (v *ProcessTimeoutReq) {
	if !p.IsSetReq() {
		return OrderServiceProcessTimeoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceProcessTimeoutArgs) SetReq(val *ProcessTimeoutReq) {
	p.Req = val
}

func (p *OrderServiceProcessTimeoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceProcessTimeoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceProcessTimeoutArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceProcessTimeoutArgs = map[int16]string{
	1: "req",
}

type OrderServiceProcessTimeoutResult struct {
	Success *ProcessTimeoutResp `thrift:"success,0,optional" frugal:"0,optional,ProcessTimeoutResp" json:"success,omitempty"`
}

func NewOrderServiceProcessTimeoutResult() *OrderServiceProcessTimeoutResult {
	return &OrderServiceProcessTimeoutResult{}
}

func (p *OrderServiceProcessTimeoutResult) InitDefault() {
}

var OrderServiceProcessTimeoutResult_Success_DEFAULT *ProcessTimeoutResp

func (p *OrderServiceProcessTimeoutResult) GetSuccess() (v *ProcessTimeoutResp) {
	if !p.IsSetSuccess() {
		return OrderServiceProcessTimeoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceProcessTimeoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*ProcessTimeoutResp)
}

func (p *OrderServiceProcessTimeoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceProcessTimeoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceProcessTimeoutResult(%+v)", *p)
}

var fieldIDToName_OrderServiceProcessTimeoutResult = map[int16]string{
	0: "success",
}

type OrderServiceGetOrderStatsArgs struct {
	Req *OrderStatsReq `thrift:"req,1" frugal:"1,default,OrderStatsReq" json:"req"`
}

func NewOrderServiceGetOrderStatsArgs() *OrderServiceGetOrderStatsArgs {
	return &OrderServiceGetOrderStatsArgs{}
}

func (p *OrderServiceGetOrderStatsArgs) InitDefault() {
}

var OrderServiceGetOrderStatsArgs_Req_DEFAULT *OrderStatsReq

func (p *OrderServiceGetOrderStatsArgs) GetReq() (v *OrderStatsReq) {
	if !p.IsSetReq() {
		return OrderServiceGetOrderStatsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetOrderStatsArgs) SetReq(val *OrderStatsReq) {
	p.Req = val
}

func (p *OrderServiceGetOrderStatsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetOrderStatsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderStatsArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderStatsArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetOrderStatsResult struct {
	Success *OrderStatsResp `thrift:"success,0,optional" frugal:"0,optional,OrderStatsResp" json:"success,omitempty"`
}

func NewOrderServiceGetOrderStatsResult() *OrderServiceGetOrderStatsResult {
	return &OrderServiceGetOrderStatsResult{}
}

func (p *OrderServiceGetOrderStatsResult) InitDefault() {
}

var OrderServiceGetOrderStatsResult_Success_DEFAULT *OrderStatsResp

func (p *OrderServiceGetOrderStatsResult) GetSuccess() (v *OrderStatsResp) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderStatsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrderStatsResult) SetSuccess(x interface{}) {
	p.Success = x.(*OrderStatsResp)
}

func (p *OrderServiceGetOrderStatsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderStatsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderStatsResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderStatsResult = map[int16]string{
	0: "success",
}

type OrderServiceUpdateOrderStatusArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewOrderServiceUpdateOrderStatusArgs() *OrderServiceUpdateOrderStatusArgs {
	return &OrderServiceUpdateOrderStatusArgs{}
}

func (p *OrderServiceUpdateOrderStatusArgs) InitDefault() {
}

var OrderServiceUpdateOrderStatusArgs_Req_DEFAULT *CancelOrderReq

func (p *OrderServiceUpdateOrderStatusArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceUpdateOrderStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceUpdateOrderStatusArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *OrderServiceUpdateOrderStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceUpdateOrderStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateOrderStatusArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateOrderStatusArgs = map[int16]string{
	1: "req",
}

type OrderServiceUpdateOrderStatusResult struct {
	Success *CancelOrderResp `thrift:"success,0,optional" frugal:"0,optional,CancelOrderResp" json:"success,omitempty"`
}

func NewOrderServiceUpdateOrderStatusResult() *OrderServiceUpdateOrderStatusResult {
	return &OrderServiceUpdateOrderStatusResult{}
}

func (p *OrderServiceUpdateOrderStatusResult) InitDefault() {
}

var OrderServiceUpdateOrderStatusResult_Success_DEFAULT *CancelOrderResp

func (p *OrderServiceUpdateOrderStatusResult) GetSuccess() (v *CancelOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceUpdateOrderStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceUpdateOrderStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelOrderResp)
}

func (p *OrderServiceUpdateOrderStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceUpdateOrderStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateOrderStatusResult(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateOrderStatusResult = map[int16]string{
	0: "success",
}

type OrderServiceShipOrderArgs struct {
	Req *PayOrderReq `thrift:"req,1" frugal:"1,default,PayOrderReq" json:"req"`
}

func NewOrderServiceShipOrderArgs() *OrderServiceShipOrderArgs {
	return &OrderServiceShipOrderArgs{}
}

func (p *OrderServiceShipOrderArgs) InitDefault() {
}

var OrderServiceShipOrderArgs_Req_DEFAULT *PayOrderReq

func (p *OrderServiceShipOrderArgs) GetReq() (v *PayOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceShipOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceShipOrderArgs) SetReq(val *PayOrderReq) {
	p.Req = val
}

func (p *OrderServiceShipOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceShipOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceShipOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceShipOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceShipOrderResult struct {
	Success *PayOrderResp `thrift:"success,0,optional" frugal:"0,optional,PayOrderResp" json:"success,omitempty"`
}

func NewOrderServiceShipOrderResult() *OrderServiceShipOrderResult {
	return &OrderServiceShipOrderResult{}
}

func (p *OrderServiceShipOrderResult) InitDefault() {
}

var OrderServiceShipOrderResult_Success_DEFAULT *PayOrderResp

func (p *OrderServiceShipOrderResult) GetSuccess() (v *PayOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceShipOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceShipOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*PayOrderResp)
}

func (p *OrderServiceShipOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceShipOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceShipOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceShipOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceConfirmReceiptArgs struct {
	Req *PayOrderReq `thrift:"req,1" frugal:"1,default,PayOrderReq" json:"req"`
}

func NewOrderServiceConfirmReceiptArgs() *OrderServiceConfirmReceiptArgs {
	return &OrderServiceConfirmReceiptArgs{}
}

func (p *OrderServiceConfirmReceiptArgs) InitDefault() {
}

var OrderServiceConfirmReceiptArgs_Req_DEFAULT *PayOrderReq

func (p *OrderServiceConfirmReceiptArgs) GetReq() (v *PayOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceConfirmReceiptArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceConfirmReceiptArgs) SetReq(val *PayOrderReq) {
	p.Req = val
}

func (p *OrderServiceConfirmReceiptArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceConfirmReceiptArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmReceiptArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmReceiptArgs = map[int16]string{
	1: "req",
}

type OrderServiceConfirmReceiptResult struct {
	Success *PayOrderResp `thrift:"success,0,optional" frugal:"0,optional,PayOrderResp" json:"success,omitempty"`
}

func NewOrderServiceConfirmReceiptResult() *OrderServiceConfirmReceiptResult {
	return &OrderServiceConfirmReceiptResult{}
}

func (p *OrderServiceConfirmReceiptResult) InitDefault() {
}

var OrderServiceConfirmReceiptResult_Success_DEFAULT *PayOrderResp

func (p *OrderServiceConfirmReceiptResult) GetSuccess() (v *PayOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceConfirmReceiptResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceConfirmReceiptResult) SetSuccess(x interface{}) {
	p.Success = x.(*PayOrderResp)
}

func (p *OrderServiceConfirmReceiptResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceConfirmReceiptResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceConfirmReceiptResult(%+v)", *p)
}

var fieldIDToName_OrderServiceConfirmReceiptResult = map[int16]string{
	0: "success",
}
