// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ProductStatus int64

const (
	ProductStatus_DRAFT   ProductStatus = 0
	ProductStatus_ONLINE  ProductStatus = 1
	ProductStatus_OFFLINE ProductStatus = 2
	ProductStatus_DELETED ProductStatus = 3
)

func (p ProductStatus) String() string {
	switch p {
	case ProductStatus_DRAFT:
		return "DRAFT"
	case ProductStatus_ONLINE:
		return "ONLINE"
	case ProductStatus_OFFLINE:
		return "OFFLINE"
	case ProductStatus_DELETED:
		return "DELETED"
	}
	return "<UNSET>"
}

func ProductStatusFromString(s string) (ProductStatus, error) {
	switch s {
	case "DRAFT":
		return ProductStatus_DRAFT, nil
	case "ONLINE":
		return ProductStatus_ONLINE, nil
	case "OFFLINE":
		return ProductStatus_OFFLINE, nil
	case "DELETED":
		return ProductStatus_DELETED, nil
	}
	return ProductStatus(0), fmt.Errorf("not a valid ProductStatus string")
}

func ProductStatusPtr(v ProductStatus) *ProductStatus { return &v }
func (p *ProductStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ProductStatus(result.Int64)
	return
}

func (p *ProductStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type Product struct {
	Id        int64         `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name      string        `thrift:"name,2" frugal:"2,default,string" json:"name"`
	Avatar    string        `thrift:"avatar,3" frugal:"3,default,string" json:"avatar"`
	Category  string        `thrift:"category,4" frugal:"4,default,string" json:"category"`
	Price     float64       `thrift:"price,5" frugal:"5,default,double" json:"price"`
	Stock     int32         `thrift:"stock,6" frugal:"6,default,i32" json:"stock"`
	Status    ProductStatus `thrift:"status,7" frugal:"7,default,ProductStatus" json:"status"`
	CreatedAt int64         `thrift:"createdAt,8" frugal:"8,default,i64" json:"createdAt"`
	UpdatedAt int64         `thrift:"updatedAt,9" frugal:"9,default,i64" json:"updatedAt"`
	Brand     *string       `thrift:"brand,10,optional" frugal:"10,optional,string" json:"brand,omitempty"`
}

func NewProduct() *Product {
	return &Product{
		Status: ProductStatus_DRAFT,
	}
}

func (p *Product) InitDefault() {
	p.Status = ProductStatus_DRAFT
}

func (p *Product) GetId() (v int64) {
	return p.Id
}

func (p *Product) GetName() (v string) {
	return p.Name
}

func (p *Product) GetAvatar() (v string) {
	return p.Avatar
}

func (p *Product) GetCategory() (v string) {
	return p.Category
}

func (p *Product) GetPrice() (v float64) {
	return p.Price
}

func (p *Product) GetStock() (v int32) {
	return p.Stock
}

func (p *Product) GetStatus() (v ProductStatus) {
	return p.Status
}

func (p *Product) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *Product) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

var Product_Brand_DEFAULT string

func (p *Product) GetBrand() (v string) {
	if !p.IsSetBrand() {
		return Product_Brand_DEFAULT
	}
	return *p.Brand
}
func (p *Product) SetId(val int64) {
	p.Id = val
}
func (p *Product) SetName(val string) {
	p.Name = val
}
func (p *Product) SetAvatar(val string) {
	p.Avatar = val
}
func (p *Product) SetCategory(val string) {
	p.Category = val
}
func (p *Product) SetPrice(val float64) {
	p.Price = val
}
func (p *Product) SetStock(val int32) {
	p.Stock = val
}
func (p *Product) SetStatus(val ProductStatus) {
	p.Status = val
}
func (p *Product) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *Product) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *Product) SetBrand(val *string) {
	p.Brand = val
}

func (p *Product) IsSetBrand() bool {
	return p.Brand != nil
}

func (p *Product) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Product(%+v)", *p)
}

var fieldIDToName_Product = map[int16]string{
	1:  "id",
	2:  "name",
	3:  "avatar",
	4:  "category",
	5:  "price",
	6:  "stock",
	7:  "status",
	8:  "createdAt",
	9:  "updatedAt",
	10: "brand",
}

type SimpleProduct struct {
	Id       int64         `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Category string        `thrift:"category,2" frugal:"2,default,string" json:"category"`
	Price    float64       `thrift:"price,3" frugal:"3,default,double" json:"price"`
	Stock    int32         `thrift:"stock,4" frugal:"4,default,i32" json:"stock"`
	Status   ProductStatus `thrift:"status,5" frugal:"5,default,ProductStatus" json:"status"`
	Brand    *string       `thrift:"brand,6,optional" frugal:"6,optional,string" json:"brand,omitempty"`
	Name     string        `thrift:"name,7" frugal:"7,default,string" json:"name"`
	Avatar   string        `thrift:"avatar,8" frugal:"8,default,string" json:"avatar"`
}

func NewSimpleProduct() *SimpleProduct {
	return &SimpleProduct{
		Status: ProductStatus_ONLINE,
	}
}

func (p *SimpleProduct) InitDefault() {
	p.Status = ProductStatus_ONLINE
}

func (p *SimpleProduct) GetId() (v int64) {
	return p.Id
}

func (p *SimpleProduct) GetCategory() (v string) {
	return p.Category
}

func (p *SimpleProduct) GetPrice() (v float64) {
	return p.Price
}

func (p *SimpleProduct) GetStock() (v int32) {
	return p.Stock
}

func (p *SimpleProduct) GetStatus() (v ProductStatus) {
	return p.Status
}

var SimpleProduct_Brand_DEFAULT string

func (p *SimpleProduct) GetBrand() (v string) {
	if !p.IsSetBrand() {
		return SimpleProduct_Brand_DEFAULT
	}
	return *p.Brand
}

func (p *SimpleProduct) GetName() (v string) {
	return p.Name
}

func (p *SimpleProduct) GetAvatar() (v string) {
	return p.Avatar
}
func (p *SimpleProduct) SetId(val int64) {
	p.Id = val
}
func (p *SimpleProduct) SetCategory(val string) {
	p.Category = val
}
func (p *SimpleProduct) SetPrice(val float64) {
	p.Price = val
}
func (p *SimpleProduct) SetStock(val int32) {
	p.Stock = val
}
func (p *SimpleProduct) SetStatus(val ProductStatus) {
	p.Status = val
}
func (p *SimpleProduct) SetBrand(val *string) {
	p.Brand = val
}
func (p *SimpleProduct) SetName(val string) {
	p.Name = val
}
func (p *SimpleProduct) SetAvatar(val string) {
	p.Avatar = val
}

func (p *SimpleProduct) IsSetBrand() bool {
	return p.Brand != nil
}

func (p *SimpleProduct) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SimpleProduct(%+v)", *p)
}

var fieldIDToName_SimpleProduct = map[int16]string{
	1: "id",
	2: "category",
	3: "price",
	4: "stock",
	5: "status",
	6: "brand",
	7: "name",
	8: "avatar",
}

type CreateProductReq struct {
	Name     string        `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Avatar   string        `thrift:"avatar,2" frugal:"2,default,string" json:"avatar"`
	Category string        `thrift:"category,3" frugal:"3,default,string" json:"category"`
	Price    float64       `thrift:"price,4" frugal:"4,default,double" json:"price"`
	Stock    int32         `thrift:"stock,5" frugal:"5,default,i32" json:"stock"`
	Brand    *string       `thrift:"brand,6,optional" frugal:"6,optional,string" json:"brand,omitempty"`
	Status   ProductStatus `thrift:"status,7,optional" frugal:"7,optional,ProductStatus" json:"status,omitempty"`
}

func NewCreateProductReq() *CreateProductReq {
	return &CreateProductReq{
		Status: ProductStatus_DRAFT,
	}
}

func (p *CreateProductReq) InitDefault() {
	p.Status = ProductStatus_DRAFT
}

func (p *CreateProductReq) GetName() (v string) {
	return p.Name
}

func (p *CreateProductReq) GetAvatar() (v string) {
	return p.Avatar
}

func (p *CreateProductReq) GetCategory() (v string) {
	return p.Category
}

func (p *CreateProductReq) GetPrice() (v float64) {
	return p.Price
}

func (p *CreateProductReq) GetStock() (v int32) {
	return p.Stock
}

var CreateProductReq_Brand_DEFAULT string

func (p *CreateProductReq) GetBrand() (v string) {
	if !p.IsSetBrand() {
		return CreateProductReq_Brand_DEFAULT
	}
	return *p.Brand
}

var CreateProductReq_Status_DEFAULT ProductStatus = ProductStatus_DRAFT

func (p *CreateProductReq) GetStatus() (v ProductStatus) {
	if !p.IsSetStatus() {
		return CreateProductReq_Status_DEFAULT
	}
	return p.Status
}
func (p *CreateProductReq) SetName(val string) {
	p.Name = val
}
func (p *CreateProductReq) SetAvatar(val string) {
	p.Avatar = val
}
func (p *CreateProductReq) SetCategory(val string) {
	p.Category = val
}
func (p *CreateProductReq) SetPrice(val float64) {
	p.Price = val
}
func (p *CreateProductReq) SetStock(val int32) {
	p.Stock = val
}
func (p *CreateProductReq) SetBrand(val *string) {
	p.Brand = val
}
func (p *CreateProductReq) SetStatus(val ProductStatus) {
	p.Status = val
}

func (p *CreateProductReq) IsSetBrand() bool {
	return p.Brand != nil
}

func (p *CreateProductReq) IsSetStatus() bool {
	return p.Status != CreateProductReq_Status_DEFAULT
}

func (p *CreateProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductReq(%+v)", *p)
}

var fieldIDToName_CreateProductReq = map[int16]string{
	1: "name",
	2: "avatar",
	3: "category",
	4: "price",
	5: "stock",
	6: "brand",
	7: "status",
}

type CreateProductResp struct {
	Success bool     `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32    `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string  `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Product *Product `thrift:"product,4" frugal:"4,default,Product" json:"product"`
}

func NewCreateProductResp() *CreateProductResp {
	return &CreateProductResp{
		Code: 0,
	}
}

func (p *CreateProductResp) InitDefault() {
	p.Code = 0
}

func (p *CreateProductResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreateProductResp) GetCode() (v int32) {
	return p.Code
}

var CreateProductResp_Message_DEFAULT string

func (p *CreateProductResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return CreateProductResp_Message_DEFAULT
	}
	return *p.Message
}

var CreateProductResp_Product_DEFAULT *Product

func (p *CreateProductResp) GetProduct() (v *Product) {
	if !p.IsSetProduct() {
		return CreateProductResp_Product_DEFAULT
	}
	return p.Product
}
func (p *CreateProductResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreateProductResp) SetCode(val int32) {
	p.Code = val
}
func (p *CreateProductResp) SetMessage(val *string) {
	p.Message = val
}
func (p *CreateProductResp) SetProduct(val *Product) {
	p.Product = val
}

func (p *CreateProductResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *CreateProductResp) IsSetProduct() bool {
	return p.Product != nil
}

func (p *CreateProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateProductResp(%+v)", *p)
}

var fieldIDToName_CreateProductResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "product",
}

type GetProductReq struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewGetProductReq() *GetProductReq {
	return &GetProductReq{}
}

func (p *GetProductReq) InitDefault() {
}

func (p *GetProductReq) GetId() (v int64) {
	return p.Id
}
func (p *GetProductReq) SetId(val int64) {
	p.Id = val
}

func (p *GetProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductReq(%+v)", *p)
}

var fieldIDToName_GetProductReq = map[int16]string{
	1: "id",
}

type GetProductResp struct {
	Success bool     `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32    `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string  `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Product *Product `thrift:"product,4" frugal:"4,default,Product" json:"product"`
}

func NewGetProductResp() *GetProductResp {
	return &GetProductResp{
		Code: 0,
	}
}

func (p *GetProductResp) InitDefault() {
	p.Code = 0
}

func (p *GetProductResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetProductResp) GetCode() (v int32) {
	return p.Code
}

var GetProductResp_Message_DEFAULT string

func (p *GetProductResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return GetProductResp_Message_DEFAULT
	}
	return *p.Message
}

var GetProductResp_Product_DEFAULT *Product

func (p *GetProductResp) GetProduct() (v *Product) {
	if !p.IsSetProduct() {
		return GetProductResp_Product_DEFAULT
	}
	return p.Product
}
func (p *GetProductResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetProductResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetProductResp) SetMessage(val *string) {
	p.Message = val
}
func (p *GetProductResp) SetProduct(val *Product) {
	p.Product = val
}

func (p *GetProductResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *GetProductResp) IsSetProduct() bool {
	return p.Product != nil
}

func (p *GetProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetProductResp(%+v)", *p)
}

var fieldIDToName_GetProductResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "product",
}

type UpdateProductReq struct {
	Id       int64          `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Name     *string        `thrift:"name,2,optional" frugal:"2,optional,string" json:"name,omitempty"`
	Avatar   *string        `thrift:"avatar,3,optional" frugal:"3,optional,string" json:"avatar,omitempty"`
	Category *string        `thrift:"category,4,optional" frugal:"4,optional,string" json:"category,omitempty"`
	Price    *float64       `thrift:"price,5,optional" frugal:"5,optional,double" json:"price,omitempty"`
	Stock    *int32         `thrift:"stock,6,optional" frugal:"6,optional,i32" json:"stock,omitempty"`
	Status   *ProductStatus `thrift:"status,7,optional" frugal:"7,optional,ProductStatus" json:"status,omitempty"`
	Brand    *string        `thrift:"brand,8,optional" frugal:"8,optional,string" json:"brand,omitempty"`
}

func NewUpdateProductReq() *UpdateProductReq {
	return &UpdateProductReq{}
}

func (p *UpdateProductReq) InitDefault() {
}

func (p *UpdateProductReq) GetId() (v int64) {
	return p.Id
}

var UpdateProductReq_Name_DEFAULT string

func (p *UpdateProductReq) GetName() (v string) {
	if !p.IsSetName() {
		return UpdateProductReq_Name_DEFAULT
	}
	return *p.Name
}

var UpdateProductReq_Avatar_DEFAULT string

func (p *UpdateProductReq) GetAvatar() (v string) {
	if !p.IsSetAvatar() {
		return UpdateProductReq_Avatar_DEFAULT
	}
	return *p.Avatar
}

var UpdateProductReq_Category_DEFAULT string

func (p *UpdateProductReq) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return UpdateProductReq_Category_DEFAULT
	}
	return *p.Category
}

var UpdateProductReq_Price_DEFAULT float64

func (p *UpdateProductReq) GetPrice() (v float64) {
	if !p.IsSetPrice() {
		return UpdateProductReq_Price_DEFAULT
	}
	return *p.Price
}

var UpdateProductReq_Stock_DEFAULT int32

func (p *UpdateProductReq) GetStock() (v int32) {
	if !p.IsSetStock() {
		return UpdateProductReq_Stock_DEFAULT
	}
	return *p.Stock
}

var UpdateProductReq_Status_DEFAULT ProductStatus

func (p *UpdateProductReq) GetStatus() (v ProductStatus) {
	if !p.IsSetStatus() {
		return UpdateProductReq_Status_DEFAULT
	}
	return *p.Status
}

var UpdateProductReq_Brand_DEFAULT string

func (p *UpdateProductReq) GetBrand() (v string) {
	if !p.IsSetBrand() {
		return UpdateProductReq_Brand_DEFAULT
	}
	return *p.Brand
}
func (p *UpdateProductReq) SetId(val int64) {
	p.Id = val
}
func (p *UpdateProductReq) SetName(val *string) {
	p.Name = val
}
func (p *UpdateProductReq) SetAvatar(val *string) {
	p.Avatar = val
}
func (p *UpdateProductReq) SetCategory(val *string) {
	p.Category = val
}
func (p *UpdateProductReq) SetPrice(val *float64) {
	p.Price = val
}
func (p *UpdateProductReq) SetStock(val *int32) {
	p.Stock = val
}
func (p *UpdateProductReq) SetStatus(val *ProductStatus) {
	p.Status = val
}
func (p *UpdateProductReq) SetBrand(val *string) {
	p.Brand = val
}

func (p *UpdateProductReq) IsSetName() bool {
	return p.Name != nil
}

func (p *UpdateProductReq) IsSetAvatar() bool {
	return p.Avatar != nil
}

func (p *UpdateProductReq) IsSetCategory() bool {
	return p.Category != nil
}

func (p *UpdateProductReq) IsSetPrice() bool {
	return p.Price != nil
}

func (p *UpdateProductReq) IsSetStock() bool {
	return p.Stock != nil
}

func (p *UpdateProductReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *UpdateProductReq) IsSetBrand() bool {
	return p.Brand != nil
}

func (p *UpdateProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProductReq(%+v)", *p)
}

var fieldIDToName_UpdateProductReq = map[int16]string{
	1: "id",
	2: "name",
	3: "avatar",
	4: "category",
	5: "price",
	6: "stock",
	7: "status",
	8: "brand",
}

type UpdateProductResp struct {
	Success bool     `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32    `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string  `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Product *Product `thrift:"product,4" frugal:"4,default,Product" json:"product"`
}

func NewUpdateProductResp() *UpdateProductResp {
	return &UpdateProductResp{
		Code: 0,
	}
}

func (p *UpdateProductResp) InitDefault() {
	p.Code = 0
}

func (p *UpdateProductResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateProductResp) GetCode() (v int32) {
	return p.Code
}

var UpdateProductResp_Message_DEFAULT string

func (p *UpdateProductResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return UpdateProductResp_Message_DEFAULT
	}
	return *p.Message
}

var UpdateProductResp_Product_DEFAULT *Product

func (p *UpdateProductResp) GetProduct() (v *Product) {
	if !p.IsSetProduct() {
		return UpdateProductResp_Product_DEFAULT
	}
	return p.Product
}
func (p *UpdateProductResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateProductResp) SetCode(val int32) {
	p.Code = val
}
func (p *UpdateProductResp) SetMessage(val *string) {
	p.Message = val
}
func (p *UpdateProductResp) SetProduct(val *Product) {
	p.Product = val
}

func (p *UpdateProductResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *UpdateProductResp) IsSetProduct() bool {
	return p.Product != nil
}

func (p *UpdateProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProductResp(%+v)", *p)
}

var fieldIDToName_UpdateProductResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "product",
}

type DeleteProductReq struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewDeleteProductReq() *DeleteProductReq {
	return &DeleteProductReq{}
}

func (p *DeleteProductReq) InitDefault() {
}

func (p *DeleteProductReq) GetId() (v int64) {
	return p.Id
}
func (p *DeleteProductReq) SetId(val int64) {
	p.Id = val
}

func (p *DeleteProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteProductReq(%+v)", *p)
}

var fieldIDToName_DeleteProductReq = map[int16]string{
	1: "id",
}

type DeleteProductResp struct {
	Success bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32   `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
}

func NewDeleteProductResp() *DeleteProductResp {
	return &DeleteProductResp{
		Code: 0,
	}
}

func (p *DeleteProductResp) InitDefault() {
	p.Code = 0
}

func (p *DeleteProductResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *DeleteProductResp) GetCode() (v int32) {
	return p.Code
}

var DeleteProductResp_Message_DEFAULT string

func (p *DeleteProductResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return DeleteProductResp_Message_DEFAULT
	}
	return *p.Message
}
func (p *DeleteProductResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeleteProductResp) SetCode(val int32) {
	p.Code = val
}
func (p *DeleteProductResp) SetMessage(val *string) {
	p.Message = val
}

func (p *DeleteProductResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *DeleteProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteProductResp(%+v)", *p)
}

var fieldIDToName_DeleteProductResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
}

type OnlineProductReq struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewOnlineProductReq() *OnlineProductReq {
	return &OnlineProductReq{}
}

func (p *OnlineProductReq) InitDefault() {
}

func (p *OnlineProductReq) GetId() (v int64) {
	return p.Id
}
func (p *OnlineProductReq) SetId(val int64) {
	p.Id = val
}

func (p *OnlineProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OnlineProductReq(%+v)", *p)
}

var fieldIDToName_OnlineProductReq = map[int16]string{
	1: "id",
}

type OnlineProductResp struct {
	Success    bool          `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32         `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    *string       `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	OldStatus  ProductStatus `thrift:"oldStatus,4" frugal:"4,default,ProductStatus" json:"oldStatus"`
	NewStatus_ ProductStatus `thrift:"newStatus,5" frugal:"5,default,ProductStatus" json:"newStatus"`
	OperatedAt int64         `thrift:"operatedAt,6" frugal:"6,default,i64" json:"operatedAt"`
}

func NewOnlineProductResp() *OnlineProductResp {
	return &OnlineProductResp{
		Code: 0,
	}
}

func (p *OnlineProductResp) InitDefault() {
	p.Code = 0
}

func (p *OnlineProductResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OnlineProductResp) GetCode() (v int32) {
	return p.Code
}

var OnlineProductResp_Message_DEFAULT string

func (p *OnlineProductResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return OnlineProductResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *OnlineProductResp) GetOldStatus() (v ProductStatus) {
	return p.OldStatus
}

func (p *OnlineProductResp) GetNewStatus_() (v ProductStatus) {
	return p.NewStatus_
}

func (p *OnlineProductResp) GetOperatedAt() (v int64) {
	return p.OperatedAt
}
func (p *OnlineProductResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OnlineProductResp) SetCode(val int32) {
	p.Code = val
}
func (p *OnlineProductResp) SetMessage(val *string) {
	p.Message = val
}
func (p *OnlineProductResp) SetOldStatus(val ProductStatus) {
	p.OldStatus = val
}
func (p *OnlineProductResp) SetNewStatus_(val ProductStatus) {
	p.NewStatus_ = val
}
func (p *OnlineProductResp) SetOperatedAt(val int64) {
	p.OperatedAt = val
}

func (p *OnlineProductResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *OnlineProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OnlineProductResp(%+v)", *p)
}

var fieldIDToName_OnlineProductResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "oldStatus",
	5: "newStatus",
	6: "operatedAt",
}

type OfflineProductReq struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewOfflineProductReq() *OfflineProductReq {
	return &OfflineProductReq{}
}

func (p *OfflineProductReq) InitDefault() {
}

func (p *OfflineProductReq) GetId() (v int64) {
	return p.Id
}
func (p *OfflineProductReq) SetId(val int64) {
	p.Id = val
}

func (p *OfflineProductReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OfflineProductReq(%+v)", *p)
}

var fieldIDToName_OfflineProductReq = map[int16]string{
	1: "id",
}

type OfflineProductResp struct {
	Success    bool          `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32         `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    *string       `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	OldStatus  ProductStatus `thrift:"oldStatus,4" frugal:"4,default,ProductStatus" json:"oldStatus"`
	NewStatus_ ProductStatus `thrift:"newStatus,5" frugal:"5,default,ProductStatus" json:"newStatus"`
	OperatedAt int64         `thrift:"operatedAt,6" frugal:"6,default,i64" json:"operatedAt"`
}

func NewOfflineProductResp() *OfflineProductResp {
	return &OfflineProductResp{
		Code: 0,
	}
}

func (p *OfflineProductResp) InitDefault() {
	p.Code = 0
}

func (p *OfflineProductResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *OfflineProductResp) GetCode() (v int32) {
	return p.Code
}

var OfflineProductResp_Message_DEFAULT string

func (p *OfflineProductResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return OfflineProductResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *OfflineProductResp) GetOldStatus() (v ProductStatus) {
	return p.OldStatus
}

func (p *OfflineProductResp) GetNewStatus_() (v ProductStatus) {
	return p.NewStatus_
}

func (p *OfflineProductResp) GetOperatedAt() (v int64) {
	return p.OperatedAt
}
func (p *OfflineProductResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *OfflineProductResp) SetCode(val int32) {
	p.Code = val
}
func (p *OfflineProductResp) SetMessage(val *string) {
	p.Message = val
}
func (p *OfflineProductResp) SetOldStatus(val ProductStatus) {
	p.OldStatus = val
}
func (p *OfflineProductResp) SetNewStatus_(val ProductStatus) {
	p.NewStatus_ = val
}
func (p *OfflineProductResp) SetOperatedAt(val int64) {
	p.OperatedAt = val
}

func (p *OfflineProductResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *OfflineProductResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OfflineProductResp(%+v)", *p)
}

var fieldIDToName_OfflineProductResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "oldStatus",
	5: "newStatus",
	6: "operatedAt",
}

type UserSearchProductsReq struct {
	Category *string  `thrift:"category,1,optional" frugal:"1,optional,string" json:"category,omitempty"`
	MinPrice *float64 `thrift:"minPrice,2,optional" frugal:"2,optional,double" json:"minPrice,omitempty"`
	MaxPrice *float64 `thrift:"maxPrice,3,optional" frugal:"3,optional,double" json:"maxPrice,omitempty"`
	Keyword  *string  `thrift:"keyword,4,optional" frugal:"4,optional,string" json:"keyword,omitempty"`
	Page     int32    `thrift:"page,5" frugal:"5,default,i32" json:"page"`
	PageSize int32    `thrift:"pageSize,6" frugal:"6,default,i32" json:"pageSize"`
}

func NewUserSearchProductsReq() *UserSearchProductsReq {
	return &UserSearchProductsReq{
		Page:     1,
		PageSize: 20,
	}
}

func (p *UserSearchProductsReq) InitDefault() {
	p.Page = 1
	p.PageSize = 20
}

var UserSearchProductsReq_Category_DEFAULT string

func (p *UserSearchProductsReq) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return UserSearchProductsReq_Category_DEFAULT
	}
	return *p.Category
}

var UserSearchProductsReq_MinPrice_DEFAULT float64

func (p *UserSearchProductsReq) GetMinPrice() (v float64) {
	if !p.IsSetMinPrice() {
		return UserSearchProductsReq_MinPrice_DEFAULT
	}
	return *p.MinPrice
}

var UserSearchProductsReq_MaxPrice_DEFAULT float64

func (p *UserSearchProductsReq) GetMaxPrice() (v float64) {
	if !p.IsSetMaxPrice() {
		return UserSearchProductsReq_MaxPrice_DEFAULT
	}
	return *p.MaxPrice
}

var UserSearchProductsReq_Keyword_DEFAULT string

func (p *UserSearchProductsReq) GetKeyword() (v string) {
	if !p.IsSetKeyword() {
		return UserSearchProductsReq_Keyword_DEFAULT
	}
	return *p.Keyword
}

func (p *UserSearchProductsReq) GetPage() (v int32) {
	return p.Page
}

func (p *UserSearchProductsReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *UserSearchProductsReq) SetCategory(val *string) {
	p.Category = val
}
func (p *UserSearchProductsReq) SetMinPrice(val *float64) {
	p.MinPrice = val
}
func (p *UserSearchProductsReq) SetMaxPrice(val *float64) {
	p.MaxPrice = val
}
func (p *UserSearchProductsReq) SetKeyword(val *string) {
	p.Keyword = val
}
func (p *UserSearchProductsReq) SetPage(val int32) {
	p.Page = val
}
func (p *UserSearchProductsReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *UserSearchProductsReq) IsSetCategory() bool {
	return p.Category != nil
}

func (p *UserSearchProductsReq) IsSetMinPrice() bool {
	return p.MinPrice != nil
}

func (p *UserSearchProductsReq) IsSetMaxPrice() bool {
	return p.MaxPrice != nil
}

func (p *UserSearchProductsReq) IsSetKeyword() bool {
	return p.Keyword != nil
}

func (p *UserSearchProductsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSearchProductsReq(%+v)", *p)
}

var fieldIDToName_UserSearchProductsReq = map[int16]string{
	1: "category",
	2: "minPrice",
	3: "maxPrice",
	4: "keyword",
	5: "page",
	6: "pageSize",
}

type UserSearchProductsResp struct {
	Success  bool             `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code     int32            `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message  *string          `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Total    int32            `thrift:"total,4" frugal:"4,default,i32" json:"total"`
	Page     int32            `thrift:"page,5" frugal:"5,default,i32" json:"page"`
	PageSize int32            `thrift:"pageSize,6" frugal:"6,default,i32" json:"pageSize"`
	Products []*SimpleProduct `thrift:"products,7" frugal:"7,default,list<SimpleProduct>" json:"products"`
}

func NewUserSearchProductsResp() *UserSearchProductsResp {
	return &UserSearchProductsResp{
		Code: 0,
	}
}

func (p *UserSearchProductsResp) InitDefault() {
	p.Code = 0
}

func (p *UserSearchProductsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UserSearchProductsResp) GetCode() (v int32) {
	return p.Code
}

var UserSearchProductsResp_Message_DEFAULT string

func (p *UserSearchProductsResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return UserSearchProductsResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *UserSearchProductsResp) GetTotal() (v int32) {
	return p.Total
}

func (p *UserSearchProductsResp) GetPage() (v int32) {
	return p.Page
}

func (p *UserSearchProductsResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *UserSearchProductsResp) GetProducts() (v []*SimpleProduct) {
	return p.Products
}
func (p *UserSearchProductsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UserSearchProductsResp) SetCode(val int32) {
	p.Code = val
}
func (p *UserSearchProductsResp) SetMessage(val *string) {
	p.Message = val
}
func (p *UserSearchProductsResp) SetTotal(val int32) {
	p.Total = val
}
func (p *UserSearchProductsResp) SetPage(val int32) {
	p.Page = val
}
func (p *UserSearchProductsResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *UserSearchProductsResp) SetProducts(val []*SimpleProduct) {
	p.Products = val
}

func (p *UserSearchProductsResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *UserSearchProductsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSearchProductsResp(%+v)", *p)
}

var fieldIDToName_UserSearchProductsResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "total",
	5: "page",
	6: "pageSize",
	7: "products",
}

type AdminSearchProductsReq struct {
	Id       *int64   `thrift:"id,1,optional" frugal:"1,optional,i64" json:"id,omitempty"`
	Category *string  `thrift:"category,2,optional" frugal:"2,optional,string" json:"category,omitempty"`
	MinPrice *float64 `thrift:"minPrice,3,optional" frugal:"3,optional,double" json:"minPrice,omitempty"`
	MaxPrice *float64 `thrift:"maxPrice,4,optional" frugal:"4,optional,double" json:"maxPrice,omitempty"`
	Keyword  *string  `thrift:"keyword,5,optional" frugal:"5,optional,string" json:"keyword,omitempty"`
	Page     int32    `thrift:"page,6" frugal:"6,default,i32" json:"page"`
	PageSize int32    `thrift:"pageSize,7" frugal:"7,default,i32" json:"pageSize"`
}

func NewAdminSearchProductsReq() *AdminSearchProductsReq {
	return &AdminSearchProductsReq{
		Page:     1,
		PageSize: 20,
	}
}

func (p *AdminSearchProductsReq) InitDefault() {
	p.Page = 1
	p.PageSize = 20
}

var AdminSearchProductsReq_Id_DEFAULT int64

func (p *AdminSearchProductsReq) GetId() (v int64) {
	if !p.IsSetId() {
		return AdminSearchProductsReq_Id_DEFAULT
	}
	return *p.Id
}

var AdminSearchProductsReq_Category_DEFAULT string

func (p *AdminSearchProductsReq) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return AdminSearchProductsReq_Category_DEFAULT
	}
	return *p.Category
}

var AdminSearchProductsReq_MinPrice_DEFAULT float64

func (p *AdminSearchProductsReq) GetMinPrice() (v float64) {
	if !p.IsSetMinPrice() {
		return AdminSearchProductsReq_MinPrice_DEFAULT
	}
	return *p.MinPrice
}

var AdminSearchProductsReq_MaxPrice_DEFAULT float64

func (p *AdminSearchProductsReq) GetMaxPrice() (v float64) {
	if !p.IsSetMaxPrice() {
		return AdminSearchProductsReq_MaxPrice_DEFAULT
	}
	return *p.MaxPrice
}

var AdminSearchProductsReq_Keyword_DEFAULT string

func (p *AdminSearchProductsReq) GetKeyword() (v string) {
	if !p.IsSetKeyword() {
		return AdminSearchProductsReq_Keyword_DEFAULT
	}
	return *p.Keyword
}

func (p *AdminSearchProductsReq) GetPage() (v int32) {
	return p.Page
}

func (p *AdminSearchProductsReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *AdminSearchProductsReq) SetId(val *int64) {
	p.Id = val
}
func (p *AdminSearchProductsReq) SetCategory(val *string) {
	p.Category = val
}
func (p *AdminSearchProductsReq) SetMinPrice(val *float64) {
	p.MinPrice = val
}
func (p *AdminSearchProductsReq) SetMaxPrice(val *float64) {
	p.MaxPrice = val
}
func (p *AdminSearchProductsReq) SetKeyword(val *string) {
	p.Keyword = val
}
func (p *AdminSearchProductsReq) SetPage(val int32) {
	p.Page = val
}
func (p *AdminSearchProductsReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *AdminSearchProductsReq) IsSetId() bool {
	return p.Id != nil
}

func (p *AdminSearchProductsReq) IsSetCategory() bool {
	return p.Category != nil
}

func (p *AdminSearchProductsReq) IsSetMinPrice() bool {
	return p.MinPrice != nil
}

func (p *AdminSearchProductsReq) IsSetMaxPrice() bool {
	return p.MaxPrice != nil
}

func (p *AdminSearchProductsReq) IsSetKeyword() bool {
	return p.Keyword != nil
}

func (p *AdminSearchProductsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdminSearchProductsReq(%+v)", *p)
}

var fieldIDToName_AdminSearchProductsReq = map[int16]string{
	1: "id",
	2: "category",
	3: "minPrice",
	4: "maxPrice",
	5: "keyword",
	6: "page",
	7: "pageSize",
}

type AdminSearchProductsResp struct {
	Success  bool       `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code     int32      `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message  *string    `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Total    int32      `thrift:"total,4" frugal:"4,default,i32" json:"total"`
	Page     int32      `thrift:"page,5" frugal:"5,default,i32" json:"page"`
	PageSize int32      `thrift:"pageSize,6" frugal:"6,default,i32" json:"pageSize"`
	Products []*Product `thrift:"products,7" frugal:"7,default,list<Product>" json:"products"`
}

func NewAdminSearchProductsResp() *AdminSearchProductsResp {
	return &AdminSearchProductsResp{
		Code: 0,
	}
}

func (p *AdminSearchProductsResp) InitDefault() {
	p.Code = 0
}

func (p *AdminSearchProductsResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *AdminSearchProductsResp) GetCode() (v int32) {
	return p.Code
}

var AdminSearchProductsResp_Message_DEFAULT string

func (p *AdminSearchProductsResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return AdminSearchProductsResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *AdminSearchProductsResp) GetTotal() (v int32) {
	return p.Total
}

func (p *AdminSearchProductsResp) GetPage() (v int32) {
	return p.Page
}

func (p *AdminSearchProductsResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *AdminSearchProductsResp) GetProducts() (v []*Product) {
	return p.Products
}
func (p *AdminSearchProductsResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *AdminSearchProductsResp) SetCode(val int32) {
	p.Code = val
}
func (p *AdminSearchProductsResp) SetMessage(val *string) {
	p.Message = val
}
func (p *AdminSearchProductsResp) SetTotal(val int32) {
	p.Total = val
}
func (p *AdminSearchProductsResp) SetPage(val int32) {
	p.Page = val
}
func (p *AdminSearchProductsResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *AdminSearchProductsResp) SetProducts(val []*Product) {
	p.Products = val
}

func (p *AdminSearchProductsResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *AdminSearchProductsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AdminSearchProductsResp(%+v)", *p)
}

var fieldIDToName_AdminSearchProductsResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "total",
	5: "page",
	6: "pageSize",
	7: "products",
}

type ProductService interface {
	CreateProduct(ctx context.Context, req *CreateProductReq) (r *CreateProductResp, err error)

	GetProduct(ctx context.Context, req *GetProductReq) (r *GetProductResp, err error)

	UpdateProduct(ctx context.Context, req *UpdateProductReq) (r *UpdateProductResp, err error)

	OnlineProduct(ctx context.Context, req *OnlineProductReq) (r *OnlineProductResp, err error)

	OfflineProduct(ctx context.Context, req *OfflineProductReq) (r *OfflineProductResp, err error)

	DeleteProduct(ctx context.Context, req *DeleteProductReq) (r *DeleteProductResp, err error)

	UserSearchProducts(ctx context.Context, req *UserSearchProductsReq) (r *UserSearchProductsResp, err error)

	AdminSearchProducts(ctx context.Context, req *AdminSearchProductsReq) (r *AdminSearchProductsResp, err error)
}

type ProductServiceCreateProductArgs struct {
	Req *CreateProductReq `thrift:"req,1" frugal:"1,default,CreateProductReq" json:"req"`
}

func NewProductServiceCreateProductArgs() *ProductServiceCreateProductArgs {
	return &ProductServiceCreateProductArgs{}
}

func (p *ProductServiceCreateProductArgs) InitDefault() {
}

var ProductServiceCreateProductArgs_Req_DEFAULT *CreateProductReq

func (p *ProductServiceCreateProductArgs) GetReq() (v *CreateProductReq) {
	if !p.IsSetReq() {
		return ProductServiceCreateProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceCreateProductArgs) SetReq(val *CreateProductReq) {
	p.Req = val
}

func (p *ProductServiceCreateProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceCreateProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceCreateProductResult struct {
	Success *CreateProductResp `thrift:"success,0,optional" frugal:"0,optional,CreateProductResp" json:"success,omitempty"`
}

func NewProductServiceCreateProductResult() *ProductServiceCreateProductResult {
	return &ProductServiceCreateProductResult{}
}

func (p *ProductServiceCreateProductResult) InitDefault() {
}

var ProductServiceCreateProductResult_Success_DEFAULT *CreateProductResp

func (p *ProductServiceCreateProductResult) GetSuccess() (v *CreateProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceCreateProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceCreateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateProductResp)
}

func (p *ProductServiceCreateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceCreateProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceCreateProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceCreateProductResult = map[int16]string{
	0: "success",
}

type ProductServiceGetProductArgs struct {
	Req *GetProductReq `thrift:"req,1" frugal:"1,default,GetProductReq" json:"req"`
}

func NewProductServiceGetProductArgs() *ProductServiceGetProductArgs {
	return &ProductServiceGetProductArgs{}
}

func (p *ProductServiceGetProductArgs) InitDefault() {
}

var ProductServiceGetProductArgs_Req_DEFAULT *GetProductReq

func (p *ProductServiceGetProductArgs) GetReq() (v *GetProductReq) {
	if !p.IsSetReq() {
		return ProductServiceGetProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceGetProductArgs) SetReq(val *GetProductReq) {
	p.Req = val
}

func (p *ProductServiceGetProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceGetProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceGetProductResult struct {
	Success *GetProductResp `thrift:"success,0,optional" frugal:"0,optional,GetProductResp" json:"success,omitempty"`
}

func NewProductServiceGetProductResult() *ProductServiceGetProductResult {
	return &ProductServiceGetProductResult{}
}

func (p *ProductServiceGetProductResult) InitDefault() {
}

var ProductServiceGetProductResult_Success_DEFAULT *GetProductResp

func (p *ProductServiceGetProductResult) GetSuccess() (v *GetProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceGetProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceGetProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetProductResp)
}

func (p *ProductServiceGetProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceGetProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceGetProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceGetProductResult = map[int16]string{
	0: "success",
}

type ProductServiceUpdateProductArgs struct {
	Req *UpdateProductReq `thrift:"req,1" frugal:"1,default,UpdateProductReq" json:"req"`
}

func NewProductServiceUpdateProductArgs() *ProductServiceUpdateProductArgs {
	return &ProductServiceUpdateProductArgs{}
}

func (p *ProductServiceUpdateProductArgs) InitDefault() {
}

var ProductServiceUpdateProductArgs_Req_DEFAULT *UpdateProductReq

func (p *ProductServiceUpdateProductArgs) GetReq() (v *UpdateProductReq) {
	if !p.IsSetReq() {
		return ProductServiceUpdateProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceUpdateProductArgs) SetReq(val *UpdateProductReq) {
	p.Req = val
}

func (p *ProductServiceUpdateProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceUpdateProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceUpdateProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceUpdateProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceUpdateProductResult struct {
	Success *UpdateProductResp `thrift:"success,0,optional" frugal:"0,optional,UpdateProductResp" json:"success,omitempty"`
}

func NewProductServiceUpdateProductResult() *ProductServiceUpdateProductResult {
	return &ProductServiceUpdateProductResult{}
}

func (p *ProductServiceUpdateProductResult) InitDefault() {
}

var ProductServiceUpdateProductResult_Success_DEFAULT *UpdateProductResp

func (p *ProductServiceUpdateProductResult) GetSuccess() (v *UpdateProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceUpdateProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceUpdateProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateProductResp)
}

func (p *ProductServiceUpdateProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceUpdateProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceUpdateProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceUpdateProductResult = map[int16]string{
	0: "success",
}

type ProductServiceOnlineProductArgs struct {
	Req *OnlineProductReq `thrift:"req,1" frugal:"1,default,OnlineProductReq" json:"req"`
}

func NewProductServiceOnlineProductArgs() *ProductServiceOnlineProductArgs {
	return &ProductServiceOnlineProductArgs{}
}

func (p *ProductServiceOnlineProductArgs) InitDefault() {
}

var ProductServiceOnlineProductArgs_Req_DEFAULT *OnlineProductReq

func (p *ProductServiceOnlineProductArgs) GetReq() (v *OnlineProductReq) {
	if !p.IsSetReq() {
		return ProductServiceOnlineProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceOnlineProductArgs) SetReq(val *OnlineProductReq) {
	p.Req = val
}

func (p *ProductServiceOnlineProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceOnlineProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceOnlineProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceOnlineProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceOnlineProductResult struct {
	Success *OnlineProductResp `thrift:"success,0,optional" frugal:"0,optional,OnlineProductResp" json:"success,omitempty"`
}

func NewProductServiceOnlineProductResult() *ProductServiceOnlineProductResult {
	return &ProductServiceOnlineProductResult{}
}

func (p *ProductServiceOnlineProductResult) InitDefault() {
}

var ProductServiceOnlineProductResult_Success_DEFAULT *OnlineProductResp

func (p *ProductServiceOnlineProductResult) GetSuccess() (v *OnlineProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceOnlineProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceOnlineProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*OnlineProductResp)
}

func (p *ProductServiceOnlineProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceOnlineProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceOnlineProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceOnlineProductResult = map[int16]string{
	0: "success",
}

type ProductServiceOfflineProductArgs struct {
	Req *OfflineProductReq `thrift:"req,1" frugal:"1,default,OfflineProductReq" json:"req"`
}

func NewProductServiceOfflineProductArgs() *ProductServiceOfflineProductArgs {
	return &ProductServiceOfflineProductArgs{}
}

func (p *ProductServiceOfflineProductArgs) InitDefault() {
}

var ProductServiceOfflineProductArgs_Req_DEFAULT *OfflineProductReq

func (p *ProductServiceOfflineProductArgs) GetReq() (v *OfflineProductReq) {
	if !p.IsSetReq() {
		return ProductServiceOfflineProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceOfflineProductArgs) SetReq(val *OfflineProductReq) {
	p.Req = val
}

func (p *ProductServiceOfflineProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceOfflineProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceOfflineProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceOfflineProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceOfflineProductResult struct {
	Success *OfflineProductResp `thrift:"success,0,optional" frugal:"0,optional,OfflineProductResp" json:"success,omitempty"`
}

func NewProductServiceOfflineProductResult() *ProductServiceOfflineProductResult {
	return &ProductServiceOfflineProductResult{}
}

func (p *ProductServiceOfflineProductResult) InitDefault() {
}

var ProductServiceOfflineProductResult_Success_DEFAULT *OfflineProductResp

func (p *ProductServiceOfflineProductResult) GetSuccess() (v *OfflineProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceOfflineProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceOfflineProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*OfflineProductResp)
}

func (p *ProductServiceOfflineProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceOfflineProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceOfflineProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceOfflineProductResult = map[int16]string{
	0: "success",
}

type ProductServiceDeleteProductArgs struct {
	Req *DeleteProductReq `thrift:"req,1" frugal:"1,default,DeleteProductReq" json:"req"`
}

func NewProductServiceDeleteProductArgs() *ProductServiceDeleteProductArgs {
	return &ProductServiceDeleteProductArgs{}
}

func (p *ProductServiceDeleteProductArgs) InitDefault() {
}

var ProductServiceDeleteProductArgs_Req_DEFAULT *DeleteProductReq

func (p *ProductServiceDeleteProductArgs) GetReq() (v *DeleteProductReq) {
	if !p.IsSetReq() {
		return ProductServiceDeleteProductArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceDeleteProductArgs) SetReq(val *DeleteProductReq) {
	p.Req = val
}

func (p *ProductServiceDeleteProductArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceDeleteProductArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceDeleteProductArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceDeleteProductArgs = map[int16]string{
	1: "req",
}

type ProductServiceDeleteProductResult struct {
	Success *DeleteProductResp `thrift:"success,0,optional" frugal:"0,optional,DeleteProductResp" json:"success,omitempty"`
}

func NewProductServiceDeleteProductResult() *ProductServiceDeleteProductResult {
	return &ProductServiceDeleteProductResult{}
}

func (p *ProductServiceDeleteProductResult) InitDefault() {
}

var ProductServiceDeleteProductResult_Success_DEFAULT *DeleteProductResp

func (p *ProductServiceDeleteProductResult) GetSuccess() (v *DeleteProductResp) {
	if !p.IsSetSuccess() {
		return ProductServiceDeleteProductResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceDeleteProductResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteProductResp)
}

func (p *ProductServiceDeleteProductResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceDeleteProductResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceDeleteProductResult(%+v)", *p)
}

var fieldIDToName_ProductServiceDeleteProductResult = map[int16]string{
	0: "success",
}

type ProductServiceUserSearchProductsArgs struct {
	Req *UserSearchProductsReq `thrift:"req,1" frugal:"1,default,UserSearchProductsReq" json:"req"`
}

func NewProductServiceUserSearchProductsArgs() *ProductServiceUserSearchProductsArgs {
	return &ProductServiceUserSearchProductsArgs{}
}

func (p *ProductServiceUserSearchProductsArgs) InitDefault() {
}

var ProductServiceUserSearchProductsArgs_Req_DEFAULT *UserSearchProductsReq

func (p *ProductServiceUserSearchProductsArgs) GetReq() (v *UserSearchProductsReq) {
	if !p.IsSetReq() {
		return ProductServiceUserSearchProductsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceUserSearchProductsArgs) SetReq(val *UserSearchProductsReq) {
	p.Req = val
}

func (p *ProductServiceUserSearchProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceUserSearchProductsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceUserSearchProductsArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceUserSearchProductsArgs = map[int16]string{
	1: "req",
}

type ProductServiceUserSearchProductsResult struct {
	Success *UserSearchProductsResp `thrift:"success,0,optional" frugal:"0,optional,UserSearchProductsResp" json:"success,omitempty"`
}

func NewProductServiceUserSearchProductsResult() *ProductServiceUserSearchProductsResult {
	return &ProductServiceUserSearchProductsResult{}
}

func (p *ProductServiceUserSearchProductsResult) InitDefault() {
}

var ProductServiceUserSearchProductsResult_Success_DEFAULT *UserSearchProductsResp

func (p *ProductServiceUserSearchProductsResult) GetSuccess() (v *UserSearchProductsResp) {
	if !p.IsSetSuccess() {
		return ProductServiceUserSearchProductsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceUserSearchProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*UserSearchProductsResp)
}

func (p *ProductServiceUserSearchProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceUserSearchProductsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceUserSearchProductsResult(%+v)", *p)
}

var fieldIDToName_ProductServiceUserSearchProductsResult = map[int16]string{
	0: "success",
}

type ProductServiceAdminSearchProductsArgs struct {
	Req *AdminSearchProductsReq `thrift:"req,1" frugal:"1,default,AdminSearchProductsReq" json:"req"`
}

func NewProductServiceAdminSearchProductsArgs() *ProductServiceAdminSearchProductsArgs {
	return &ProductServiceAdminSearchProductsArgs{}
}

func (p *ProductServiceAdminSearchProductsArgs) InitDefault() {
}

var ProductServiceAdminSearchProductsArgs_Req_DEFAULT *AdminSearchProductsReq

func (p *ProductServiceAdminSearchProductsArgs) GetReq() (v *AdminSearchProductsReq) {
	if !p.IsSetReq() {
		return ProductServiceAdminSearchProductsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProductServiceAdminSearchProductsArgs) SetReq(val *AdminSearchProductsReq) {
	p.Req = val
}

func (p *ProductServiceAdminSearchProductsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProductServiceAdminSearchProductsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceAdminSearchProductsArgs(%+v)", *p)
}

var fieldIDToName_ProductServiceAdminSearchProductsArgs = map[int16]string{
	1: "req",
}

type ProductServiceAdminSearchProductsResult struct {
	Success *AdminSearchProductsResp `thrift:"success,0,optional" frugal:"0,optional,AdminSearchProductsResp" json:"success,omitempty"`
}

func NewProductServiceAdminSearchProductsResult() *ProductServiceAdminSearchProductsResult {
	return &ProductServiceAdminSearchProductsResult{}
}

func (p *ProductServiceAdminSearchProductsResult) InitDefault() {
}

var ProductServiceAdminSearchProductsResult_Success_DEFAULT *AdminSearchProductsResp

func (p *ProductServiceAdminSearchProductsResult) GetSuccess() (v *AdminSearchProductsResp) {
	if !p.IsSetSuccess() {
		return ProductServiceAdminSearchProductsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProductServiceAdminSearchProductsResult) SetSuccess(x interface{}) {
	p.Success = x.(*AdminSearchProductsResp)
}

func (p *ProductServiceAdminSearchProductsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProductServiceAdminSearchProductsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProductServiceAdminSearchProductsResult(%+v)", *p)
}

var fieldIDToName_ProductServiceAdminSearchProductsResult = map[int16]string{
	0: "success",
}
