// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package api

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type OrderStatus int64

const (
	OrderStatus_UNPAID    OrderStatus = 0
	OrderStatus_PAID      OrderStatus = 1
	OrderStatus_SHIPPED   OrderStatus = 2
	OrderStatus_COMPLETED OrderStatus = 3
	OrderStatus_CANCELLED OrderStatus = 4
)

func (p OrderStatus) String() string {
	switch p {
	case OrderStatus_UNPAID:
		return "UNPAID"
	case OrderStatus_PAID:
		return "PAID"
	case OrderStatus_SHIPPED:
		return "SHIPPED"
	case OrderStatus_COMPLETED:
		return "COMPLETED"
	case OrderStatus_CANCELLED:
		return "CANCELLED"
	}
	return "<UNSET>"
}

func OrderStatusFromString(s string) (OrderStatus, error) {
	switch s {
	case "UNPAID":
		return OrderStatus_UNPAID, nil
	case "PAID":
		return OrderStatus_PAID, nil
	case "SHIPPED":
		return OrderStatus_SHIPPED, nil
	case "COMPLETED":
		return OrderStatus_COMPLETED, nil
	case "CANCELLED":
		return OrderStatus_CANCELLED, nil
	}
	return OrderStatus(0), fmt.Errorf("not a valid OrderStatus string")
}

func OrderStatusPtr(v OrderStatus) *OrderStatus { return &v }
func (p *OrderStatus) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = OrderStatus(result.Int64)
	return
}

func (p *OrderStatus) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type OrderItem struct {
	ProductId   int64   `thrift:"productId,1" frugal:"1,default,i64" json:"productId"`
	ProductName string  `thrift:"productName,2" frugal:"2,default,string" json:"productName"`
	Quantity    int32   `thrift:"quantity,3" frugal:"3,default,i32" json:"quantity"`
	Price       float64 `thrift:"price,4" frugal:"4,default,double" json:"price"`
}

func NewOrderItem() *OrderItem {
	return &OrderItem{}
}

func (p *OrderItem) InitDefault() {
}

func (p *OrderItem) GetProductId() (v int64) {
	return p.ProductId
}

func (p *OrderItem) GetProductName() (v string) {
	return p.ProductName
}

func (p *OrderItem) GetQuantity() (v int32) {
	return p.Quantity
}

func (p *OrderItem) GetPrice() (v float64) {
	return p.Price
}
func (p *OrderItem) SetProductId(val int64) {
	p.ProductId = val
}
func (p *OrderItem) SetProductName(val string) {
	p.ProductName = val
}
func (p *OrderItem) SetQuantity(val int32) {
	p.Quantity = val
}
func (p *OrderItem) SetPrice(val float64) {
	p.Price = val
}

func (p *OrderItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderItem(%+v)", *p)
}

var fieldIDToName_OrderItem = map[int16]string{
	1: "productId",
	2: "productName",
	3: "quantity",
	4: "price",
}

type Order struct {
	OrderId     int64        `thrift:"orderId,1" frugal:"1,default,i64" json:"orderId"`
	OrderNo     string       `thrift:"orderNo,2" frugal:"2,default,string" json:"orderNo"`
	UserId      int64        `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	TotalAmount float64      `thrift:"totalAmount,4" frugal:"4,default,double" json:"totalAmount"`
	Status      OrderStatus  `thrift:"status,5" frugal:"5,default,OrderStatus" json:"status"`
	Items       []*OrderItem `thrift:"items,6" frugal:"6,default,list<OrderItem>" json:"items"`
	CreatedAt   int64        `thrift:"createdAt,7" frugal:"7,default,i64" json:"createdAt"`
	Receiver    string       `thrift:"receiver,8" frugal:"8,default,string" json:"receiver"`
	Phone       string       `thrift:"phone,9" frugal:"9,default,string" json:"phone"`
	Address     string       `thrift:"address,10" frugal:"10,default,string" json:"address"`
}

func NewOrder() *Order {
	return &Order{}
}

func (p *Order) InitDefault() {
}

func (p *Order) GetOrderId() (v int64) {
	return p.OrderId
}

func (p *Order) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *Order) GetUserId() (v int64) {
	return p.UserId
}

func (p *Order) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

func (p *Order) GetStatus() (v OrderStatus) {
	return p.Status
}

func (p *Order) GetItems() (v []*OrderItem) {
	return p.Items
}

func (p *Order) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *Order) GetReceiver() (v string) {
	return p.Receiver
}

func (p *Order) GetPhone() (v string) {
	return p.Phone
}

func (p *Order) GetAddress() (v string) {
	return p.Address
}
func (p *Order) SetOrderId(val int64) {
	p.OrderId = val
}
func (p *Order) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *Order) SetUserId(val int64) {
	p.UserId = val
}
func (p *Order) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *Order) SetStatus(val OrderStatus) {
	p.Status = val
}
func (p *Order) SetItems(val []*OrderItem) {
	p.Items = val
}
func (p *Order) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *Order) SetReceiver(val string) {
	p.Receiver = val
}
func (p *Order) SetPhone(val string) {
	p.Phone = val
}
func (p *Order) SetAddress(val string) {
	p.Address = val
}

func (p *Order) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Order(%+v)", *p)
}

var fieldIDToName_Order = map[int16]string{
	1:  "orderId",
	2:  "orderNo",
	3:  "userId",
	4:  "totalAmount",
	5:  "status",
	6:  "items",
	7:  "createdAt",
	8:  "receiver",
	9:  "phone",
	10: "address",
}

type CreateOrderReq struct {
	UserId        int64        `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Items         []*OrderItem `thrift:"items,2" frugal:"2,default,list<OrderItem>" json:"items"`
	Receiver      string       `thrift:"receiver,3" frugal:"3,default,string" json:"receiver"`
	Phone         string       `thrift:"phone,4" frugal:"4,default,string" json:"phone"`
	Address       string       `thrift:"address,5" frugal:"5,default,string" json:"address"`
	PaymentMethod string       `thrift:"paymentMethod,6" frugal:"6,default,string" json:"paymentMethod"`
}

func NewCreateOrderReq() *CreateOrderReq {
	return &CreateOrderReq{}
}

func (p *CreateOrderReq) InitDefault() {
}

func (p *CreateOrderReq) GetUserId() (v int64) {
	return p.UserId
}

func (p *CreateOrderReq) GetItems() (v []*OrderItem) {
	return p.Items
}

func (p *CreateOrderReq) GetReceiver() (v string) {
	return p.Receiver
}

func (p *CreateOrderReq) GetPhone() (v string) {
	return p.Phone
}

func (p *CreateOrderReq) GetAddress() (v string) {
	return p.Address
}

func (p *CreateOrderReq) GetPaymentMethod() (v string) {
	return p.PaymentMethod
}
func (p *CreateOrderReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateOrderReq) SetItems(val []*OrderItem) {
	p.Items = val
}
func (p *CreateOrderReq) SetReceiver(val string) {
	p.Receiver = val
}
func (p *CreateOrderReq) SetPhone(val string) {
	p.Phone = val
}
func (p *CreateOrderReq) SetAddress(val string) {
	p.Address = val
}
func (p *CreateOrderReq) SetPaymentMethod(val string) {
	p.PaymentMethod = val
}

func (p *CreateOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderReq(%+v)", *p)
}

var fieldIDToName_CreateOrderReq = map[int16]string{
	1: "userId",
	2: "items",
	3: "receiver",
	4: "phone",
	5: "address",
	6: "paymentMethod",
}

type CreateOrderResp struct {
	Success     bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code        int32   `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message     *string `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	OrderNo     string  `thrift:"orderNo,4" frugal:"4,default,string" json:"orderNo"`
	TotalAmount float64 `thrift:"totalAmount,5" frugal:"5,default,double" json:"totalAmount"`
	PaymentUrl  string  `thrift:"paymentUrl,6" frugal:"6,default,string" json:"paymentUrl"`
}

func NewCreateOrderResp() *CreateOrderResp {
	return &CreateOrderResp{
		Code: 0,
	}
}

func (p *CreateOrderResp) InitDefault() {
	p.Code = 0
}

func (p *CreateOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CreateOrderResp) GetCode() (v int32) {
	return p.Code
}

var CreateOrderResp_Message_DEFAULT string

func (p *CreateOrderResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return CreateOrderResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *CreateOrderResp) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *CreateOrderResp) GetTotalAmount() (v float64) {
	return p.TotalAmount
}

func (p *CreateOrderResp) GetPaymentUrl() (v string) {
	return p.PaymentUrl
}
func (p *CreateOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CreateOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *CreateOrderResp) SetMessage(val *string) {
	p.Message = val
}
func (p *CreateOrderResp) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *CreateOrderResp) SetTotalAmount(val float64) {
	p.TotalAmount = val
}
func (p *CreateOrderResp) SetPaymentUrl(val string) {
	p.PaymentUrl = val
}

func (p *CreateOrderResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *CreateOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateOrderResp(%+v)", *p)
}

var fieldIDToName_CreateOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "orderNo",
	5: "totalAmount",
	6: "paymentUrl",
}

type PayOrderReq struct {
	OrderNo string `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId  int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewPayOrderReq() *PayOrderReq {
	return &PayOrderReq{}
}

func (p *PayOrderReq) InitDefault() {
}

func (p *PayOrderReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *PayOrderReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *PayOrderReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *PayOrderReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *PayOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderReq(%+v)", *p)
}

var fieldIDToName_PayOrderReq = map[int16]string{
	1: "orderNo",
	2: "userId",
}

type PayOrderResp struct {
	Success    bool        `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32       `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    *string     `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	NewStatus_ OrderStatus `thrift:"newStatus,4" frugal:"4,default,OrderStatus" json:"newStatus"`
}

func NewPayOrderResp() *PayOrderResp {
	return &PayOrderResp{
		Code: 0,
	}
}

func (p *PayOrderResp) InitDefault() {
	p.Code = 0
}

func (p *PayOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *PayOrderResp) GetCode() (v int32) {
	return p.Code
}

var PayOrderResp_Message_DEFAULT string

func (p *PayOrderResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return PayOrderResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *PayOrderResp) GetNewStatus_() (v OrderStatus) {
	return p.NewStatus_
}
func (p *PayOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *PayOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *PayOrderResp) SetMessage(val *string) {
	p.Message = val
}
func (p *PayOrderResp) SetNewStatus_(val OrderStatus) {
	p.NewStatus_ = val
}

func (p *PayOrderResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *PayOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PayOrderResp(%+v)", *p)
}

var fieldIDToName_PayOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "newStatus",
}

type CancelOrderReq struct {
	OrderNo string  `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId  int64   `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
	Reason  *string `thrift:"reason,3,optional" frugal:"3,optional,string" json:"reason,omitempty"`
}

func NewCancelOrderReq() *CancelOrderReq {
	return &CancelOrderReq{}
}

func (p *CancelOrderReq) InitDefault() {
}

func (p *CancelOrderReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *CancelOrderReq) GetUserId() (v int64) {
	return p.UserId
}

var CancelOrderReq_Reason_DEFAULT string

func (p *CancelOrderReq) GetReason() (v string) {
	if !p.IsSetReason() {
		return CancelOrderReq_Reason_DEFAULT
	}
	return *p.Reason
}
func (p *CancelOrderReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *CancelOrderReq) SetUserId(val int64) {
	p.UserId = val
}
func (p *CancelOrderReq) SetReason(val *string) {
	p.Reason = val
}

func (p *CancelOrderReq) IsSetReason() bool {
	return p.Reason != nil
}

func (p *CancelOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderReq(%+v)", *p)
}

var fieldIDToName_CancelOrderReq = map[int16]string{
	1: "orderNo",
	2: "userId",
	3: "reason",
}

type CancelOrderResp struct {
	Success    bool        `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32       `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    *string     `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	NewStatus_ OrderStatus `thrift:"newStatus,4" frugal:"4,default,OrderStatus" json:"newStatus"`
}

func NewCancelOrderResp() *CancelOrderResp {
	return &CancelOrderResp{
		Code: 0,
	}
}

func (p *CancelOrderResp) InitDefault() {
	p.Code = 0
}

func (p *CancelOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *CancelOrderResp) GetCode() (v int32) {
	return p.Code
}

var CancelOrderResp_Message_DEFAULT string

func (p *CancelOrderResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return CancelOrderResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *CancelOrderResp) GetNewStatus_() (v OrderStatus) {
	return p.NewStatus_
}
func (p *CancelOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *CancelOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *CancelOrderResp) SetMessage(val *string) {
	p.Message = val
}
func (p *CancelOrderResp) SetNewStatus_(val OrderStatus) {
	p.NewStatus_ = val
}

func (p *CancelOrderResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *CancelOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CancelOrderResp(%+v)", *p)
}

var fieldIDToName_CancelOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "newStatus",
}

type GetOrderDetailReq struct {
	OrderNo string `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	UserId  int64  `thrift:"userId,2" frugal:"2,default,i64" json:"userId"`
}

func NewGetOrderDetailReq() *GetOrderDetailReq {
	return &GetOrderDetailReq{}
}

func (p *GetOrderDetailReq) InitDefault() {
}

func (p *GetOrderDetailReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *GetOrderDetailReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetOrderDetailReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *GetOrderDetailReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetOrderDetailReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderDetailReq(%+v)", *p)
}

var fieldIDToName_GetOrderDetailReq = map[int16]string{
	1: "orderNo",
	2: "userId",
}

type GetOrderDetailResp struct {
	Success bool    `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code    int32   `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message *string `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Order   *Order  `thrift:"order,4" frugal:"4,default,Order" json:"order"`
}

func NewGetOrderDetailResp() *GetOrderDetailResp {
	return &GetOrderDetailResp{
		Code: 0,
	}
}

func (p *GetOrderDetailResp) InitDefault() {
	p.Code = 0
}

func (p *GetOrderDetailResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *GetOrderDetailResp) GetCode() (v int32) {
	return p.Code
}

var GetOrderDetailResp_Message_DEFAULT string

func (p *GetOrderDetailResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return GetOrderDetailResp_Message_DEFAULT
	}
	return *p.Message
}

var GetOrderDetailResp_Order_DEFAULT *Order

func (p *GetOrderDetailResp) GetOrder() (v *Order) {
	if !p.IsSetOrder() {
		return GetOrderDetailResp_Order_DEFAULT
	}
	return p.Order
}
func (p *GetOrderDetailResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *GetOrderDetailResp) SetCode(val int32) {
	p.Code = val
}
func (p *GetOrderDetailResp) SetMessage(val *string) {
	p.Message = val
}
func (p *GetOrderDetailResp) SetOrder(val *Order) {
	p.Order = val
}

func (p *GetOrderDetailResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *GetOrderDetailResp) IsSetOrder() bool {
	return p.Order != nil
}

func (p *GetOrderDetailResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetOrderDetailResp(%+v)", *p)
}

var fieldIDToName_GetOrderDetailResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "order",
}

type QueryOrderReq struct {
	OrderNo  *string      `thrift:"orderNo,1,optional" frugal:"1,optional,string" json:"orderNo,omitempty"`
	UserId   *int64       `thrift:"userId,2,optional" frugal:"2,optional,i64" json:"userId,omitempty"`
	Status   *OrderStatus `thrift:"status,3,optional" frugal:"3,optional,OrderStatus" json:"status,omitempty"`
	Page     int32        `thrift:"page,4" frugal:"4,default,i32" json:"page"`
	PageSize int32        `thrift:"pageSize,5" frugal:"5,default,i32" json:"pageSize"`
}

func NewQueryOrderReq() *QueryOrderReq {
	return &QueryOrderReq{
		Page:     1,
		PageSize: 10,
	}
}

func (p *QueryOrderReq) InitDefault() {
	p.Page = 1
	p.PageSize = 10
}

var QueryOrderReq_OrderNo_DEFAULT string

func (p *QueryOrderReq) GetOrderNo() (v string) {
	if !p.IsSetOrderNo() {
		return QueryOrderReq_OrderNo_DEFAULT
	}
	return *p.OrderNo
}

var QueryOrderReq_UserId_DEFAULT int64

func (p *QueryOrderReq) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return QueryOrderReq_UserId_DEFAULT
	}
	return *p.UserId
}

var QueryOrderReq_Status_DEFAULT OrderStatus

func (p *QueryOrderReq) GetStatus() (v OrderStatus) {
	if !p.IsSetStatus() {
		return QueryOrderReq_Status_DEFAULT
	}
	return *p.Status
}

func (p *QueryOrderReq) GetPage() (v int32) {
	return p.Page
}

func (p *QueryOrderReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *QueryOrderReq) SetOrderNo(val *string) {
	p.OrderNo = val
}
func (p *QueryOrderReq) SetUserId(val *int64) {
	p.UserId = val
}
func (p *QueryOrderReq) SetStatus(val *OrderStatus) {
	p.Status = val
}
func (p *QueryOrderReq) SetPage(val int32) {
	p.Page = val
}
func (p *QueryOrderReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *QueryOrderReq) IsSetOrderNo() bool {
	return p.OrderNo != nil
}

func (p *QueryOrderReq) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *QueryOrderReq) IsSetStatus() bool {
	return p.Status != nil
}

func (p *QueryOrderReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderReq(%+v)", *p)
}

var fieldIDToName_QueryOrderReq = map[int16]string{
	1: "orderNo",
	2: "userId",
	3: "status",
	4: "page",
	5: "pageSize",
}

type QueryOrderResp struct {
	Success  bool     `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code     int32    `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message  *string  `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	Total    int32    `thrift:"total,4" frugal:"4,default,i32" json:"total"`
	Page     int32    `thrift:"page,5" frugal:"5,default,i32" json:"page"`
	PageSize int32    `thrift:"pageSize,6" frugal:"6,default,i32" json:"pageSize"`
	Orders   []*Order `thrift:"orders,7" frugal:"7,default,list<Order>" json:"orders"`
}

func NewQueryOrderResp() *QueryOrderResp {
	return &QueryOrderResp{
		Code: 0,
	}
}

func (p *QueryOrderResp) InitDefault() {
	p.Code = 0
}

func (p *QueryOrderResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *QueryOrderResp) GetCode() (v int32) {
	return p.Code
}

var QueryOrderResp_Message_DEFAULT string

func (p *QueryOrderResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return QueryOrderResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *QueryOrderResp) GetTotal() (v int32) {
	return p.Total
}

func (p *QueryOrderResp) GetPage() (v int32) {
	return p.Page
}

func (p *QueryOrderResp) GetPageSize() (v int32) {
	return p.PageSize
}

func (p *QueryOrderResp) GetOrders() (v []*Order) {
	return p.Orders
}
func (p *QueryOrderResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *QueryOrderResp) SetCode(val int32) {
	p.Code = val
}
func (p *QueryOrderResp) SetMessage(val *string) {
	p.Message = val
}
func (p *QueryOrderResp) SetTotal(val int32) {
	p.Total = val
}
func (p *QueryOrderResp) SetPage(val int32) {
	p.Page = val
}
func (p *QueryOrderResp) SetPageSize(val int32) {
	p.PageSize = val
}
func (p *QueryOrderResp) SetOrders(val []*Order) {
	p.Orders = val
}

func (p *QueryOrderResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *QueryOrderResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryOrderResp(%+v)", *p)
}

var fieldIDToName_QueryOrderResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "total",
	5: "page",
	6: "pageSize",
	7: "orders",
}

type UpdateOrderStatusReq struct {
	OrderNo string      `thrift:"orderNo,1" frugal:"1,default,string" json:"orderNo"`
	Status  OrderStatus `thrift:"status,2" frugal:"2,default,OrderStatus" json:"status"`
	UserId  int64       `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
}

func NewUpdateOrderStatusReq() *UpdateOrderStatusReq {
	return &UpdateOrderStatusReq{}
}

func (p *UpdateOrderStatusReq) InitDefault() {
}

func (p *UpdateOrderStatusReq) GetOrderNo() (v string) {
	return p.OrderNo
}

func (p *UpdateOrderStatusReq) GetStatus() (v OrderStatus) {
	return p.Status
}

func (p *UpdateOrderStatusReq) GetUserId() (v int64) {
	return p.UserId
}
func (p *UpdateOrderStatusReq) SetOrderNo(val string) {
	p.OrderNo = val
}
func (p *UpdateOrderStatusReq) SetStatus(val OrderStatus) {
	p.Status = val
}
func (p *UpdateOrderStatusReq) SetUserId(val int64) {
	p.UserId = val
}

func (p *UpdateOrderStatusReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateOrderStatusReq(%+v)", *p)
}

var fieldIDToName_UpdateOrderStatusReq = map[int16]string{
	1: "orderNo",
	2: "status",
	3: "userId",
}

type UpdateOrderStatusResp struct {
	Success    bool        `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Code       int32       `thrift:"code,2" frugal:"2,default,i32" json:"code"`
	Message    *string     `thrift:"message,3,optional" frugal:"3,optional,string" json:"message,omitempty"`
	OldStatus  OrderStatus `thrift:"oldStatus,4" frugal:"4,default,OrderStatus" json:"oldStatus"`
	NewStatus_ OrderStatus `thrift:"newStatus,5" frugal:"5,default,OrderStatus" json:"newStatus"`
}

func NewUpdateOrderStatusResp() *UpdateOrderStatusResp {
	return &UpdateOrderStatusResp{
		Code: 0,
	}
}

func (p *UpdateOrderStatusResp) InitDefault() {
	p.Code = 0
}

func (p *UpdateOrderStatusResp) GetSuccess() (v bool) {
	return p.Success
}

func (p *UpdateOrderStatusResp) GetCode() (v int32) {
	return p.Code
}

var UpdateOrderStatusResp_Message_DEFAULT string

func (p *UpdateOrderStatusResp) GetMessage() (v string) {
	if !p.IsSetMessage() {
		return UpdateOrderStatusResp_Message_DEFAULT
	}
	return *p.Message
}

func (p *UpdateOrderStatusResp) GetOldStatus() (v OrderStatus) {
	return p.OldStatus
}

func (p *UpdateOrderStatusResp) GetNewStatus_() (v OrderStatus) {
	return p.NewStatus_
}
func (p *UpdateOrderStatusResp) SetSuccess(val bool) {
	p.Success = val
}
func (p *UpdateOrderStatusResp) SetCode(val int32) {
	p.Code = val
}
func (p *UpdateOrderStatusResp) SetMessage(val *string) {
	p.Message = val
}
func (p *UpdateOrderStatusResp) SetOldStatus(val OrderStatus) {
	p.OldStatus = val
}
func (p *UpdateOrderStatusResp) SetNewStatus_(val OrderStatus) {
	p.NewStatus_ = val
}

func (p *UpdateOrderStatusResp) IsSetMessage() bool {
	return p.Message != nil
}

func (p *UpdateOrderStatusResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateOrderStatusResp(%+v)", *p)
}

var fieldIDToName_UpdateOrderStatusResp = map[int16]string{
	1: "success",
	2: "code",
	3: "message",
	4: "oldStatus",
	5: "newStatus",
}

type OrderService interface {
	CreateOrder(ctx context.Context, req *CreateOrderReq) (r *CreateOrderResp, err error)

	PayOrder(ctx context.Context, req *PayOrderReq) (r *PayOrderResp, err error)

	CancelOrder(ctx context.Context, req *CancelOrderReq) (r *CancelOrderResp, err error)

	GetOrderDetail(ctx context.Context, req *GetOrderDetailReq) (r *GetOrderDetailResp, err error)

	QueryOrders(ctx context.Context, req *QueryOrderReq) (r *QueryOrderResp, err error)

	UpdateOrderStatus(ctx context.Context, req *UpdateOrderStatusReq) (r *UpdateOrderStatusResp, err error)
}

type OrderServiceCreateOrderArgs struct {
	Req *CreateOrderReq `thrift:"req,1" frugal:"1,default,CreateOrderReq" json:"req"`
}

func NewOrderServiceCreateOrderArgs() *OrderServiceCreateOrderArgs {
	return &OrderServiceCreateOrderArgs{}
}

func (p *OrderServiceCreateOrderArgs) InitDefault() {
}

var OrderServiceCreateOrderArgs_Req_DEFAULT *CreateOrderReq

func (p *OrderServiceCreateOrderArgs) GetReq() (v *CreateOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCreateOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCreateOrderArgs) SetReq(val *CreateOrderReq) {
	p.Req = val
}

func (p *OrderServiceCreateOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCreateOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCreateOrderResult struct {
	Success *CreateOrderResp `thrift:"success,0,optional" frugal:"0,optional,CreateOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCreateOrderResult() *OrderServiceCreateOrderResult {
	return &OrderServiceCreateOrderResult{}
}

func (p *OrderServiceCreateOrderResult) InitDefault() {
}

var OrderServiceCreateOrderResult_Success_DEFAULT *CreateOrderResp

func (p *OrderServiceCreateOrderResult) GetSuccess() (v *CreateOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCreateOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCreateOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateOrderResp)
}

func (p *OrderServiceCreateOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCreateOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCreateOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCreateOrderResult = map[int16]string{
	0: "success",
}

type OrderServicePayOrderArgs struct {
	Req *PayOrderReq `thrift:"req,1" frugal:"1,default,PayOrderReq" json:"req"`
}

func NewOrderServicePayOrderArgs() *OrderServicePayOrderArgs {
	return &OrderServicePayOrderArgs{}
}

func (p *OrderServicePayOrderArgs) InitDefault() {
}

var OrderServicePayOrderArgs_Req_DEFAULT *PayOrderReq

func (p *OrderServicePayOrderArgs) GetReq() (v *PayOrderReq) {
	if !p.IsSetReq() {
		return OrderServicePayOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServicePayOrderArgs) SetReq(val *PayOrderReq) {
	p.Req = val
}

func (p *OrderServicePayOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServicePayOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePayOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServicePayOrderArgs = map[int16]string{
	1: "req",
}

type OrderServicePayOrderResult struct {
	Success *PayOrderResp `thrift:"success,0,optional" frugal:"0,optional,PayOrderResp" json:"success,omitempty"`
}

func NewOrderServicePayOrderResult() *OrderServicePayOrderResult {
	return &OrderServicePayOrderResult{}
}

func (p *OrderServicePayOrderResult) InitDefault() {
}

var OrderServicePayOrderResult_Success_DEFAULT *PayOrderResp

func (p *OrderServicePayOrderResult) GetSuccess() (v *PayOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServicePayOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServicePayOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*PayOrderResp)
}

func (p *OrderServicePayOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServicePayOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServicePayOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServicePayOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceCancelOrderArgs struct {
	Req *CancelOrderReq `thrift:"req,1" frugal:"1,default,CancelOrderReq" json:"req"`
}

func NewOrderServiceCancelOrderArgs() *OrderServiceCancelOrderArgs {
	return &OrderServiceCancelOrderArgs{}
}

func (p *OrderServiceCancelOrderArgs) InitDefault() {
}

var OrderServiceCancelOrderArgs_Req_DEFAULT *CancelOrderReq

func (p *OrderServiceCancelOrderArgs) GetReq() (v *CancelOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceCancelOrderArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceCancelOrderArgs) SetReq(val *CancelOrderReq) {
	p.Req = val
}

func (p *OrderServiceCancelOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceCancelOrderArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderArgs = map[int16]string{
	1: "req",
}

type OrderServiceCancelOrderResult struct {
	Success *CancelOrderResp `thrift:"success,0,optional" frugal:"0,optional,CancelOrderResp" json:"success,omitempty"`
}

func NewOrderServiceCancelOrderResult() *OrderServiceCancelOrderResult {
	return &OrderServiceCancelOrderResult{}
}

func (p *OrderServiceCancelOrderResult) InitDefault() {
}

var OrderServiceCancelOrderResult_Success_DEFAULT *CancelOrderResp

func (p *OrderServiceCancelOrderResult) GetSuccess() (v *CancelOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceCancelOrderResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceCancelOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*CancelOrderResp)
}

func (p *OrderServiceCancelOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceCancelOrderResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceCancelOrderResult(%+v)", *p)
}

var fieldIDToName_OrderServiceCancelOrderResult = map[int16]string{
	0: "success",
}

type OrderServiceGetOrderDetailArgs struct {
	Req *GetOrderDetailReq `thrift:"req,1" frugal:"1,default,GetOrderDetailReq" json:"req"`
}

func NewOrderServiceGetOrderDetailArgs() *OrderServiceGetOrderDetailArgs {
	return &OrderServiceGetOrderDetailArgs{}
}

func (p *OrderServiceGetOrderDetailArgs) InitDefault() {
}

var OrderServiceGetOrderDetailArgs_Req_DEFAULT *GetOrderDetailReq

func (p *OrderServiceGetOrderDetailArgs) GetReq() (v *GetOrderDetailReq) {
	if !p.IsSetReq() {
		return OrderServiceGetOrderDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceGetOrderDetailArgs) SetReq(val *GetOrderDetailReq) {
	p.Req = val
}

func (p *OrderServiceGetOrderDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceGetOrderDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderDetailArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderDetailArgs = map[int16]string{
	1: "req",
}

type OrderServiceGetOrderDetailResult struct {
	Success *GetOrderDetailResp `thrift:"success,0,optional" frugal:"0,optional,GetOrderDetailResp" json:"success,omitempty"`
}

func NewOrderServiceGetOrderDetailResult() *OrderServiceGetOrderDetailResult {
	return &OrderServiceGetOrderDetailResult{}
}

func (p *OrderServiceGetOrderDetailResult) InitDefault() {
}

var OrderServiceGetOrderDetailResult_Success_DEFAULT *GetOrderDetailResp

func (p *OrderServiceGetOrderDetailResult) GetSuccess() (v *GetOrderDetailResp) {
	if !p.IsSetSuccess() {
		return OrderServiceGetOrderDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceGetOrderDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetOrderDetailResp)
}

func (p *OrderServiceGetOrderDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceGetOrderDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceGetOrderDetailResult(%+v)", *p)
}

var fieldIDToName_OrderServiceGetOrderDetailResult = map[int16]string{
	0: "success",
}

type OrderServiceQueryOrdersArgs struct {
	Req *QueryOrderReq `thrift:"req,1" frugal:"1,default,QueryOrderReq" json:"req"`
}

func NewOrderServiceQueryOrdersArgs() *OrderServiceQueryOrdersArgs {
	return &OrderServiceQueryOrdersArgs{}
}

func (p *OrderServiceQueryOrdersArgs) InitDefault() {
}

var OrderServiceQueryOrdersArgs_Req_DEFAULT *QueryOrderReq

func (p *OrderServiceQueryOrdersArgs) GetReq() (v *QueryOrderReq) {
	if !p.IsSetReq() {
		return OrderServiceQueryOrdersArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceQueryOrdersArgs) SetReq(val *QueryOrderReq) {
	p.Req = val
}

func (p *OrderServiceQueryOrdersArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceQueryOrdersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrdersArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrdersArgs = map[int16]string{
	1: "req",
}

type OrderServiceQueryOrdersResult struct {
	Success *QueryOrderResp `thrift:"success,0,optional" frugal:"0,optional,QueryOrderResp" json:"success,omitempty"`
}

func NewOrderServiceQueryOrdersResult() *OrderServiceQueryOrdersResult {
	return &OrderServiceQueryOrdersResult{}
}

func (p *OrderServiceQueryOrdersResult) InitDefault() {
}

var OrderServiceQueryOrdersResult_Success_DEFAULT *QueryOrderResp

func (p *OrderServiceQueryOrdersResult) GetSuccess() (v *QueryOrderResp) {
	if !p.IsSetSuccess() {
		return OrderServiceQueryOrdersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceQueryOrdersResult) SetSuccess(x interface{}) {
	p.Success = x.(*QueryOrderResp)
}

func (p *OrderServiceQueryOrdersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceQueryOrdersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceQueryOrdersResult(%+v)", *p)
}

var fieldIDToName_OrderServiceQueryOrdersResult = map[int16]string{
	0: "success",
}

type OrderServiceUpdateOrderStatusArgs struct {
	Req *UpdateOrderStatusReq `thrift:"req,1" frugal:"1,default,UpdateOrderStatusReq" json:"req"`
}

func NewOrderServiceUpdateOrderStatusArgs() *OrderServiceUpdateOrderStatusArgs {
	return &OrderServiceUpdateOrderStatusArgs{}
}

func (p *OrderServiceUpdateOrderStatusArgs) InitDefault() {
}

var OrderServiceUpdateOrderStatusArgs_Req_DEFAULT *UpdateOrderStatusReq

func (p *OrderServiceUpdateOrderStatusArgs) GetReq() (v *UpdateOrderStatusReq) {
	if !p.IsSetReq() {
		return OrderServiceUpdateOrderStatusArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *OrderServiceUpdateOrderStatusArgs) SetReq(val *UpdateOrderStatusReq) {
	p.Req = val
}

func (p *OrderServiceUpdateOrderStatusArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *OrderServiceUpdateOrderStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateOrderStatusArgs(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateOrderStatusArgs = map[int16]string{
	1: "req",
}

type OrderServiceUpdateOrderStatusResult struct {
	Success *UpdateOrderStatusResp `thrift:"success,0,optional" frugal:"0,optional,UpdateOrderStatusResp" json:"success,omitempty"`
}

func NewOrderServiceUpdateOrderStatusResult() *OrderServiceUpdateOrderStatusResult {
	return &OrderServiceUpdateOrderStatusResult{}
}

func (p *OrderServiceUpdateOrderStatusResult) InitDefault() {
}

var OrderServiceUpdateOrderStatusResult_Success_DEFAULT *UpdateOrderStatusResp

func (p *OrderServiceUpdateOrderStatusResult) GetSuccess() (v *UpdateOrderStatusResp) {
	if !p.IsSetSuccess() {
		return OrderServiceUpdateOrderStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *OrderServiceUpdateOrderStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateOrderStatusResp)
}

func (p *OrderServiceUpdateOrderStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *OrderServiceUpdateOrderStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OrderServiceUpdateOrderStatusResult(%+v)", *p)
}

var fieldIDToName_OrderServiceUpdateOrderStatusResult = map[int16]string{
	0: "success",
}
