// Code generated by Kitex v0.15.2. DO NOT EDIT.

package orderservice

import (
	"context"
	api "ecommerce/order-service/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOrder(ctx context.Context, req *api.CreateOrderReq, callOptions ...callopt.Option) (r *api.CreateOrderResp, err error)
	PayOrder(ctx context.Context, req *api.PayOrderReq, callOptions ...callopt.Option) (r *api.PayOrderResp, err error)
	CancelOrder(ctx context.Context, req *api.CancelOrderReq, callOptions ...callopt.Option) (r *api.CancelOrderResp, err error)
	GetOrderDetail(ctx context.Context, req *api.GetOrderDetailReq, callOptions ...callopt.Option) (r *api.GetOrderDetailResp, err error)
	QueryOrders(ctx context.Context, req *api.QueryOrderReq, callOptions ...callopt.Option) (r *api.QueryOrderResp, err error)
	UpdateOrderStatus(ctx context.Context, req *api.UpdateOrderStatusReq, callOptions ...callopt.Option) (r *api.UpdateOrderStatusResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kOrderServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOrderServiceClient struct {
	*kClient
}

func (p *kOrderServiceClient) CreateOrder(ctx context.Context, req *api.CreateOrderReq, callOptions ...callopt.Option) (r *api.CreateOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOrder(ctx, req)
}

func (p *kOrderServiceClient) PayOrder(ctx context.Context, req *api.PayOrderReq, callOptions ...callopt.Option) (r *api.PayOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PayOrder(ctx, req)
}

func (p *kOrderServiceClient) CancelOrder(ctx context.Context, req *api.CancelOrderReq, callOptions ...callopt.Option) (r *api.CancelOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOrder(ctx, req)
}

func (p *kOrderServiceClient) GetOrderDetail(ctx context.Context, req *api.GetOrderDetailReq, callOptions ...callopt.Option) (r *api.GetOrderDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOrderDetail(ctx, req)
}

func (p *kOrderServiceClient) QueryOrders(ctx context.Context, req *api.QueryOrderReq, callOptions ...callopt.Option) (r *api.QueryOrderResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrders(ctx, req)
}

func (p *kOrderServiceClient) UpdateOrderStatus(ctx context.Context, req *api.UpdateOrderStatusReq, callOptions ...callopt.Option) (r *api.UpdateOrderStatusResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateOrderStatus(ctx, req)
}
