// Code generated by Kitex v0.15.2. DO NOT EDIT.

package orderservice

import (
	"context"
	api "ecommerce/order-service/kitex_gen/api"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateOrder": kitex.NewMethodInfo(
		createOrderHandler,
		newOrderServiceCreateOrderArgs,
		newOrderServiceCreateOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PayOrder": kitex.NewMethodInfo(
		payOrderHandler,
		newOrderServicePayOrderArgs,
		newOrderServicePayOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CancelOrder": kitex.NewMethodInfo(
		cancelOrderHandler,
		newOrderServiceCancelOrderArgs,
		newOrderServiceCancelOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetOrderDetail": kitex.NewMethodInfo(
		getOrderDetailHandler,
		newOrderServiceGetOrderDetailArgs,
		newOrderServiceGetOrderDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"QueryOrders": kitex.NewMethodInfo(
		queryOrdersHandler,
		newOrderServiceQueryOrdersArgs,
		newOrderServiceQueryOrdersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateOrderStatus": kitex.NewMethodInfo(
		updateOrderStatusHandler,
		newOrderServiceUpdateOrderStatusArgs,
		newOrderServiceUpdateOrderStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*api.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.OrderServiceCreateOrderArgs)
	realResult := result.(*api.OrderServiceCreateOrderResult)
	success, err := handler.(api.OrderService).CreateOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCreateOrderArgs() interface{} {
	return api.NewOrderServiceCreateOrderArgs()
}

func newOrderServiceCreateOrderResult() interface{} {
	return api.NewOrderServiceCreateOrderResult()
}

func payOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.OrderServicePayOrderArgs)
	realResult := result.(*api.OrderServicePayOrderResult)
	success, err := handler.(api.OrderService).PayOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServicePayOrderArgs() interface{} {
	return api.NewOrderServicePayOrderArgs()
}

func newOrderServicePayOrderResult() interface{} {
	return api.NewOrderServicePayOrderResult()
}

func cancelOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.OrderServiceCancelOrderArgs)
	realResult := result.(*api.OrderServiceCancelOrderResult)
	success, err := handler.(api.OrderService).CancelOrder(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceCancelOrderArgs() interface{} {
	return api.NewOrderServiceCancelOrderArgs()
}

func newOrderServiceCancelOrderResult() interface{} {
	return api.NewOrderServiceCancelOrderResult()
}

func getOrderDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.OrderServiceGetOrderDetailArgs)
	realResult := result.(*api.OrderServiceGetOrderDetailResult)
	success, err := handler.(api.OrderService).GetOrderDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceGetOrderDetailArgs() interface{} {
	return api.NewOrderServiceGetOrderDetailArgs()
}

func newOrderServiceGetOrderDetailResult() interface{} {
	return api.NewOrderServiceGetOrderDetailResult()
}

func queryOrdersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.OrderServiceQueryOrdersArgs)
	realResult := result.(*api.OrderServiceQueryOrdersResult)
	success, err := handler.(api.OrderService).QueryOrders(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceQueryOrdersArgs() interface{} {
	return api.NewOrderServiceQueryOrdersArgs()
}

func newOrderServiceQueryOrdersResult() interface{} {
	return api.NewOrderServiceQueryOrdersResult()
}

func updateOrderStatusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.OrderServiceUpdateOrderStatusArgs)
	realResult := result.(*api.OrderServiceUpdateOrderStatusResult)
	success, err := handler.(api.OrderService).UpdateOrderStatus(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newOrderServiceUpdateOrderStatusArgs() interface{} {
	return api.NewOrderServiceUpdateOrderStatusArgs()
}

func newOrderServiceUpdateOrderStatusResult() interface{} {
	return api.NewOrderServiceUpdateOrderStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateOrder(ctx context.Context, req *api.CreateOrderReq) (r *api.CreateOrderResp, err error) {
	var _args api.OrderServiceCreateOrderArgs
	_args.Req = req
	var _result api.OrderServiceCreateOrderResult
	if err = p.c.Call(ctx, "CreateOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PayOrder(ctx context.Context, req *api.PayOrderReq) (r *api.PayOrderResp, err error) {
	var _args api.OrderServicePayOrderArgs
	_args.Req = req
	var _result api.OrderServicePayOrderResult
	if err = p.c.Call(ctx, "PayOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CancelOrder(ctx context.Context, req *api.CancelOrderReq) (r *api.CancelOrderResp, err error) {
	var _args api.OrderServiceCancelOrderArgs
	_args.Req = req
	var _result api.OrderServiceCancelOrderResult
	if err = p.c.Call(ctx, "CancelOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetOrderDetail(ctx context.Context, req *api.GetOrderDetailReq) (r *api.GetOrderDetailResp, err error) {
	var _args api.OrderServiceGetOrderDetailArgs
	_args.Req = req
	var _result api.OrderServiceGetOrderDetailResult
	if err = p.c.Call(ctx, "GetOrderDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) QueryOrders(ctx context.Context, req *api.QueryOrderReq) (r *api.QueryOrderResp, err error) {
	var _args api.OrderServiceQueryOrdersArgs
	_args.Req = req
	var _result api.OrderServiceQueryOrdersResult
	if err = p.c.Call(ctx, "QueryOrders", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateOrderStatus(ctx context.Context, req *api.UpdateOrderStatusReq) (r *api.UpdateOrderStatusResp, err error) {
	var _args api.OrderServiceUpdateOrderStatusArgs
	_args.Req = req
	var _result api.OrderServiceUpdateOrderStatusResult
	if err = p.c.Call(ctx, "UpdateOrderStatus", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
