// Code generated by Kitex v0.15.2. DO NOT EDIT.

package productservice

import (
	"context"
	api "ecommerce/order-service/kitex_gen/api"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateProduct(ctx context.Context, req *api.CreateProductReq, callOptions ...callopt.Option) (r *api.CreateProductResp, err error)
	GetProduct(ctx context.Context, req *api.GetProductReq, callOptions ...callopt.Option) (r *api.GetProductResp, err error)
	UpdateProduct(ctx context.Context, req *api.UpdateProductReq, callOptions ...callopt.Option) (r *api.UpdateProductResp, err error)
	OnlineProduct(ctx context.Context, req *api.OnlineProductReq, callOptions ...callopt.Option) (r *api.OnlineProductResp, err error)
	OfflineProduct(ctx context.Context, req *api.OfflineProductReq, callOptions ...callopt.Option) (r *api.OfflineProductResp, err error)
	DeleteProduct(ctx context.Context, req *api.DeleteProductReq, callOptions ...callopt.Option) (r *api.DeleteProductResp, err error)
	UserSearchProducts(ctx context.Context, req *api.UserSearchProductsReq, callOptions ...callopt.Option) (r *api.UserSearchProductsResp, err error)
	AdminSearchProducts(ctx context.Context, req *api.AdminSearchProductsReq, callOptions ...callopt.Option) (r *api.AdminSearchProductsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductServiceClient struct {
	*kClient
}

func (p *kProductServiceClient) CreateProduct(ctx context.Context, req *api.CreateProductReq, callOptions ...callopt.Option) (r *api.CreateProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateProduct(ctx, req)
}

func (p *kProductServiceClient) GetProduct(ctx context.Context, req *api.GetProductReq, callOptions ...callopt.Option) (r *api.GetProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProduct(ctx, req)
}

func (p *kProductServiceClient) UpdateProduct(ctx context.Context, req *api.UpdateProductReq, callOptions ...callopt.Option) (r *api.UpdateProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProduct(ctx, req)
}

func (p *kProductServiceClient) OnlineProduct(ctx context.Context, req *api.OnlineProductReq, callOptions ...callopt.Option) (r *api.OnlineProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.OnlineProduct(ctx, req)
}

func (p *kProductServiceClient) OfflineProduct(ctx context.Context, req *api.OfflineProductReq, callOptions ...callopt.Option) (r *api.OfflineProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.OfflineProduct(ctx, req)
}

func (p *kProductServiceClient) DeleteProduct(ctx context.Context, req *api.DeleteProductReq, callOptions ...callopt.Option) (r *api.DeleteProductResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteProduct(ctx, req)
}

func (p *kProductServiceClient) UserSearchProducts(ctx context.Context, req *api.UserSearchProductsReq, callOptions ...callopt.Option) (r *api.UserSearchProductsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserSearchProducts(ctx, req)
}

func (p *kProductServiceClient) AdminSearchProducts(ctx context.Context, req *api.AdminSearchProductsReq, callOptions ...callopt.Option) (r *api.AdminSearchProductsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AdminSearchProducts(ctx, req)
}
