// Code generated by Kitex v0.15.2. DO NOT EDIT.

package productservice

import (
	"context"
	api "ecommerce/order-service/kitex_gen/api"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateProduct": kitex.NewMethodInfo(
		createProductHandler,
		newProductServiceCreateProductArgs,
		newProductServiceCreateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetProduct": kitex.NewMethodInfo(
		getProductHandler,
		newProductServiceGetProductArgs,
		newProductServiceGetProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateProduct": kitex.NewMethodInfo(
		updateProductHandler,
		newProductServiceUpdateProductArgs,
		newProductServiceUpdateProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OnlineProduct": kitex.NewMethodInfo(
		onlineProductHandler,
		newProductServiceOnlineProductArgs,
		newProductServiceOnlineProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"OfflineProduct": kitex.NewMethodInfo(
		offlineProductHandler,
		newProductServiceOfflineProductArgs,
		newProductServiceOfflineProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteProduct": kitex.NewMethodInfo(
		deleteProductHandler,
		newProductServiceDeleteProductArgs,
		newProductServiceDeleteProductResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UserSearchProducts": kitex.NewMethodInfo(
		userSearchProductsHandler,
		newProductServiceUserSearchProductsArgs,
		newProductServiceUserSearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AdminSearchProducts": kitex.NewMethodInfo(
		adminSearchProductsHandler,
		newProductServiceAdminSearchProductsArgs,
		newProductServiceAdminSearchProductsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	productServiceServiceInfo                = NewServiceInfo()
	productServiceServiceInfoForClient       = NewServiceInfoForClient()
	productServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return productServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return productServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ProductService"
	handlerType := (*api.ProductService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func createProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceCreateProductArgs)
	realResult := result.(*api.ProductServiceCreateProductResult)
	success, err := handler.(api.ProductService).CreateProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceCreateProductArgs() interface{} {
	return api.NewProductServiceCreateProductArgs()
}

func newProductServiceCreateProductResult() interface{} {
	return api.NewProductServiceCreateProductResult()
}

func getProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceGetProductArgs)
	realResult := result.(*api.ProductServiceGetProductResult)
	success, err := handler.(api.ProductService).GetProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceGetProductArgs() interface{} {
	return api.NewProductServiceGetProductArgs()
}

func newProductServiceGetProductResult() interface{} {
	return api.NewProductServiceGetProductResult()
}

func updateProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceUpdateProductArgs)
	realResult := result.(*api.ProductServiceUpdateProductResult)
	success, err := handler.(api.ProductService).UpdateProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceUpdateProductArgs() interface{} {
	return api.NewProductServiceUpdateProductArgs()
}

func newProductServiceUpdateProductResult() interface{} {
	return api.NewProductServiceUpdateProductResult()
}

func onlineProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceOnlineProductArgs)
	realResult := result.(*api.ProductServiceOnlineProductResult)
	success, err := handler.(api.ProductService).OnlineProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceOnlineProductArgs() interface{} {
	return api.NewProductServiceOnlineProductArgs()
}

func newProductServiceOnlineProductResult() interface{} {
	return api.NewProductServiceOnlineProductResult()
}

func offlineProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceOfflineProductArgs)
	realResult := result.(*api.ProductServiceOfflineProductResult)
	success, err := handler.(api.ProductService).OfflineProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceOfflineProductArgs() interface{} {
	return api.NewProductServiceOfflineProductArgs()
}

func newProductServiceOfflineProductResult() interface{} {
	return api.NewProductServiceOfflineProductResult()
}

func deleteProductHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceDeleteProductArgs)
	realResult := result.(*api.ProductServiceDeleteProductResult)
	success, err := handler.(api.ProductService).DeleteProduct(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceDeleteProductArgs() interface{} {
	return api.NewProductServiceDeleteProductArgs()
}

func newProductServiceDeleteProductResult() interface{} {
	return api.NewProductServiceDeleteProductResult()
}

func userSearchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceUserSearchProductsArgs)
	realResult := result.(*api.ProductServiceUserSearchProductsResult)
	success, err := handler.(api.ProductService).UserSearchProducts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceUserSearchProductsArgs() interface{} {
	return api.NewProductServiceUserSearchProductsArgs()
}

func newProductServiceUserSearchProductsResult() interface{} {
	return api.NewProductServiceUserSearchProductsResult()
}

func adminSearchProductsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ProductServiceAdminSearchProductsArgs)
	realResult := result.(*api.ProductServiceAdminSearchProductsResult)
	success, err := handler.(api.ProductService).AdminSearchProducts(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newProductServiceAdminSearchProductsArgs() interface{} {
	return api.NewProductServiceAdminSearchProductsArgs()
}

func newProductServiceAdminSearchProductsResult() interface{} {
	return api.NewProductServiceAdminSearchProductsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateProduct(ctx context.Context, req *api.CreateProductReq) (r *api.CreateProductResp, err error) {
	var _args api.ProductServiceCreateProductArgs
	_args.Req = req
	var _result api.ProductServiceCreateProductResult
	if err = p.c.Call(ctx, "CreateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProduct(ctx context.Context, req *api.GetProductReq) (r *api.GetProductResp, err error) {
	var _args api.ProductServiceGetProductArgs
	_args.Req = req
	var _result api.ProductServiceGetProductResult
	if err = p.c.Call(ctx, "GetProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProduct(ctx context.Context, req *api.UpdateProductReq) (r *api.UpdateProductResp, err error) {
	var _args api.ProductServiceUpdateProductArgs
	_args.Req = req
	var _result api.ProductServiceUpdateProductResult
	if err = p.c.Call(ctx, "UpdateProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OnlineProduct(ctx context.Context, req *api.OnlineProductReq) (r *api.OnlineProductResp, err error) {
	var _args api.ProductServiceOnlineProductArgs
	_args.Req = req
	var _result api.ProductServiceOnlineProductResult
	if err = p.c.Call(ctx, "OnlineProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) OfflineProduct(ctx context.Context, req *api.OfflineProductReq) (r *api.OfflineProductResp, err error) {
	var _args api.ProductServiceOfflineProductArgs
	_args.Req = req
	var _result api.ProductServiceOfflineProductResult
	if err = p.c.Call(ctx, "OfflineProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteProduct(ctx context.Context, req *api.DeleteProductReq) (r *api.DeleteProductResp, err error) {
	var _args api.ProductServiceDeleteProductArgs
	_args.Req = req
	var _result api.ProductServiceDeleteProductResult
	if err = p.c.Call(ctx, "DeleteProduct", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UserSearchProducts(ctx context.Context, req *api.UserSearchProductsReq) (r *api.UserSearchProductsResp, err error) {
	var _args api.ProductServiceUserSearchProductsArgs
	_args.Req = req
	var _result api.ProductServiceUserSearchProductsResult
	if err = p.c.Call(ctx, "UserSearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AdminSearchProducts(ctx context.Context, req *api.AdminSearchProductsReq) (r *api.AdminSearchProductsResp, err error) {
	var _args api.ProductServiceAdminSearchProductsArgs
	_args.Req = req
	var _result api.ProductServiceAdminSearchProductsResult
	if err = p.c.Call(ctx, "AdminSearchProducts", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
